### PR TITLE
  Clean up shell script style

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
Standardizes and/or updates some of the style inconsistencies in shell scripts:
  - All scripts re-indented properly
  - All backticks replaced with $( ) for subshells
  - All test statements replaced with [ ]
  - If/then and while/do now all appear on same line
  - Heredocs now use <<- instead of << to allow proper indentation
    - These files had to be converted to tab indentation, the only kind recognized by <<-
 
There should be no functional change with this PR, but it needs testing.

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Depends on PR #495 being merged first.

**Comment by WenMeng-NOAA** [comment]
@WalterKolczynski-NOAA I guess this PR is not needed since you already adapt gfs post process scripts in global-workflow repository, right?

**Comment by WenMeng-NOAA** [comment]
@WalterKolczynski-NOAA It seems to me that you already adapted some gfs post process scripts in global-workflow repos., would you like this PR still merged in UPP develop branch?

**Comment by WenMeng-NOAA** [comment]
Close this PR since all gfs post process scripts will be transitioned to the global-workflow repository.

**Pull request closed without merging**
