### PR TITLE
Build UPP on Gaea

### LINKED ISSUE #943: Compile upp on Gaea-C5
Compiling upp on Gaea-C5

### PR DESCRIPTION
**Pull request by DavidBurrows-NCO**
This PR modifies modulefile/gaea.lua to successfully build on Gaea.
The changes made in the module file are in line with changes made for building other global-workflow submodules on Gaea.

Ref #943

### CODE REVIEW

**Comment by DavidBurrows-NCO** [comment]
Hi @WenMeng-NOAA ... This PR also cross references a NOAA-EMC/global-workflow issue: https://github.com/NOAA-EMC/global-workflow/issues/2535. Please let me know if there is anything I need to do. Thank you!

**Comment by FernandoAndrade-NOAA** [comment]
Adding a note here that there were no issues encountered building UPP on Gaea. Changes should not affect results on other machines, RTs on WCOSS2 to verify no changes should be sufficient for merging.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RTs has been completed on WCOSS2 without changed results.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Comment by DavidBurrows-NCO** [comment]
@WenMeng-NOAA @FernandoAndrade-NOAA Thank you both for your time!

**Pull request merged**
