### PR TITLE
Feature/update modules

### LINKED ISSUE #500: Cheyenne hpc-stack module update
Description:
1. UFS-WM hpc-stack modules on Cheynne were migrated to /glade/work/epicufsrt/GMTB/tools for both gnu and Intel
2. intel2022.1 upgrade is on-going UFS-WM repo
3. Need to combine the issues of the new hpc-stack location and compiler update and stack lib package options of g2/libpng/w3emc
4. Additional PRs are expected to cover other RDHPCs

### PR DESCRIPTION
**Pull request by jkbk2004**
Description:
To update the hpc-stack on Cheyenne for both gnu and Intel: new hpc-stack location and updates on g2/libpng/w3emc

Test:
Tested on Cheyenne for the SRW and stand alone build cases.

### CODE REVIEW

**Comment by fossell** [comment]
@jkbk2004 or @mkavulich - Do these updated module versions need to be public-v3 release?

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 Can you open an issue for this PR? Thanks!

**Comment by jkbk2004** [comment]
@WenMeng-NOAA I will create an issue.

**Comment by fossell** [comment]
@jkbk2004 - did you create an issue for this yet? I don't see it, can you link it to the draft PR if you've already created it?

**Comment by jkbk2004** [comment]
@fossell @WenMeng-NOAA  I think I have a trouble to use development side bar in this repo. So I am just adding a direct link here of the issue #500 As hpc-stack updates and sync cases are related to other repos, we may need to merge into develop branch, not in release branch.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@fossell Do you have more comments on this PR?

**Review by fossell — APPROVED** [review]

**Comment by fossell** [comment]
@jkbk2004 - I see this is still a Draft. Will you have more mods as you work through this issue with other repos? Or is this ready to go as is?

**Comment by jkbk2004** [comment]
> @jkbk2004 - I see this is still a Draft. Will you have more mods as you work through this issue with other repos? Or is this ready to go as is?

@fossell I prefer to have some more days since Cheyenne is down. And we can wait to see a progress of srw PR [250](https://github.com/ufs-community/ufs-srweather-app/pull/250)

**Comment by fossell** [comment]
> > @jkbk2004 - I see this is still a Draft. Will you have more mods as you work through this issue with other repos? Or is this ready to go as is?
> 
> @fossell I prefer to have some more days since Cheyenne is down. And we can wait to see a progress of srw PR [250](https://github.com/ufs-community/ufs-srweather-app/pull/250)

@jkbk2004 - Sounds good. Let us know when you're ready and we'll make it ready for review at that point and I can review the final changes.  Thanks!

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on WCOSS1-Dell. No changed results.

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 Would you change this PR from draft request status for merging, or you have more changes added?

**Comment by jkbk2004** [comment]
@WenMeng-NOAA ufs-wm side, intel2022.1 upgrade is on-going. I want to give a week more to merge this PR.

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 We have an UPP major upgrade for 2d decomposition within 2 weeks and it will be implemented in ufs-weather-model.  If your PR need more time after 5/20, I will create a release branch based on the current develop for your PR merging. Please let me know if my proposal is working for you.

**Comment by jkbk2004** [comment]
@WenMeng-NOAA so hpc-stack modulefiles of 2d decomp upgrade will likely be synced with ufs-wm, right? then I think we can hold this PR. My intention is to sync with ufs-wm modulefiles. We don't need any interruption. I am also covering ufs-wm code management side. I can smoothly follow on. If it's better option to close this PR now and reopen later after upgrade, I agree with that option as well.

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 The upp is configurated as a submodule of FV3 component in ufs-weather-model instead of pre-installed lib at the hpc-stack module for in-line post. There might be a risk your module update PR following after a large PR. Let's wait for one more week to see which PR is ready for merging.

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 May I ask the status of this PR? Thanks!

**Comment by jkbk2004** [comment]
@WenMeng-NOAA I may close the draft and open new one. I still see it will be better to sync modulefiles across machines. There has been a progress on ufs srw app to address this modulefile sync case. I see lua files are directly used on some machines. Is there a reason not using module commands?

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA I may close the draft and open new one. I still see it will be better to sync modulefiles across machines. There has been a progress on ufs srw app to address this modulefile sync case. I see lua files are directly used on some machines. Is there a reason not using module commands?

@jkbk2004 Your plan works for me. Per EIB's suggestion, we changed modulefile on WCOSS2 and some R&D machines in lua format so that library versions may be overridden by setting from upstream applications, e.g. global-workflow.

**Pull request closed without merging**
