### PR TITLE
[production/AQM.v7] Add -check noarg_temp_created to reduce size of err file caused by -check all

### LINKED ISSUE #825: EE2 compliance for AQMv7 for ufs-weather-model, adding -ftrapuv and -check all for DEBUG builds
AQM.v7 need to meet NCO EE2 compliance with the ufs-weather-model/fv3atm/upp code.

This issue does differ from using release/aqm_v7 as it pertains only to needs for ufs-weather-model/FV3/upp

- A new branch `production/AQM.v7` will need to be created (completed)
- Changes to accomplish adding -ftrapuv and -check all made in appropriate locations for DEBUG builds.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
in production/AQM.v7 (for FV3/upp) Add -check noarg_temp_created in DEBUG Fortran flags to reduce size of err file caused by -check all

Closes #825

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
updated title to add [production/AQM.v7], apologies if that caused any confusion.

**Comment by WenMeng-NOAA** [comment]
@BrianCurtis-NOAA Should this change to be incorporated branch release/aqm_v7 too?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA Should this change to be incorporated branch release/aqm_v7 too?

I don't think i've heard that it was needed there. If it is later I'll get a PR added for that branch.

I'm ready for merge.

**Comment by WenMeng-NOAA** [comment]
> > @BrianCurtis-NOAA Should this change to be incorporated branch release/aqm_v7 too?
> 
> I don't think i've heard that it was needed there. If it is later I'll get a PR added for that branch.
> 
> I'm ready for merge.

@BrianCurtis-NOAA Thanks for clarifying.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
