### PR TITLE
Port release/gefs_v12 to WCOSS2 for GEFSv12 

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**
Port UPP for GEFSv12.1 to WCOSS2

### CODE REVIEW

**Comment by XianwuXue-NOAA** [comment]
@WenMeng-NOAA Because you have add "The bug fix for a printout of a out of boundary array" in branch release/gefs_v12, and the wcoss2 transition does not allow the bug fix, so should I change it back?

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA Because you have add "The bug fix for a printout of a out of boundary array" in branch release/gefs_v12, and the wcoss2 transition does not allow the bug fix, so should I change it back?

That's the hot fix for ops. code and will have no changed results in ops. products. I would think it should include in the package for wcoss2 transition. You might consult with Steven too.

**Comment by XianwuXue-NOAA** [comment]
@WenMeng-NOAA Thanks. I will consult with Steven and cc to you.

**Comment by XianwuXue-NOAA** [comment]
@WenMeng-NOAA Since Steven has approved this code changes, please find a time to review my changes and approve it. Thanks

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@XianwuXue-NOAA Your changes look good for me. I assume the UPP executable can be successfully run through with GEFS model history files on wcoss2, right?

**Comment by XianwuXue-NOAA** [comment]
@WenMeng-NOAA Yes, it can run successfully on WCOSS2

**Comment by WenMeng-NOAA** [comment]
@XianwuXue-NOAA Thanks for confirming. This PR is ready for merging.

**Comment by WenMeng-NOAA** [comment]
@XianwuXue-NOAA Please let me know if you need a tag for NCO code delivery.

**Pull request merged**
