### PR TITLE
turn on doxygen build in CI

### LINKED ISSUE #847: turn on documentation builds in CI
The doxygen build can be turned on in CI by added -DENABLE_DOCS=ON to the cmake line at the bottom of the yml file.

If doxygen WARN_AS_ERROR is also turned on in the Doxyfile,in, the the CI will require that all new code have doxygen documentation. (It cannot ensure that it is good documentation, just that it is present.)

This is extremely useful for policing all contributions fairly and with immediate programmer feedback. This raises the quality of documentation in contributions quite a bit, before the code is even reviewed, saving team time.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #847

This will build documentation in the CI, but will not fail CI for any documentation warnings.

However, this will causes the documentation warnings to appear in the build output, and developers can target them clear them up.

Once they are all gone, we can turn on WARN_AS_ERROR in doxygen, and ensure that new code always passes documentation check before being merged.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett Please sync your branch with the latest UPP develop.

**Comment by edwardhartnett** [comment]
Done.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Please run the testing from your end.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA Please run the testing from your end.

No changes from my side of RTs on Hera, Hercules, and Orion.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 without baseline changes. This PR is ready for merging.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
