### PR TITLE
RRFS-MPAS: Provide TSOIL and SOILW (9 levels) in native-level GRIB2 files

### LINKED ISSUE #1053: RRFS-MPAS: TSOIL and SOILW needed in native-level GRIB2 files
For RRFS-MPAS applications, GSL requests that TSOIL (soil temperature) and SOILW (soil moisture) be included at all nine levels within the native-level GRIB2 files.  

This issue can be assigned to @jaymes-kenyon

### PR DESCRIPTION
**Pull request by jaymes-kenyon**
For RRFS-MPAS applications, this update provides TSOIL and SOILW within the native-level GRIB2 files for all nine soil levels.  It has been successfully tested in a real-time RRFS-MPAS configuration.

This PR addresses issue #1053.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon Please validate my UPP standalone test at /home/Wen.Meng/stmp2/mpas_2024082112 on Hera.
I see new fields added in the dataset WRFNAT as:
```
Wen.Meng@hfe02 mpas_2024082112$ wgrib2 WRFNAT12.tm00 -match TSOIL
1004:572666045:d=2024082100:TSOIL:0-0 m below ground:12 hour fcst:
1006:575599968:d=2024082100:TSOIL:0.01-0.01 m below ground:12 hour fcst:
1008:578401926:d=2024082100:TSOIL:0.04-0.04 m below ground:12 hour fcst:
1010:581131012:d=2024082100:TSOIL:0.1-0.1 m below ground:12 hour fcst:
1012:583799560:d=2024082100:TSOIL:0.3-0.3 m below ground:12 hour fcst:
1014:586353377:d=2024082100:TSOIL:0.6-0.6 m below ground:12 hour fcst:
1016:588861504:d=2024082100:TSOIL:1-1 m below ground:12 hour fcst:
1018:591355880:d=2024082100:TSOIL:1.6-1.6 m below ground:12 hour fcst:
1020:593884099:d=2024082100:TSOIL:3-3 m below ground:12 hour fcst:

Wen.Meng@hfe02 mpas_2024082112$ wgrib2 WRFNAT12.tm00 -match SOILW
1009:580165320:d=2024082100:SOILW:0.04-0.04 m below ground:12 hour fcst:
1011:582875577:d=2024082100:SOILW:0.1-0.1 m below ground:12 hour fcst:
1013:585465416:d=2024082100:SOILW:0.3-0.3 m below ground:12 hour fcst:
1015:587967861:d=2024082100:SOILW:0.6-0.6 m below ground:12 hour fcst:
1017:590486621:d=2024082100:SOILW:1-1 m below ground:12 hour fcst:
1019:593010472:d=2024082100:SOILW:1.6-1.6 m below ground:12 hour fcst:
1021:595484678:d=2024082100:SOILW:3-3 m below ground:12 hour fcst:
```

**Comment by jaymes-kenyon** [comment]
@WenMeng-NOAA — Your test looks good!  The WRFNAT dataset now contains 9 levels of TSOIL and SOILW, as expected.  Thanks!

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA @FernandoAndrade-NOAA You may start the UPP RTs on R&D platforms. There should be no baseline update with this PR.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have completed on WCOSS2 without baseline change.

**Comment by gspetro-NOAA** [comment]
No changes in RT results across Hera, Hercules, and Orion. :)

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA Please go head to approve this PR.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
