### PR TITLE
update pointer to CMakeModules

### PR DESCRIPTION
**Pull request by aerorahul**
update pointer to CMakeModules following [CMakeModules PR 40](https://github.com/NOAA-EMC/CMakeModules/pull/40)

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]

**Comment by fossell** [comment]
Is this change also need for SRW app v1.0 (release/public-v2 branch)?  Or is this purely development?

**Comment by climbfuji** [comment]
> Is this change also need for SRW app v1.0 (release/public-v2 branch)? Or is this purely development?

I can tell you that it is not needed for MRW app v1.1 (release/public-v1) - I can't tell you right away if it should go into release/public-v2. I hope it will, though.

**Comment by WenMeng-NOAA** [comment]
@fossell and @aerorahul  I might think this #PR is an update of CAMKE build capacity, will have no impact on GNC build and change the UPP regression tests, right?

**Comment by aerorahul** [comment]
@WenMeng-NOAA 
This PR does not impact GNU builds.
This PR is an update to the cleanup from @climbfuji

**Comment by WenMeng-NOAA** [comment]
@aerorahul Thanks for clarifying. I might wait for @fossell's reviewing.

**Comment by fossell** [comment]
All - apologies for delayed response, had other project priorities to address.  This is ok with me, I'll work with SRW team as needed to see if they will need this for their build.

**Review by fossell — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@fossell Thanks for confirming. I will proceed merging in branch develop.

**Pull request merged**
