### PR TITLE
Update UPP modulefile on Hera, Orion and Hercules with the spack-stack-1.5.0

### LINKED ISSUE #814: Update modulefiles for Hera and Orion with the spack-stack-1.5.0
The UPP modulefiles for Hera and Orion need updates with the spack-stack-1.5.0.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Update modulefiles on Hera, Orion and Hercules with the spack-stack-1.5.0.

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
Looks good to me! I'll go ahead and ensure the job cards within the test suite on Hera, Orion, and Hercules have been switched to spack stack 1.5.0 and start a final test run through Jenkins today. Thanks for working on and helping out with this!

**Comment by FernandoAndrade-NOAA** [comment]
Also addresses #741, this PR upgrades to ip version 4.3.0

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA The module statements within rt.sh will need to be updated to utilize spack-stack. It resulted in errors during the RTs despite running to completion due to hpc stack still being utilized. Could you go ahead and make the appropriate adjustments?

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA The module statements within rt.sh will need to be updated to utilize spack-stack. It resulted in errors during the RTs despite running to completion due to hpc stack still being utilized. Could you go ahead and make the appropriate adjustments?

@FernandoAndrade-NOAA Updated, Please try again.

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA Orion is still rerunning within Jenkins, however Hera still is having issues with the postmsg command not being found. Is that within the prod-utils / prod_utils module? If so there's potential for confusion and conflict as I'm seeing results for both with module spider on Hera and likely Orion when it finishes:
```
[Fernando.Andrade-maldonado@hfe08 spack-testing]$ module spider prod-util

----------------------------------------------------------------------------------------------------------------------------------------------
  prod-util:
----------------------------------------------------------------------------------------------------------------------------------------------
     Versions:
        prod-util/1.2.2

----------------------------------------------------------------------------------------------------------------------------------------------
  For detailed information about a specific "prod-util" package (including how to load the modules) use the module's full name.
  Note that names that have a trailing (E) are extensions provided by other modules.
  For example:

     $ module spider prod-util/1.2.2
----------------------------------------------------------------------------------------------------------------------------------------------



[Fernando.Andrade-maldonado@hfe08 spack-testing]$ module spider prod_util

----------------------------------------------------------------------------------------------------------------------------------------------
  prod_util: prod_util/1.2.2
----------------------------------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "prod_util/1.2.2" module is available to load.

      stack-gcc/9.2.0
      stack-intel/2021.5.0

    Help:
       Product utilities for the NCEP models. This is part of NOAA's NCEPLIBS
      project.
```

**Comment by FernandoAndrade-NOAA** [comment]
That may have not been so clear, I wanted to check and clarify which is the correct prod-util/prod_util and would that mixing and matching be the cause of the failing postmsg commands within rt.sh?

**Comment by WenMeng-NOAA** [comment]
I changed prod-util/1.2.2 to prod_util/1.2.2 on Hera. On Orio, there are prod_util/1.2.2 and prod-util/1.2.2 installed (They are the same).

**Comment by FernandoAndrade-NOAA** [comment]
Hera and Orion UPP RTs finished with changes in the expected tests verified during pretesting. Running Hercules manually now.

**Comment by FernandoAndrade-NOAA** [comment]
Hercules UPP RTs have completed with changes in gfs, 3drtma, and fv3r @WenMeng-NOAA if you could confirm these sort of changes are expected on that machine.
The run directory is available at 
`/work2/noaa/epic/nandoam/regression-testing/upp/hercules/spack-stack-150/UPP/ci/rundir/upp-HERCULES`

**Comment by WenMeng-NOAA** [comment]
> Hercules UPP RTs have completed with changes in gfs, 3drtma, and fv3r @WenMeng-NOAA if you could confirm these sort of changes are expected on that machine. The run directory is available at `/work2/noaa/epic/nandoam/regression-testing/upp/hercules/spack-stack-150/UPP/ci/rundir/upp-HERCULES`

@FernandoAndrade-NOAA Your testing on Hercules looks good for me.

**Comment by WenMeng-NOAA** [comment]
The UPP RT was completed on WCOSS2 without changes.

**Comment by WenMeng-NOAA** [comment]
There will be the UPP RT baseline recreations with this PR:
Hera: rap, hrrr
Orion: fv3r, 3drtma, gfs, rap, hrrr

**Comment by FernandoAndrade-NOAA** [comment]
> > Hercules UPP RTs have completed with changes in gfs, 3drtma, and fv3r @WenMeng-NOAA if you could confirm these sort of changes are expected on that machine. The run directory is available at `/work2/noaa/epic/nandoam/regression-testing/upp/hercules/spack-stack-150/UPP/ci/rundir/upp-HERCULES`
> 
> @FernandoAndrade-NOAA Your testing on Hercules looks good for me.

Thanks! 
Hercules baseline recreations: 3DRTMA, GFS, FV3R

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
