### PR TITLE
update gtg code revision

### PR DESCRIPTION
**Pull request by hsinmulin-NOAA**
Reduce the GTG UPP printout message (https://github.com/NCAR/UPP_GTG/pull/35)

remove "printflag=2" from "gtg_interp.F90" for the configuration file to fully control the printout.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@hsinmulin-NOAA Please change your PR to target the release/rrfs_v1 branch.

**Comment by hsinmulin-NOAA** [comment]
change target UPP version to rrfs_v1 instead of develop

**Comment by hsinmulin-NOAA** [comment]
Target version is changed per request.

**Comment by hsinmulin-NOAA** [comment]
change the source of version to rrfs_v1

**Pull request closed without merging**
