### PR TITLE
Change version number from 8.0.0 to 1.0.0 for UFS release

### PR DESCRIPTION
**Pull request by climbfuji**
Change version number from 8.0.0 to 1.0.0 for UFS release, see discussion in https://github.com/NOAA-EMC/NCEPLIBS/pull/66

### CODE REVIEW

**Review by fossell — APPROVED** [review]

**Comment by climbfuji** [comment]
@fossell @WenMeng-NOAA I merged the PR. Can I ask you to recreate the tag, please? Thanks.

**Comment by fossell** [comment]
@climbfuji I'll do it shortly.

**Comment by fossell** [comment]
@climbfuji - New ufs-v1.0.0 tag has been created.

**Comment by climbfuji** [comment]
Great! Thank you!

**Comment by WenMeng-NOAA** [comment]
Thanks!

**Pull request merged**
