### PR TITLE
fix a bug in AOD calculation

### LINKED ISSUE #488: fix a bug in AOD calculation
aerosol AOD are wrongly double-counted

### PR DESCRIPTION
**Pull request by lipan-NOAA**
issue #488

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@lipan-NOAA It appears to me your changes failed on UPP building. Would you look into that?

**Comment by WenMeng-NOAA** [comment]
@lipan-NOAA Do you think the changes in INITPOST_GFS_NEMS_MPIIO.f can be synced in INITPOST_NETCDF.f which is the interface for reading FV3 model outputs in netcdf? The GFSV17/GEFSV13 output model history files in netcdf only.

**Comment by lipan-NOAA** [comment]
@WenMeng-NOAA it could be, but we have not decided how does GOCART outputs connect to UPP yet.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA it could be, but we have not decided how does GOCART outputs connect to UPP yet.

@lipan-NOAA Got it. You may update the interface for FV3 in netcdf later.

**Comment by WenMeng-NOAA** [comment]
@lipan-NOAA A suggestion on your UPP folk. You might rename EMC_post to UPP via the instructions at 
https://github.com/NOAA-EMC/UPP/discussions/372

**Comment by WenMeng-NOAA** [comment]
@lipan-NOAA I conducted the UPP RT tests with your branch on Dell and saw some changed results in field "AOTK:entire atmosphere". The field by field comparison against the current RT baseline for hrrt have as:
111:77093701:AOTK:entire atmosphere (considered as a single layer):rpn_corr=0.98454:rpn_rms=11.4022

Would you think that is expected change?

**Comment by lipan-NOAA** [comment]
@WenMeng-NOAA yes it is what I expected. Since the factors used in the calculation of PM25 and PM10 were changed.

**Comment by WenMeng-NOAA** [comment]
@lipan-NOAA Thanks for verifying. I will proceed more RT tests on other platforms.

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were conducted on WCOSS1_Cray, WCOSS1-Dell, Hera, WCOSS2. There were changed results from filed AOTK. @lipan-NOAA  confirmed the expected changes. The baselines of hrrr, rap will be recreated with the PR merged.
```
Wen.Meng@clogin02 ptmp$ cat hrrr_2020060118_pe_test/WRFTWO.GrbF04.diff
111:77093497:AOTK:entire atmosphere (considered as a single layer):rpn_corr=0.98454:rpn_rms=11.4022
```

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
