### PR TITLE
Clean out lagacy fv3lam control file and bug fix of tke initialization

### LINKED ISSUE #745: Fix a bug in TKE initialization
In UPP INITPOST_NETCDF.f, QKE was read in from model output and divided by 2 to obtain TKE without accounting for missing values.  

The offending line
https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/INITPOST_NETCDF.f#L1622

should be updated as follow:

if (q2(i,j,l)/=spval)q2(i,j,l)=q2(i,j,l)/2.

A sample TKE post processed output below dashed lines showed many large values due to this bug:

-----------------------------------------------------------------------------------------------
17:111658851:vt=2023060700:1 hybrid level:10 hour fcst:TKE Turbulent Kinetic Energy [J/kg]:
    ndata=14452641:undef=0:mean=7.53534e+19:min=0:max=5e+20
    grid_template=1:winds(N/S):
        rotated lat-lon grid:(4881 x 2961) units 1e-06 input WE:SN output WE:SN res 48
        lat -37.000000 to 37.000000 by 0.025000
        lon 299.000000 to 61.000000 by 0.025000 #points=14452641
        south pole lat=-35.000000 lon=247.000000 angle of rot=0.000000

### LINKED ISSUE #749: Update UPP RT test for RRFS
The UPP RT test for RRFS is configured with obsolete RRFS model history files and UPP control file. Updates are needed:

- new baseline of model history files from RRFS parallel run
- replace obsolete RRFS control file fv3lam* with fv3lam_rrfs*

### LINKED ISSUE #751: Clean up legacy control files and grib2 table file
The following files from UPP/parm would not used for the UPP community support:

- params_grib2_tbl_new_dtc
- postxconfig-NT-.txt
- postxconfig-NT-WRF.txt
- postcntrl.xml
- postcntrl_wrf.xml

Now it is time to clean up them.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main changes are:

- Bug fix of tke initialization from Huiya
- Clean out legacy fv3lam control files
- Update parm/makefile for generating all UFS based application's text control files with unified post_avbfld.xml
- Clean up legacy control files postcntrl* and postcntrl_wrf*
- Clean up legacy grib2 table param*dtc

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA and @FernandoAndrade-NOAA I combined the changes proposed in issue #751 in this PR. Please let me know if you have concerns.

**Comment by FernandoAndrade-NOAA** [comment]
Looks good! Much easier to see it's managed from a single unified fields .xml now. UPP RTs passed on Hera with no changes to results.

Run available here: `/scratch1/NCEPDEV/nems/Fernando.Andrade-maldonado/regression-tests/upp-tests/emc/rt-750`

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 and Orion without changed results.

**Review by HuiyaChuang-NOAA — APPROVED** [review]

**Comment by mkavulich** [comment]
@WenMeng-NOAA, the file  `parm/postxconfig-NT-fv3lam.txt` is being used by the SRW's workflow in the current develop. When updating to this UPP hash, should we transition to using `parm/postxconfig-NT-fv3lam_rrfs.txt`?

**Comment by WenMeng-NOAA** [comment]
@mkavulich Yes, I would recommend parm/postxconfig-NT-fv3lam_rrfs.txt since recent updates for RRFS products are only in it.

**Pull request merged**
