### PR TITLE
Add BUILD_WITH_NEMSIO build option to allow building UPP without nemsio

### LINKED ISSUE #913: Add an option to build UPP executable without nemsio lib
@DusanJovic-NOAA suggests new option to build UPP executable without nemsio library. This will simplify building of upp on system with minimal support for nceplibs, such as github ci or other cloud machines.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
Added BUILD_WITH_NEMSIO cmake option (ON by default), which allows building the UPP executable without nemsio file support and without requiring nemsio library.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA I ran the UPP build script 'comiple_upp.sh' under UPP/tests and got failure as:
```
[ 97%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.x.dir/getIVariableN.f.o
[ 98%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.x.dir/getVariable.f.o
[ 99%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.x.dir/INITPOST_NEMS.f.o
[100%] Linking Fortran executable upp.x
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/intel/2021.5.0/nemsio-2.5.4-gvup4la/lib64/libnemsio.a(nemsio_read.f90.o): In function `nemsio_read_mp_nemsio_readrecgrb8_':
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/cache/build_stage/spack-stage-nemsio-2.5.4-gvup4lazwrieeerhzitvuka772v7t4nn/spack-src/src/nemsio_read.f90:974: undefined reference to `getgbm_'
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/intel/2021.5.0/nemsio-2.5.4-gvup4la/lib64/libnemsio.a(nemsio_read.f90.o): In function `nemsio_read_mp_nemsio_readrecvgrb8_':
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/cache/build_stage/spack-stage-nemsio-2.5.4-gvup4lazwrieeerhzitvuka772v7t4nn/spack-src/src/nemsio_read.f90:1027: undefined reference to `getgbm_'
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/intel/2021.5.0/nemsio-2.5.4-gvup4la/lib64/libnemsio.a(nemsio_read.f90.o): In function `nemsio_read_mp_nemsio_readrecgrb4w34_':
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/cache/build_stage/spack-stage-nemsio-2.5.4-gvup4lazwrieeerhzitvuka772v7t4nn/spack-src/src/nemsio_read.f90:865: undefined reference to `getgbm_'
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/intel/2021.5.0/nemsio-2.5.4-gvup4la/lib64/libnemsio.a(nemsio_read.f90.o): In function `nemsio_read_mp_nemsio_readrecvgrb4w34_':
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/cache/build_stage/spack-stage-nemsio-2.5.4-gvup4lazwrieeerhzitvuka772v7t4nn/spack-src/src/nemsio_read.f90:919: undefined reference to `getgbm_'
make[2]: *** [sorc/ncep_post.fd/CMakeFiles/upp.x.dir/build.make:309: sorc/ncep_post.fd/upp.x] Error 1
make[1]: *** [CMakeFiles/Makefile2:159: sorc/ncep_post.fd/CMakeFiles/upp.x.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by DusanJovic-NOAA** [comment]
@WenMeng-NOAA Please try again. The nemsio library depends on w3emc and bacio, so I had to explicitly add them as dependencies.

https://github.com/NOAA-EMC/NCEPLIBS-nemsio/blob/develop/src/CMakeLists.txt#L42-L43

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Now It works. Thanks!

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Could you modify build scripts compile_upp.sh under /tests to add an option without nemsio lib? You might refer to the option '-w' used for wrf_io lib.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Could you modify build scripts compile_upp.sh under /tests to add an option without nemsio lib? You might refer to the option '-w' used for wrf_io lib.

Done. See 5b6815f

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Your changes look good in my UPP standalone tests. Thanks!

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Can you sync your branch with the latest UPP develop for our merging process?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Can you sync your branch with the latest UPP develop for our merging process?

Done.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. There should be baseline update with this PR.

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Thanks for contributing to the enhancement of UPP, making it more flexible to support various configurations.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2. No baseline update is needed with this PR.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. There should be baseline update with this PR.

RT results look good to go from my side on Hera, Hercules, and Orion.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
