### PR TITLE
Adding SREF products to GEFS v13 (UPP #1013).

### LINKED ISSUE #1013: Add additional products for GEFS v13 to replace SREF
Jun Du compare with GEFS v13 products with operational SREF products and summarized a list of missing SREF products at https://docs.google.com/document/d/1jGdN3lJsn_NS8aKUKyq-E4ftvIkXLfur/edit
He suggests the following products available for GEFS v13:

- [x] Vorticity at 6 levels (850 700 600 500 300 250)

- [x] Td at 4 levels (850 700 500 300)     

- [x] Composite reflectivity

- [x] Echo top 

- [x] U, V, H at 275 and 225hPa levels (or I change to other levels 250 and 100hPa?) (GEFS outputs every 25 or 50hPa in vertical?)

- [x] Total cloud cover (%)

- [x] Cloud top height (use pressure instead of height?)

### PR DESCRIPTION
**Pull request by ChristopherHill-NOAA**
UPP #1013 
The GEFS control file is augmented with five variables not already included from SREF, in advance of GEFS v13 replacing SREF.

The five variables are:
DPT_ON_ISOBARIC_SFC  ( at 30000. 50000. 70000. 85000. [Pa] )
INST_TCDC_ON_ENTIRE_ATMOS
HGT_ON_CLOUD_TOP
REFC_ON_ENTIRE_ATMOS
RETOP_ON_ENTIRE_ATMOS_SINGLE_LYR

@JunDu-NOAA has verified the content of a singular Grib output file that resulted from a UPP test invoking the updated control file (postxconfig-NT-gefs.txt).

### CODE REVIEW

**Comment by JunDu-NOAA** [comment]
Looks good and go ahead

**Comment by WenMeng-NOAA** [comment]
@JunDu-NOAA Please validate my test results at /u/wen.meng/ptmp/post_gefs_2019030600-after on dogwood.

**Comment by JunDu-NOAA** [comment]
I have checked your directory and verified all five variables are correct.
-- Jun

**Comment by ChristopherHill-NOAA** [comment]
The pressure levels of 22500 and 27500 (Pa) have been added to the GEFS control file for each of the following variables:
HGT_ON_ISOBARIC_SURFACE
UGRD_ON_ISOBARIC_SURFACE
VGRD_ON_ISOBARIC_SURFACE

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on R&D machines. There should be no baseline update since gefsv13 is not included in the RTs.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2, without baseline change.

**Review by FernandoAndrade-NOAA — APPROVED** [review]
No changes in RT results for Hera, Hercules, and Orion.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
