### PR TITLE
UPP WAFS update

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
1. UPP WAFS outputs on ICAO standard levels with the exact number
2. sorc/ncep_post.fd/MDLFLD.f changes interface to call gtg_algo()
3. scripts/exgfs_nceppost.sh.ecf, UPP WAFS outputs hourly when forecast is between 6 to 12, every 3 hours other than that.

### CODE REVIEW

**Comment by YaliMao-NOAA** [comment]
https://github.com/NCAR/UPP_GTG
master branch is updated, though with a bug to be fixed. It can pass compiling and generate GTG though it's all missing values at low levels between 725-1000mb.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA Can you change the PR targeting to upstream branch release/gfs_v16 instead of develop?

**Comment by YaliMao-NOAA** [comment]
Changed PR targeting to release/gfs_v16.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA Please sync your branch with the upstream UPP branch release/gfs_16.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The gfs v16 regression test was conducted on Dell and Hera. No changed results in master, flux and special data sets. This branch is ready for merging.

**Pull request merged**
