### PR TITLE
switched to local copy of FindNetCDF.cmake

### LINKED ISSUE #384: Need to copy FindNetcdf.cmake into cmake directory, and not depend on CMakeModules, in order for releases to work
When you mark a release in GitHub, it packages up the repo for you and provides that as a .tar.gz file, available on the "Releases" page.

However, in the case of UPP, all these tarballs are broken, because the GitHub packaging is not smart enough to handle submodules. :-(

As a result, you need to copy the FindNetCDF.cmake file into your cmake directory, and use it from there. This is unfortunate, because it is a copy of the .cmake file, which will have to be manually updated to bring in any changes to the CMakeModules version of the file. However, this is just a consequence of how CMake works, and how GitHub packages files, so with the NCEPLIBS projects, we just live with these extra copies.

The error you will get attempting to build from one of your releases is:

```
 >> 11    CMake Error at CMakeLists.txt:34 (find_package):
     12      By not providing "FindNetCDF.cmake" in CMAKE_MODULE_PATH this project has
     13      asked CMake to find a package configuration file provided by "NetCDF", but
     14      CMake did not find one.
     15    
     16      Could not find a package configuration file provided by "NetCDF" with any
     17      of the following names:

```

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #384 

switched to local copy of FindNetCDF.cmake

### CODE REVIEW

**Review by kgerheiser — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were successfully completed on WCOSS-Dell, WCOSS-Cray and Hera. No baseline changes.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by fossell** [comment]
Proposed changes look ok to me, testing build and quick case now for community standalone apps.  Will also need to update documentation accordingly to address removal of submodules and change to clone commands (no need for recurse submodules). 
@hertneky - Please take a look at these proposed mods, we'll need to make documentation updates in develop.

**Review by fossell — APPROVED** [review]

**Comment by fossell** [comment]
Please feel free to merge, I'll create a separate issue for updating documentation to reflect these mods.

**Comment by WenMeng-NOAA** [comment]
With this PR merging, I will update the UPP build procedure on WCOSS-Dell, WCOSS-Cray, Hera, Jet and Orion.

**Comment by WenMeng-NOAA** [comment]
@fossell and @hertneky Thanks for documenting UPP updates.

**Pull request merged**
