### PR TITLE
Update g2tmpl to 1.10.2 and crtm to 2.4.0

### LINKED ISSUE #365: Transition UPP to use CRTM v2.4 for RRFS implementation
Per email exchange with Daryl, DA group is planning to use CRTM V2.4 for RRFS implementation.

Haixia added the following lines to DA CRTM interface to adjust to CRTM V2.4 and recommended UPP does the same:

------------------------------------------------------------------------------------------------------
do ii=1,n_clouds_fwd_wk
           if(cloud_cont(k,ii) > 1.001_r_kind*1.0E-6_r_kind .and. atmosphere(1)%cloud_fraction(k) < 1.001_r_kind*1.0E-12_r_kind) then
                   atmosphere(1)%cloud_fraction(k)=1.001_r_kind*1.0E-12_r_kind
                 end if
              end do
-----------------------------------------------------------------------------------------------------------------

Per Emily: In CRTM 2.3.0.  Users do not have to provide cloud fraction profiles from the model for cloudy radiance calculation.  It is assumed overcast if cloud fraction is not provided.  In CRTM 2.4.0, the cloud fraction profile is required for cloudy radiance calculation

### LINKED ISSUE #553: Update g2tmpl and crtm modules
- Update g2tmpl to 1.10.2 and crtm to 2.4.0 in UPP develop branch.
- Add changes in CALRAD_WCLOUD_newcrtm.f for crtm/2.4.0
- Add abi_g17 and abi_g17 fix files in GFS post processing runtime

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
- Update g2tmpl to 1.10.2 
- Update crtm to 2.4.0
- Update CALRAD_WCLOUD_newcrtm.f for crtm/2.4.0
- Add abi_g17 and abi_g17 fix files for GFS post processing runtime
- Clean out legacy modulefiles for WCOSS1 
- Add changes for supporting WCOSS2 Acorn

** g2tmpl/1.10.0 is kept on WCOSS2 since new g2tmpl/1.10.2 is not installed yet.

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@WenMeng-NOAA The changes look good to me, I have a model branch with 2.4.0 crtm and 1.10.2 getmpl, I will update UPP after your merge this PR. Thanks

**Review by junwang-noaa — APPROVED** [review]

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA looks good to me!  Thanks for working on this.

**Review by EricJames-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were conducted on WCOSS2, Hera and Orion. The following applications have baseline changes due to crtm upgrading to 2.4.0:
**gfs**:
```
 [Wen.Meng@hfe11 ~/stmp2]$ cat gfs.20210216/gfs.t00z.special.grb2f006.diff
1:0:SBTAGR8:top of atmosphere:rpn_corr=0.999588:rpn_rms=0.21773
2:3722154:SBTAGR9:top of atmosphere:rpn_corr=0.999226:rpn_rms=0.365885
3:7680361:SBTAGR10:top of atmosphere:rpn_corr=0.998426:rpn_rms=0.664747
4:12058131:SBTAGR13:top of atmosphere:rpn_corr=0.994172:rpn_rms=2.47778
```

**hrrr**:
```
[wmeng@Orion-login-1 stmp2]$ cat  hrrr_2020060118_pe_test/WRFTWO.GrbF04.diff
170:156460822:SBT123:top of atmosphere:rpn_corr=0.987814:rpn_rms=1.25053
171:158195865:SBT124:top of atmosphere:rpn_corr=0.95635:rpn_rms=7.62271
172:160086041:SBT113:top of atmosphere:rpn_corr=0.990112:rpn_rms=1.00625
173:161695699:SBT114:top of atmosphere:rpn_corr=0.957025:rpn_rms=7.86386
```

**rap**:
```
[wmeng@Orion-login-1 stmp2]$ cat rap_2020072316/WRFPRS.GrbF16.diff
708:195500241:CDCON:convective cloud layer:rpn_corr=-nan:rpn_rms=undefined
792:236708673:SBT123:top of atmosphere:rpn_corr=0.993439:rpn_rms=0.928474
793:237046537:SBT124:top of atmosphere:rpn_corr=0.946821:rpn_rms=7.01317
794:237539672:SBT113:top of atmosphere:rpn_corr=0.997083:rpn_rms=0.671609
795:237863721:SBT114:top of atmosphere:rpn_corr=0.952295:rpn_rms=7.17395
```

**rtma**:
```
[wmeng@Orion-login-1 stmp2]$ cat rtma_2020113000/WRFTWO.GrbF00.diff
167:133798324:SBT123:top of atmosphere:rpn_corr=0.993921:rpn_rms=0.738551
168:135296151:SBT124:top of atmosphere:rpn_corr=0.937889:rpn_rms=5.6218
169:137649142:SBT113:top of atmosphere:rpn_corr=0.998084:rpn_rms=0.494176
170:139019982:SBT114:top of atmosphere:rpn_corr=0.94023:rpn_rms=5.94619
```

With g2tmpl upgraded to 1.10.2, the new forecast generating process id 135 (hafs) for HAFS implementation can be processed.
```
[Wen.Meng@hfe11 fv3hafs_2021082706]$ wgrib2 HURPRS09.tm00 -processid
685:895810733:background generating process=0 forecast generating process=135
686:895818088:background generating process=0 forecast generating process=135
687:896401828:background generating process=0 forecast generating process=135
688:896727778:background generating process=0 forecast generating process=135
```

**Comment by WenMeng-NOAA** [comment]
The baselines for GFS, HAFS, RAP/HRRR and RTMA will be updated with this PR committed.

**Pull request merged**
