### PR TITLE
Update UPP modulefile on S4 with spack-stack 1.5.0

### LINKED ISSUE #831: Update modulefile on s4 with spack-stack-1.5.0
@souopgui Can you open an UPP issue to link this PR?

_Originally posted by @WenMeng-NOAA in https://github.com/NOAA-EMC/UPP/issues/828#issuecomment-1834384020_

### PR DESCRIPTION
**Pull request by souopgui**
- Rename s4 modulefiles to s4.lua on S4
- Update s4.lua with spack-stack on S4

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
Hello @souopgui, with the switch to spack-stack 1.5.0, UPP has restructured its .lua module files to resemble the ufs weather model more closely. The upp_common.lua file should now include most of those load commands and versions within your S4 .lua, meaning you can remove the duplicate loads and instead `load("upp_common")` similar to the hera, hercules, and orion modulefiles. Typically only the stack-intel, stack-intel-oneapi-mpi, and cmake loads remain within the .lua modulefiles.

This would make it a bit easier to manage and read, if you could introduce those changes into your s4.lua. Thank you.

**Comment by souopgui** [comment]
> Hello @souopgui, with the switch to spack-stack 1.5.0, UPP has restructured its .lua module files to resemble the ufs weather model more closely. The upp_common.lua file should now include most of those load commands and versions within your S4 .lua, meaning you can remove the duplicate loads and instead `load("upp_common")` similar to the hera, hercules, and orion modulefiles. Typically only the stack-intel, stack-intel-oneapi-mpi, and cmake loads remain within the .lua modulefiles.
> 
> This would make it a bit easier to manage and read, if you could introduce those changes into your s4.lua. Thank you.

Done.

**Comment by WenMeng-NOAA** [comment]
@souopgui Can you open an UPP issue to link this PR?

**Comment by WenMeng-NOAA** [comment]
The build test on WCOSS2 was completed.

**Comment by FernandoAndrade-NOAA** [comment]
> The build test on WCOSS2 was completed.

There was a delay due to an unexpected issue with cloning, running RTs on Hera and Orion now.

**Comment by WenMeng-NOAA** [comment]
> > The build test on WCOSS2 was completed.
> 
> There was a delay due to an unexpected issue with cloning, running RTs on Hera and Orion now.

@FernandoAndrade-NOAA No need for running the whole UPP RT since the update of the modulefile on s4 should have no impact on the UPP build on WCOSS2, Hera and Orion. You might have the same build test either Hera and Orion as mine on WCOSS2:
```
cd UPP/tests
./compile_upp.sh
```

**Comment by FernandoAndrade-NOAA** [comment]
> > > The build test on WCOSS2 was completed.
> > 
> > 
> > There was a delay due to an unexpected issue with cloning, running RTs on Hera and Orion now.
> 
> @FernandoAndrade-NOAA No need for running the whole UPP RT since the update of the modulefile on s4 should have no impact on the UPP build on WCOSS2, Hera and Orion. You might have the same build test either Hera and Orion as mine on WCOSS2:
> 
> ```
> cd UPP/tests
> ./compile_upp.sh
> ```

I was unsure if that was sufficient, thanks for the heads up! In that case hera, hercules and orion built successfully

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
