### PR TITLE
3DRTMA specific change

### LINKED ISSUE #173: 3DRTMA specific change
The output of 10m wind from UPP is a direct copy of the 10m wind fields in a given WRF NetCDF file. The GSI analysis does not update the 10m wind field. So using current UPP for 3DRTMA will output background 10m wind, which is not desirable. This update added a 'SUBMODELNAME="RTMA" ' logic so that UPP will update 10m wind using the wind fields at lowest HRRR model level (z=8m). It does not affect other UPP functions. #172

### PR DESCRIPTION
**Pull request by guoqing-noaa**
Changes on the INITPOST.F to add a logic to update 10m wind for 3DRTMA

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@guoqing-noaa Can you follow the procedure at https://github.com/NOAA-EMC/EMC_post/wiki/UPP-Code-Development#update-your-branch-at-your-fork-with-branch-develop-at-original-repository to sync your branch with the latest commits from the upstream branch develop? Thanks!

**Comment by guoqing-noaa** [comment]
@WenMeng-NOAA Thanks. Just merged latest changes from the "develop" branch of NOAA-EMC/EMC_post

**Comment by WenMeng-NOAA** [comment]
#173

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were conducted on Dell, Cray and Hera. No changed results were found. This PR is ready for merging.

**Pull request merged**
