### PR TITLE
Add html files for documentation generated in PR #965

### PR DESCRIPTION
**Pull request by gspetro-NOAA**
This PR adds the updated HTMLs for files updated in PR #965 to the gh-pages branch. Since gh-pages is a special branch w/o source code, the checks are expected to fail, and this does not indicate an error.

- This PR continues work to resolve Issue #392 . 
- It will also resolve Issue #569 and #391. 

Although there are 715 files changed in this PR, almost all changes relate to metadata or file format (e.g., PNGs are now SVGs). The only content-related changes come from PR #965. Documentation has been regenerated from scratch (rather than just adding select files), since over time, differences in metadata have led to issues like #569 , where certain pages and links don't render properly. By regenerating the HTMLs in full, any incompatibilities should be resolved. 

The Doxygen documentation with these updates can be viewed on the Doxygen page for my UPP fork: https://gspetro-noaa.github.io/UPP/.

### CODE REVIEW

**Comment by gspetro-NOAA** [comment]
@fossell @edwardhartnett -- Wen was wondering if either of you were available to review this gh-pages PR. It looks big but is mostly metadata changes from regenerating the docs with new Doxygen version. Hoping to automate the process soon, but in the meantime, it still needs a manual review.

**Comment by edwardhartnett** [comment]
Generally I don't use a PR to update the gh-pages branch, nor does it call for a review.

There is no code, only documentation output. Put it on the gh-pages branch from the command line, and inspect the result on the web.

**Comment by gspetro-NOAA** [comment]
@edwardhartnett Sounds reasonable! This process was inherited from our DTC counterparts, but it sounds like perhaps we should revise it. Will discuss with the CMs.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA Merging this PR. RTs will not be necessary for this update.

**Pull request merged**
