### PR TITLE
Update grib2 table files with the new release g2tmpl

### LINKED ISSUE #879: Update UPP with the new release g2tmpl
Update grib2 table files 'params_grib2_tbl_new' and 'params_grib2_tbl_new.text' in UPP with the new release g2tmpl.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Update the grib2 table files with the new release g2tmpl.

### CODE REVIEW

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
@WenMeng-NOAA these all look fine.

**Review by AndrewBenjamin-NOAA — APPROVED** [review]
@WenMeng-NOAA These all look good to me

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my test results on Hera are at 
```
[Wen.Meng@hfe04 ~/stmp2]$ pwd
/scratch1/NCEPDEV/stmp2/Wen.Meng
[Wen.Meng@hfe04 ~/stmp2]$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:14 post_nmmb_meso_2014120818_Grib2_pe_test/BGDAWP03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp    75 Mar  6 14:14 rap_2020072316/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:14 post_nmmb_meso_2014120818_Grib2/BGDAWP03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp    75 Mar  6 14:14 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 post_nmmb_meso_2014120818_Grib2_pe_test/BGRD3D03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 hrrr_2020060118/WRFTWO.GrbF04.diff
-rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 post_nmmb_meso_2014120818_Grib2/BGRD3D03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 hrrr_2020060118_pe_test/WRFTWO.GrbF04.diff
-rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 post_nmmb_meso_2014120818_Grib2_pe_test/BGRDSF03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 post_nmmb_meso_2014120818_Grib2/BGRDSF03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp  1951 Mar  6 14:16 fv3r_2023062800/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  1951 Mar  6 14:16 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14748 Mar  6 14:16 rtma_2023040400_pe_test/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14748 Mar  6 14:16 rtma_2023040400/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14594 Mar  6 14:18 fv3r_2023062800/NATLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  2516 Mar  6 14:18 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  2516 Mar  6 14:18 rtma_2023040400/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14594 Mar  6 14:19 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
```
There should be changes in field values and variable names. The grib2 table update might impact on grib2 metadata part.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2. The baselines for nmmb, rap, hrrr, fv3r and 3drtma will be recreated with this PR.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my test results on Hera are at
> 
> ```
> [Wen.Meng@hfe04 ~/stmp2]$ pwd
> /scratch1/NCEPDEV/stmp2/Wen.Meng
> [Wen.Meng@hfe04 ~/stmp2]$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:14 post_nmmb_meso_2014120818_Grib2_pe_test/BGDAWP03.tm00.Grib2.diff
> -rw-r--r-- 1 Wen.Meng stmp    75 Mar  6 14:14 rap_2020072316/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:14 post_nmmb_meso_2014120818_Grib2/BGDAWP03.tm00.Grib2.diff
> -rw-r--r-- 1 Wen.Meng stmp    75 Mar  6 14:14 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 post_nmmb_meso_2014120818_Grib2_pe_test/BGRD3D03.tm00.Grib2.diff
> -rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 hrrr_2020060118/WRFTWO.GrbF04.diff
> -rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 post_nmmb_meso_2014120818_Grib2/BGRD3D03.tm00.Grib2.diff
> -rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 hrrr_2020060118_pe_test/WRFTWO.GrbF04.diff
> -rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 post_nmmb_meso_2014120818_Grib2_pe_test/BGRDSF03.tm00.Grib2.diff
> -rw-r--r-- 1 Wen.Meng stmp     0 Mar  6 14:15 post_nmmb_meso_2014120818_Grib2/BGRDSF03.tm00.Grib2.diff
> -rw-r--r-- 1 Wen.Meng stmp  1951 Mar  6 14:16 fv3r_2023062800/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  1951 Mar  6 14:16 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14748 Mar  6 14:16 rtma_2023040400_pe_test/NATLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14748 Mar  6 14:16 rtma_2023040400/NATLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14594 Mar  6 14:18 fv3r_2023062800/NATLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  2516 Mar  6 14:18 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  2516 Mar  6 14:18 rtma_2023040400/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14594 Mar  6 14:19 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
> ```
> 
> There should be changes in field values and variable names. The grib2 table update might impact on grib2 metadata part.

RTs have completed on Hera, Hercules, and Orion. Changes match with your results

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
