### PR TITLE
Add modulefiles for Hercules

### LINKED ISSUE #753: Add modulefiles for Hercules
A new modulefiles is needed for porting UPP on new R&D platform Hercules.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Add a new modulefiles to port UPP on Hercules.

### CODE REVIEW

**Review by BijuThomas-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the RT on Hera. There will be no changed results with this PR.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the RT on Hera. There will be no changed results with this PR.

I'm not sure this PR is ready. A hercules.lua file should be included in addition to the detect_machine changes right?

**Comment by WenMeng-NOAA** [comment]
> > @FernandoAndrade-NOAA You may start the RT on Hera. There will be no changed results with this PR.
> 
> I'm not sure this PR is ready. A hercules.lua file should be included in addition to the detect_machine changes right?

@FernandoAndrade-NOAA Thanks for catching this. Forgot to commit it to github. Please try it.

**Comment by FernandoAndrade-NOAA** [comment]
UPP RTs have finished on Hera with no changes to results.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
This would be closing out #719 as well?

**Comment by WenMeng-NOAA** [comment]
> This would be closing out #719 as well?

yes.

**Comment by WenMeng-NOAA** [comment]
The UPP standalone test with  hafs model files was successfully completed on Hercules.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
