### PR TITLE
Update documentation for MSFPS.f, NGMFLD.f, OTLFT.f, OTLIFT.f, and ZENSUN.f

### PR DESCRIPTION
**Pull request by gspetro-NOAA**
This PR updates MSFPS.f, NGMFLD.f, OTLFT.f, OTLIFT.f (which require documentation of each subroutine even when the same information appears in the file description above), and ZENSUN.f (which needed a definition for the variable pi). 

This PR partially addresses Issue https://github.com/NOAA-EMC/UPP/issues/392 .

### CODE REVIEW

**Review by fossell — APPROVED** [review]
These changes are to doxygen comments/synax and look good to me.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Could you conduct the UPP RT test on either Hera or Orion? Since this PR is for documentation updating, one platform testing should be fine.

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA UPP RT tests completed on Hera with no change to results.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
