### PR TITLE
Bug fix for QPFFFG and QPFARI encoding in RRFS

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
prob_num and tot_num_prob were not set in grib2_module.f, resulting in seemingly random values showing up for the new GRIB2 records QPFARI and QPFFFG, as noted by Hui-Ya Chuang:

< 772:4824832913:vt=2024022023:surface:11-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat
=1 parm=197:prob >1:prob fcst 72/110
---
> 772:4824832913:vt=2024022023:surface:11-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat
=1 parm=197:prob >1:prob fcst 96/110
6177c6177
< 773:4824833141:vt=2024022023:surface:0-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat=
1 parm=197:prob >1:prob fcst 72/110
---
> 773:4824833141:vt=2024022023:surface:0-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat=
1 parm=197:prob >1:prob fcst 96/110

This small change fixes the issue, and should lead to bitwise identical results.

The change was tested for the RRFS_NA_3km system on Hera.

### CODE REVIEW

**Comment by HuiyaChuang-NOAA** [comment]
@EricJames-NOAA @MatthewPyle-NOAA 
Wen won't be back for another week or two from China.  She gave me directions to merge UPP codes and Fernando will help me.
I will be gone for 3 weeks after this weekend so let me know soon.

Huiya

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA @MatthewPyle-NOAA Wen won't be back for another week or two from China. She gave me directions to merge UPP codes and Fernando will help me. I will be gone for 3 weeks after this weekend so let me know soon.
> 
> Huiya

@HuiyaChuang-NOAA thanks for the update.  I am working on one additional bug fix which I intend to combine with this PR.  I hope to have the code ready to go tomorrow.  Once that is finished, the code should be finalized for RRFS.

**Comment by HuiyaChuang-NOAA** [comment]
> > @EricJames-NOAA @MatthewPyle-NOAA Wen won't be back for another week or two from China. She gave me directions to merge UPP codes and Fernando will help me. I will be gone for 3 weeks after this weekend so let me know soon.
> > Huiya
> 
> @HuiyaChuang-NOAA thanks for the update. I am working on one additional bug fix which I intend to combine with this PR. I hope to have the code ready to go tomorrow. Once that is finished, the code should be finalized for RRFS.

Ok, let me know.  I will see what I can do.  If I can't get to it, I will email Wen with you copied .  She is hoping to be back to work the week of June 10

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks good from my perspective.

**Comment by EricJames-NOAA** [comment]
> > > @EricJames-NOAA @MatthewPyle-NOAA Wen won't be back for another week or two from China. She gave me directions to merge UPP codes and Fernando will help me. I will be gone for 3 weeks after this weekend so let me know soon.
> > > Huiya
> > 
> > 
> > @HuiyaChuang-NOAA thanks for the update. I am working on one additional bug fix which I intend to combine with this PR. I hope to have the code ready to go tomorrow. Once that is finished, the code should be finalized for RRFS.
> 
> Ok, let me know. I will see what I can do. If I can't get to it, I will email Wen with you copied . She is hoping to be back to work the week of June 10



> > > @EricJames-NOAA @MatthewPyle-NOAA Wen won't be back for another week or two from China. She gave me directions to merge UPP codes and Fernando will help me. I will be gone for 3 weeks after this weekend so let me know soon.
> > > Huiya
> > 
> > 
> > @HuiyaChuang-NOAA thanks for the update. I am working on one additional bug fix which I intend to combine with this PR. I hope to have the code ready to go tomorrow. Once that is finished, the code should be finalized for RRFS.
> 
> Ok, let me know. I will see what I can do. If I can't get to it, I will email Wen with you copied . She is hoping to be back to work the week of June 10

@HuiyaChuang-NOAA @MatthewPyle-NOAA the PR is ready.  The only remaining issue is that accumulated fields in the top-of-the-hour 15-min output appear with units of hours instead of minutes, and I can't figure out why that's the case.  But the time labels are all correct now.  

Sorry it is so late.  If you can't get it merged now, I will spend some more time trying to figure out the time unit labeling issue.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA I assume all of these bug fixes are intended for RRFS v1 implementation, right? If so, please change the merging branch from 'develop' to 'release/rrfs_v1'.  Also, another UPP issue is needed for bug fixes except QPFFG and QPFARI encoding.

**Pull request closed without merging**
