### PR TITLE
Update grib2 tables with g2tmpl v1.10.2 and change soil moisture grib2 name

### LINKED ISSUE #853: Update grib2 tables in UPP with g2tmpl v1.10.2
The grib2 tables 'params_grib2_tbl_new' and 'params_grib2_tbl_new.text' under UPP/parm need to be updated with g2tmpl v1.10.2.

### LINKED ISSUE #854: Update grib2 name for soil moisture
The UPP defines soil moisture as the name 'SOILM'. This name was deprecated with g2tmpl v1.10.2 implementation.  See grib2 table [4.2-2-0](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-2-0.shtml) number 3 and 22. The new grib2 name for replacement is 'SOILMOI' from grib2 table [4-2-2-3](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-2-3.shtml).

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main changes are:

- Update grib2 tables in UPP with g2tmpl v1.10.2
- Change soil moisture grib2 name from 'SOILM' into 'SOILMOI'

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may conduct the UPP RTs on Hera and Orion. There are no variable value changes except grib2 meta data update. For your reference, here are my test results on Hera at /scratch1/NCEPDEV/stmp2/Wen.Meng:
'''
[Wen.Meng@hfe06 ~/stmp2]$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp   0 Jan 16 22:22 post_nmmb_meso_2014120818_Grib2/BGDAWP03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp   0 Jan 16 22:22 post_nmmb_meso_2014120818_Grib2/BGRD3D03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp   0 Jan 16 22:22 post_nmmb_meso_2014120818_Grib2/BGRDSF03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp  75 Jan 16 22:25 rap_2020072316/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp   0 Jan 16 22:28 post_nmmb_meso_2014120818_Grib2_pe_test/BGDAWP03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp  75 Jan 16 22:28 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp   0 Jan 16 22:28 post_nmmb_meso_2014120818_Grib2_pe_test/BGRD3D03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp   0 Jan 16 22:28 post_nmmb_meso_2014120818_Grib2_pe_test/BGRDSF03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp 417 Jan 16 22:33 gfs.20190830/gfs.t00z.sfluxgrbf006.grib2.diff
-rw-r--r-- 1 Wen.Meng stmp 417 Jan 16 22:34 gfs.20190830_pe_test/gfs.t00z.sfluxgrbf006.grib2.diff
'''

**Review by HuiyaChuang-NOAA — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
It seems that Jenkins is still sitting in queue, I will run manually to see if that ends up being a bit faster on Orion and Hera.

**Comment by WenMeng-NOAA** [comment]
The grib2 name of soil moisture in gfs flux dataset is updated 
From
   21:45715792:d=2019083000:SOIL_M:0-2 m below ground:6 hour fcst:
into
  21:45715792:d=2019083000:SOILMOI:0-2 m below ground:6 hour fcst:

**Comment by FernandoAndrade-NOAA** [comment]
Those failures are not fully matching with all the expected changes, I believe Jenkins timed out. The manual runs are still in queue on both systems, apologies for the delayed queues I'll check in tomorrow to see where we are with increased epic allocation.

**Comment by WenMeng-NOAA** [comment]
The UPP RT was completed on WCOSS2. There will be baseline recreations for gfs, nmmb, rap with this PR.

**Comment by FernandoAndrade-NOAA** [comment]
Rerunning Hera manually with a different account, the test results look incomplete. Orion RTs will be rerun with windfall as it also didn't fully finish RTs. EPIC is still following up about receiving increased allocation for the accounts to minimize this sort of issue.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may conduct the UPP RTs on Hera and Orion. There are no variable value changes except grib2 meta data update. For your reference, here are my test results on Hera at /scratch1/NCEPDEV/stmp2/Wen.Meng: ''' [Wen.Meng@hfe06 ~/stmp2]$ ls -ltr */*diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:22 post_nmmb_meso_2014120818_Grib2/BGDAWP03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:22 post_nmmb_meso_2014120818_Grib2/BGRD3D03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:22 post_nmmb_meso_2014120818_Grib2/BGRDSF03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 75 Jan 16 22:25 rap_2020072316/WRFPRS.GrbF16.diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:28 post_nmmb_meso_2014120818_Grib2_pe_test/BGDAWP03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 75 Jan 16 22:28 rap_2020072316_pe_test/WRFPRS.GrbF16.diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:28 post_nmmb_meso_2014120818_Grib2_pe_test/BGRD3D03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:28 post_nmmb_meso_2014120818_Grib2_pe_test/BGRDSF03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 417 Jan 16 22:33 gfs.20190830/gfs.t00z.sfluxgrbf006.grib2.diff -rw-r--r-- 1 Wen.Meng stmp 417 Jan 16 22:34 gfs.20190830_pe_test/gfs.t00z.sfluxgrbf006.grib2.diff '''

I see similar changes in my results on Hera and Orion, along with the change in gfs sflux file. I did notice a difference in the .diff output between hera and orion. Just something to be aware of:
Hera:
```
33:65050514:LANDFRC:surface:rpn_corr=-nan:rpn_rms=undefined
34:65640517:PAHFLX:surface:rpn_corr=-nan:rpn_rms=undefined
35:66230520:WATERSA:surface:rpn_corr=-nan:rpn_rms=undefined
36:66820523:EIWATER:surface:rpn_corr=-nan:rpn_rms=undefined
37:67410550:PLANTTR:surface:rpn_corr=-nan:rpn_rms=undefined
38:68000577:SOILSE:surface:rpn_corr=-nan:rpn_rms=undefined
39:68590604:PAHFLX:surface:rpn_corr=-nan:rpn_rms=undefined
```

Orion:
```
33:65050514:var discipline=2 center=7 local_table=1 parmcat=0 parm=233:surface:rpn_corr=-nan:rpn_rms=undefined
34:65640517:var discipline=2 center=7 local_table=1 parmcat=0 parm=235:surface:rpn_corr=-nan:rpn_rms=undefined
35:66230520:var discipline=2 center=7 local_table=1 parmcat=0 parm=236:surface:rpn_corr=-nan:rpn_rms=undefined
36:66820523:var discipline=2 center=7 local_table=1 parmcat=0 parm=237:surface:rpn_corr=-nan:rpn_rms=undefined
37:67410550:var discipline=2 center=7 local_table=1 parmcat=0 parm=238:surface:rpn_corr=-nan:rpn_rms=undefined
38:68000577:var discipline=2 center=7 local_table=1 parmcat=0 parm=239:surface:rpn_corr=-nan:rpn_rms=undefined
39:68590604:var discipline=2 center=7 local_table=1 parmcat=0 parm=235:surface:rpn_corr=-nan:rpn_rms=undefined
```

**Comment by WenMeng-NOAA** [comment]
> > @FernandoAndrade-NOAA You may conduct the UPP RTs on Hera and Orion. There are no variable value changes except grib2 meta data update. For your reference, here are my test results on Hera at /scratch1/NCEPDEV/stmp2/Wen.Meng: ''' [Wen.Meng@hfe06 ~/stmp2]$ ls -ltr */*diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:22 post_nmmb_meso_2014120818_Grib2/BGDAWP03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:22 post_nmmb_meso_2014120818_Grib2/BGRD3D03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:22 post_nmmb_meso_2014120818_Grib2/BGRDSF03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 75 Jan 16 22:25 rap_2020072316/WRFPRS.GrbF16.diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:28 post_nmmb_meso_2014120818_Grib2_pe_test/BGDAWP03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 75 Jan 16 22:28 rap_2020072316_pe_test/WRFPRS.GrbF16.diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:28 post_nmmb_meso_2014120818_Grib2_pe_test/BGRD3D03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 0 Jan 16 22:28 post_nmmb_meso_2014120818_Grib2_pe_test/BGRDSF03.tm00.Grib2.diff -rw-r--r-- 1 Wen.Meng stmp 417 Jan 16 22:33 gfs.20190830/gfs.t00z.sfluxgrbf006.grib2.diff -rw-r--r-- 1 Wen.Meng stmp 417 Jan 16 22:34 gfs.20190830_pe_test/gfs.t00z.sfluxgrbf006.grib2.diff '''
> 
> I see similar changes in my results on Hera and Orion, along with the change in gfs sflux file. I did notice a difference in the .diff output between hera and orion. Just something to be aware of: Hera:
> 
> ```
> 33:65050514:LANDFRC:surface:rpn_corr=-nan:rpn_rms=undefined
> 34:65640517:PAHFLX:surface:rpn_corr=-nan:rpn_rms=undefined
> 35:66230520:WATERSA:surface:rpn_corr=-nan:rpn_rms=undefined
> 36:66820523:EIWATER:surface:rpn_corr=-nan:rpn_rms=undefined
> 37:67410550:PLANTTR:surface:rpn_corr=-nan:rpn_rms=undefined
> 38:68000577:SOILSE:surface:rpn_corr=-nan:rpn_rms=undefined
> 39:68590604:PAHFLX:surface:rpn_corr=-nan:rpn_rms=undefined
> ```
> 
> Orion:
> 
> ```
> 33:65050514:var discipline=2 center=7 local_table=1 parmcat=0 parm=233:surface:rpn_corr=-nan:rpn_rms=undefined
> 34:65640517:var discipline=2 center=7 local_table=1 parmcat=0 parm=235:surface:rpn_corr=-nan:rpn_rms=undefined
> 35:66230520:var discipline=2 center=7 local_table=1 parmcat=0 parm=236:surface:rpn_corr=-nan:rpn_rms=undefined
> 36:66820523:var discipline=2 center=7 local_table=1 parmcat=0 parm=237:surface:rpn_corr=-nan:rpn_rms=undefined
> 37:67410550:var discipline=2 center=7 local_table=1 parmcat=0 parm=238:surface:rpn_corr=-nan:rpn_rms=undefined
> 38:68000577:var discipline=2 center=7 local_table=1 parmcat=0 parm=239:surface:rpn_corr=-nan:rpn_rms=undefined
> 39:68590604:var discipline=2 center=7 local_table=1 parmcat=0 parm=235:surface:rpn_corr=-nan:rpn_rms=undefined
> ```

The lower version of wgrib2 on Orion does not include the upgraded NCEP local table. From grib2 tables online, 'discipline=2 center=7 local_table=1 parmcat=0 parm=233' and 'LANDFRC' are the same, see
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-2-0.shtml

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may go ahead to approve this PR. Thanks!

**Comment by FernandoAndrade-NOAA** [comment]
Thanks for explaining! And thank you for your patience regarding the account difficulties.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAAThe PR was merged.  You may update the baselines of the UPP RT on Hera and Orion. Thanks!

**Pull request merged**
