### PR TITLE
Enable output of VEGMIN/VEGMAX

### LINKED ISSUE #1022: VEGMIN/VEGMAX needed for MPAS initialization from RRFS
In order to initialize vegetation greenness fraction in MPAS when using RRFS initial conditions, we need to have VEGMIN and VEGMAX output in RRFS GRIB2 files.  These are the seasonal min and max vegetation greenness fraction (shdmin and shdmax in netCDF history files).

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
Initializing MPAS off the FV3 RRFS requires output of VEGMAX and VEGMIN, which are the seasonal max/min green vegetation fraction.  This enables us to initialize the realtime greenness vegetation fraction from RRFS in MPAS.  

The code was tested for the RRFS 3km North America system on Hera, with no change to any output except the addition of these two new fields in NATLEV file.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA I conducted the UPP standalone test for RRFS with RRFS NA model output and saw two new fields in dataset  NATLEV as:
```
Wen.Meng@hfe06 rrfs_2022022412-after$ wgrib2 NATLEV10.tm00 -match VEGM
1433:7525413030:d=2022022412:VEGMIN:surface:10 hour fcst:
1434:7529670117:d=2022022412:VEGMAX:surface:10 hour fcst:
```
You may access my test at /home/Wen.Meng/stmp2/rrfs_2022022412-after on Hera. Please validate and let me know if you see any issues.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on R&D machines. This PR will have baseline recreation for fv3r and 3drtma tests. For your reference, my testing is at /home/Wen.Meng/stmp2/UPP-RTs on Hera:
```
Wen.Meng@hfe06 UPP-RTs$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp    75 Aug 21 01:10 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp 26701 Aug 21 01:12 rtma_2023040400_pe_test/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 26701 Aug 21 01:13 rtma_2023040400/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 26434 Aug 21 01:13 fv3r_2023062800/NATLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 26434 Aug 21 01:13 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
```

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA This PR has been aimed at the "release/rrfs_v1" branch. There is no need for the UPP RTs. Sorry for the misleading comments.

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA I conducted the UPP standalone test for RRFS with RRFS NA model output and saw two new fields in dataset NATLEV as:
> 
> ```
> Wen.Meng@hfe06 rrfs_2022022412-after$ wgrib2 NATLEV10.tm00 -match VEGM
> 1433:7525413030:d=2022022412:VEGMIN:surface:10 hour fcst:
> 1434:7529670117:d=2022022412:VEGMAX:surface:10 hour fcst:
> ```
> 
> You may access my test at /home/Wen.Meng/stmp2/rrfs_2022022412-after on Hera. Please validate and let me know if you see any issues.

@WenMeng-NOAA your results look consistent with mine!  Thanks for the test.

**Comment by WenMeng-NOAA** [comment]
> > @EricJames-NOAA I conducted the UPP standalone test for RRFS with RRFS NA model output and saw two new fields in dataset NATLEV as:
> > ```
> > Wen.Meng@hfe06 rrfs_2022022412-after$ wgrib2 NATLEV10.tm00 -match VEGM
> > 1433:7525413030:d=2022022412:VEGMIN:surface:10 hour fcst:
> > 1434:7529670117:d=2022022412:VEGMAX:surface:10 hour fcst:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You may access my test at /home/Wen.Meng/stmp2/rrfs_2022022412-after on Hera. Please validate and let me know if you see any issues.
> 
> @WenMeng-NOAA your results look consistent with mine! Thanks for the test.

@EricJames-NOAA Thanks for confirmation.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
