### PR TITLE
Remove 3 hybrid level variables from RRFS products.

### LINKED ISSUE #832: Fix CI Intel Tests
The failing Intel CI tests is because the newest version of the Intel compilers does not include `ifort`.  It has been replaced with `ifx`.  The short term fix is to use the last available version of Intel compilers that include `ifort` (2023.2.1).  See https://github.com/NOAA-EMC/GSI-utils/pull/19 for a recipe.  The longer term fix is to move to `ifx` and `icx`.

### LINKED ISSUE #835: Remove 3 variables from RRFS NATLEV files
Per request from @MatthewPyle-NOAA  to reduce the size of RRFS NATLEV files, Huiya organize a meeting with RRFS team from 
EMC and GSL to discuss this.  Three variables were identified to be potentially removed:

VVEL
PMTF
PMTC

@EricJames-NOAA confirmed with GSL AQ group that it is ok to remove PMTF and PMTC.  
@HuiyaChuang-NOAA mentioned VVEL was derived in UPP using **hydrostatic equation** to support customers who could 
not transition to model derived **non-hydrostatic W** at GFS v15 when EMC transitioned to FV3.  However, VVEL
does not accurately represent  non hydrostatic vertical motion in the model.

Meeting summary and action items from this meeting can be found in this google doc:
https://docs.google.com/document/d/1REmrrPBQRIa2ZPjuP1tBJ8qtqETedEy2l0pC0wOzPKc/edit

@WenMeng-NOAA has graciously agreed to work on this PR.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main changes are:

- Remove 3 hybrid level variables from RRFS products
- Add fix for CI failure

### CODE REVIEW

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks good to me.   Thanks @WenMeng-NOAA!

**Review by DavidHuber-NOAA — APPROVED** [review]
Looks good!

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 and Hera. The number of grib2 records in NATLEV dataset in fv3r and 3drtma tests will be changed from 1762 to 1567.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RT on R&D platform. My UPP RT is available at /scratch1/NCEPDEV/stmp2/Wen.Meng.

**Review by HuiyaChuang-NOAA — APPROVED** [review]
Thanks!

**Comment by FernandoAndrade-NOAA** [comment]
It looks like Hera is being held up within the Jenkins pipeline, I'm going to run Hera and Orion manually and see if that's a bit faster. @WenMeng-NOAA FYI I have seen Hera jobs take quite a bit longer recently on the weather model side of testing as well, this seems to be more of a system issue.

Hercules also continues to result in fatal errors with rtma and gfs test cases, I'll continue to retry. I'll create an issue for tracking as well.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RT on R&D platform. My UPP RT is available at /scratch1/NCEPDEV/stmp2/Wen.Meng.

It looks like Hera is having some issues at the moment, the RT jobs are still sitting in queue, however the RT script has timed out after a rerun. Orion tests have finished if you'd like to confirm your test results are consistent with mine, I'm seeing the expected changes in the mentioned fields within NATLEV for fv3r and 3drtma

Orion: `/work2/noaa/epic/nandoam/regression-testing/upp/orion/836/UPP/ci/rundir/upp-ORION`

**Comment by WenMeng-NOAA** [comment]
> > @FernandoAndrade-NOAA You may start the UPP RT on R&D platform. My UPP RT is available at /scratch1/NCEPDEV/stmp2/Wen.Meng.
> 
> It looks like Hera is having some issues at the moment, the RT jobs are still sitting in queue, however the RT script has timed out after a rerun. Orion tests have finished if you'd like to confirm your test results are consistent with mine, I'm seeing the expected changes in the mentioned fields within NATLEV for fv3r and 3drtma
> 
> Orion: `/work2/noaa/epic/nandoam/regression-testing/upp/orion/836/UPP/ci/rundir/upp-ORION`

@FernandoAndrade-NOAA Your Orion testing looks good to me. Since I completed this Hera testing, we can merge this PR and you could solve the UPP RT issue at EPIC end on Hera later.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
