### PR TITLE
remove MAX_PRATE_ON_SURFACE, add ACM_ACPCP_ON_SURFACE for hafs_nosat

### LINKED ISSUE #603: update hafs control file for hafs_nosat
remove the MAX_PRATE_ON_SURFACE and add the ACM_ACPCP_ON_SURFACE for hafs_nosat control file,  postcntrl_hafs_nosat.xml, postxconfig-NT-hafs_nosat.txt

### LINKED ISSUE #606: Upgrade g2tmpl to 1.10.2 on WCOSS2
The g2tmpl/1.10.2 was recently installed on WCOSS2. The dependency module g2tmpl in develop branch needs to be upgraded to 1.10.2 on WCOSS2.

### PR DESCRIPTION
**Pull request by LinZhu-NOAA**
Remove the MAX_PRATE_ON_SURFACE and add the ACM_ACPCP_ON_SURFACE for hafs_nosat control file, 

Files changed:
parm/postcntrl_hafs_nosat.xml
parm/postxconfig-NT-hafs_nosat.txt

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@LinZhu-NOAA Would you mind to combing another small update in your PR? Please update modulefiles/wcoss2.lua as:
change
   g2tmpl_ver=os.getenv("g2tmpl_ver") or "1.10.0"
into
  g2tmpl_ver=os.getenv("g2tmpl_ver") or "1.10.2"

Thanks!

**Comment by LinZhu-NOAA** [comment]
@WenMeng-NOAA The modulefiles/wcoss2.lua is updated the g2tmpl_ver to 1.10.2.  Thanks!

**Comment by WenMeng-NOAA** [comment]
@LinZhu-NOAA Can you sync your branch with the latest changes from upstream/develop so I will process this PR? The procedure can be found at 
https://github.com/NOAA-EMC/UPP/wiki/UPP-Code-Development#update-your-branch-at-your-fork-with-branch-develop-at-authoritative-repository

**Comment by LinZhu-NOAA** [comment]
@WenMeng-NOAA The upp_crontrl branch is synced with the latest changes from upstream/develop following the instruction. Please let me know if there is any problems. Thanks!

**Comment by WenMeng-NOAA** [comment]
@LinZhu-NOAA The UPP standalone test case with model history files from you is at 
/u/wen.meng/ptmp/fv3hafs_2022092800 on Cactus
With g2tmpl upgraded to 1.10.2, you may expect hafs's generating process id (135) encoded in grib2 file as:
```
wen.meng@clogin02 fv3hafs_2022092800$ wgrib2 HURPRS09.tm00 -processid|tail
679:765265688:background generating process=0 forecast generating process=135
680:767413180:background generating process=0 forecast generating process=135
681:768834179:background generating process=0 forecast generating process=135
```
https://www.nco.ncep.noaa.gov/pmb/docs/on388/tablea.html
Please verify this hafs grib2 file and let me know if you see any discrepancy from your test.

**Comment by LinZhu-NOAA** [comment]
@WenMeng-NOAA /u/wen.meng/ptmp/fv3hafs_2022092800/HURPRS09.tm00 looks okay to me. Thanks!

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on WCOSS2, Hera and Orion. The baseline of hafs including in and out data will be created with this PR.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
