### PR TITLE
Compile on GAEA C5 partition

### LINKED ISSUE #784: Compile UPP on GAEA C5 partition
The Atmospheric River project must run UPP on the C5 platform on GAEA. A first step is to get it to compile.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
Adds logic to detect the `gaea_c5` platform, and compile there. This uses modulefiles from the same Spack Stack that EPIC is using for their global workflow C5 port.

Pinging @mark-a-potts so he's aware.

Fixes #784

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA Can you sync your branch with the latest commit from the UPP develop branch? We will process this PR soon.

**Comment by SamuelTrahanNOAA** [comment]
I merged develop to my branch a moment ago.

This UPP branch doesn't run on my test case on GAEA yet. I fear that may be due to an out-of-bounds write that just happens to fail on GAEA but not elsewhere. (I encountered that recently, when 32-bit physics support in CCPP crashed due to a UPP out-of-bounds write.) Debugging that may take another few days.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Can you test on building upp executable on GAEA?

**Comment by SamuelTrahanNOAA** [comment]
@FernandoAndrade-NOAA - You must test on GAEA C5. I did not implement a C4 build. That means you must ssh to login nodes gaea51 through gaea58

**Comment by SamuelTrahanNOAA** [comment]
I just added my GAEA C4 modulefile `modulefiles/gaea.lua`. It'll compile on C4, but I have no idea if it runs. My project only has resources on C5.

**Comment by FernandoAndrade-NOAA** [comment]
I can confirm I had no issues with compiling over in `/lustre/f2/scratch/Fernando.Andrade-maldonado/regression-test/upp/785/UPP` on Gaea51 (C5), I can go ahead and test C4 as well

**Comment by FernandoAndrade-NOAA** [comment]
Running compile.sh seems to have generated upp.x without issues on gaea10 (C4) as well under
`/lustre/f2/scratch/Fernando.Andrade-maldonado/regression-test/upp/785/c4-build/UPP/`

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 without changed results. The UPP executable testing was completed on Hera and Orion.

**Comment by WenMeng-NOAA** [comment]
> Running compile.sh seems to have generated upp.x without issues on gaea10 (C4) as well under `/lustre/f2/scratch/Fernando.Andrade-maldonado/regression-test/upp/785/c4-build/UPP/`

@FernandoAndrade-NOAA You may go ahead to approve this PR.

**Review by WenMeng-NOAA — APPROVED** [review]

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Pull request merged**
