### PR TITLE
Update CMakeLists.txt for renaming project name from UPP to upp.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]

**Comment by aerorahul** [comment]
approving, but needs to be tried with UFS.

**Review by junwang-noaa — APPROVED** [review]

**Comment by aerorahul** [comment]
After merge, can you please tag this as upp_v10.0.0?

**Comment by WenMeng-NOAA** [comment]
@aerorahul Will the tag as you prefer.

**Comment by WenMeng-NOAA** [comment]
@aerorahul The tag upp_v10.0.0 was created. Please let me know if you see issues. Thanks!

**Pull request merged**
