### PR TITLE
1)Add bug fix of radar reflecttivity from Jun Wang; 2)Remove the rout…

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
…ines for calling sigio module and gfsio module into from GFSPOST.F to GFSPOSTSIG.F.

I integrate the bug fix of radar reflectivity from Jun. From the UPP regression tests, there are following
results changed from SAR test as:
[Wen.Meng@hfe09 ~/stmp2]$ cat fv3r_2018101500_pe_test/BGDAWP04.tm00.Grib2.diff
43:64238612:REFZI:entire atmosphere (considered as a single layer):rpn_corr=0.967855:rpn_rms=2.96311
800:1007721774:REFZI:4000 m above ground:rpn_corr=0.987645:rpn_rms=0.982711
803:1010338976:REFZI:1000 m above ground:rpn_corr=0.992527:rpn_rms=0.549488

Please review code changes and let me know if you see issues. Thanks!

### CODE REVIEW

**Review by ericaligo-NOAA — COMMENTED** [review]
Lines 644-655.  If QQS > 0, but QQG =0, will DBZI bet set to 0 or does SPVAL take care of this.  We should make sure that if QQS is non zero, and QQG is zero, that DBZI is not reset to 0 because of line 654.
                 if(QQS(I,J,L) < SPVAL .and. QQS(I,J,L) > 0.0) then
                   DBZI(I,J,L) =  DBZI(I,J,L) + ((QQS(I,J,L)*DENS)**1.75) * &
     &                                        2.18500E-10 * 1.E18   ! Z FOR SNOW
                 IF (QQG(I,J,L) < SPVAL)                                    &
                 else
                   DBZI(I,J,L) = 0.
                 endif
                 IF (QQG(I,J,L) < SPVAL .and. QQG(I,J,L)> 0.0) then
                   DBZI(I,J,L) =  DBZI(I,J,L) + ((QQG(I,J,L)*DENS)**1.75) * &
     &                                          1.033267E-9 * 1.E18 ! Z FOR GRAUP
                 else
                   DBZI(I,J,L) = 0.
                 endif

**Review by junwang-noaa — COMMENTED** [review]
I see Eric's point. 
                 if(QQS(I,J,L) < SPVAL .and. QQS(I,J,L) > 0.0) then
                   DBZI(I,J,L) =  DBZI(I,J,L) + ((QQS(I,J,L)*DENS)**1.75) * &
     &                                        2.18500E-10 * 1.E18   ! Z FOR SNOW
                 else
                   DBZI(I,J,L) = 0.
                 endif
                 IF (QQG(I,J,L) < SPVAL .and. QQG(I,J,L)> 0.0) then
                   DBZI(I,J,L) =  DBZI(I,J,L) + ((QQG(I,J,L)*DENS)**1.75) * &
     &                                          1.033267E-9 * 1.E18 ! Z FOR GRAUP
                 else
                   DBZI(I,J,L) = 0.
                 endif

both lines of 
                  DBZI(I,J,L) = 0.
should be changed to:
                   DBZI(I,J,L) = DBZI(I,J,L)

Another point is that I remember we also have undefined value for convective precip, is the fix in this commit?

**Comment by WenMeng-NOAA** [comment]
Jun,
I updated the changes of cprate in global and regional FV3 read interfaces. Please review.
Thanks,

**Review by junwang-noaa — APPROVED** [review]
I see Eric's point. 
                 if(QQS(I,J,L) < SPVAL .and. QQS(I,J,L) > 0.0) then
                   DBZI(I,J,L) =  DBZI(I,J,L) + ((QQS(I,J,L)*DENS)**1.75) * &
     &                                        2.18500E-10 * 1.E18   ! Z FOR SNOW
                 else
                   DBZI(I,J,L) = 0.
                 endif
                 IF (QQG(I,J,L) < SPVAL .and. QQG(I,J,L)> 0.0) then
                   DBZI(I,J,L) =  DBZI(I,J,L) + ((QQG(I,J,L)*DENS)**1.75) * &
     &                                          1.033267E-9 * 1.E18 ! Z FOR GRAUP
                 else
                   DBZI(I,J,L) = 0.
                 endif

both lines of 
                  DBZI(I,J,L) = 0.
should be changed to:
                   DBZI(I,J,L) = DBZI(I,J,L)

Another point is that I remember we also have undefined value for convective precip, is the fix in this commit?

**Review by WenMeng-NOAA — COMMENTED** [review]
good

**Pull request merged**
