### PR TITLE
Add additional SFS variables and isobaric levels

### LINKED ISSUE #885: Add additional isobaric levels for SFS products
SFS developer from EMC requests adding additional isobaric levels up to 0.01 mb in the SFS products for their model evaluation.

### LINKED ISSUE #900: Add new SFS products for CPC
Per CPC's request, the following fields are added in the SFS product list:

- 0-3000m helicity
- total sky downward direct radiation at surface
- subsurface runoff

### PR DESCRIPTION
**Pull request by KarinaAsmar-NOAA**
* Add additional SFS isobaric levels [Issue #885 ](https://github.com/NOAA-EMC/UPP/issues/885)
* Add CPC requested variables HLCY, VBDSF, SSRUN [Issue #900 ](https://github.com/NOAA-EMC/UPP/issues/900)

* Test results with grib2 files are in:
Hera: /scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone
WCOSS2: /lfs/h2/emc/ptmp/karina.asmar/sfs_standalone

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA Please sync your branch with the latest UPP develop.

**Comment by KarinaAsmar-NOAA** [comment]
> @KarinaAsmar-NOAA Please sync your branch with the latest UPP develop.

@WenMeng-NOAA The branch is synced.

**Review by XiaqiongZhou-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2. No baseline update is needed with this PR.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA This PR is ready for the UPP RTs on Hera and Orion. There will be no baseline update for it.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA This PR is ready for the UPP RTs on Hera and Orion. There will be no baseline update for it.

UPP RTs have completed on Hera, Hercules, and Orion with no changes to results, looks good to go.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
