### PR TITLE
Update UPP for rocky8 transition on Hera and Jet

### LINKED ISSUE #889: Compile with Rocky 8 OS
The hera, jet, and orion HPC clusters are transitioning to the Rocky O.S.
Need to use spack-stack for Rocky 8 to compile the UPP. 

Please see this issue from ufs-srweather-model:
https://github.com/ufs-community/ufs-weather-model/issues/2167

Tested "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/modulefiles/Core"
The compilation works smoothly.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Update UPP for rocky8 transition on Hera and Jet.

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
Hi @WenMeng-NOAA, I had no changed results after making similar changes and running RTs/compile for Hera and Jet on Thursday/Friday. Would you like me to rerun for this PR when it's ready or would that pretesting be sufficient?

**Comment by WenMeng-NOAA** [comment]
> Hi @WenMeng-NOAA, I had no changed results after making similar changes and running RTs/compile for Hera and Jet on Thursday/Friday. Would you like me to rerun for this PR when it's ready or would that pretesting be sufficient?

@FernandoAndrade-NOAA Your pre-testing on Hera should be sufficient. Please let me know if you have more comments.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA The building (compiling) test on Jet was successful.

**Comment by FernandoAndrade-NOAA** [comment]
> > Hi @WenMeng-NOAA, I had no changed results after making similar changes and running RTs/compile for Hera and Jet on Thursday/Friday. Would you like me to rerun for this PR when it's ready or would that pretesting be sufficient?
> 
> @FernandoAndrade-NOAA Your pre-testing on Hera should be sufficient. Please let me know if you have more comments.

Sounds good, thanks! I'll go ahead and start up RTs on Orion and Hercules

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 without changed results.

**Review by DavidHuber-NOAA — COMMENTED** [review]
Will a lot of developers/users still be working on CentOS between now and April 2nd on Hera?  Would it make more sense to transition entirely to Rocky 8 so an additional PR is not required after the upgrade?

I'm not sure when Jet and kjet will be upgraded, but it should not be much longer after that, so the same question applies there.

**Comment by WenMeng-NOAA** [comment]
> Will a lot of developers/users still be working on CentOS between now and April 2nd on Hera? Would it make more sense to transition entirely to Rocky 8 so an additional PR is not required after the upgrade?
> 
> I'm not sure when Jet and kjet will be upgraded, but it should not be much longer after that, so the same question applies there.

@DavidHuber-NOAA The modulefiles jet_c.lua and hera_c.lua are for CentOS 7 nodes on Jet and Hera.

**Comment by DavidHuber-NOAA** [comment]
@WenMeng-NOAA Yes, I see that, but my question is if those really need to be included.  Since CentOS will only be available for another two weeks, does the UPP really need to support CentOS during that period?

If the answer is yes, then I should point out that in two weeks, the build script will attempt to compile using `hera_c` modules when logged into nodes `hfe01` through `hfe08`, which will fail.  Thus, a new UPP PR will need to be written soon and all downstream applications will need to pick it up.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA Yes, I see that, but my question is if those really need to be included. Since CentOS will only be available for another two weeks, does the UPP really need to support CentOS during that period?
> 
> If the answer is yes, then I should point out that in two weeks, the build script will attempt to compile using `hera_c` modules when logged into nodes `hfe01` through `hfe08`, which will fail. Thus, a new UPP PR will need to be written soon and all downstream applications will need to pick it up.

@DavidHuber-NOAA The hera_c and jet_c are workaround for our UPP developers from GFS and RRFS during rocky8 transition period. GSL has been running RRFS parallel on Jet. When rocky8 transition on Hera is completed, I will update UPP for all rocky8 configuration.

**Comment by DavidHuber-NOAA** [comment]
Alright, that sounds good then.

**Review by DavidHuber-NOAA — APPROVED** [review]
All modules point where they should.  Approve.

**Comment by WenMeng-NOAA** [comment]
@DavidHuber-NOAA I will update upp revision at ufs-weather-model after rocky8 transition is done on Hera.

**Review by FernandoAndrade-NOAA — APPROVED** [review]
Hercules and Orion RTs have completed successfully with no changes to results. Hera RTs during earlier testing on Rocky 8 showed no changes. Jet build on Rocky 8 did not run into any issues.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
