### PR TITLE
updated Doxyfile, turned on warnings

### LINKED ISSUE #389: Update Doxyfile.in, turn on warnings
The doxygen documentation build uses the settings file docs/Doxyfile, which is generated by CMake from docs/Doxyfile.in.

The doxyfile contains many settings, and the availability of these settings changes (slowly) from version to version of doxygen.

The doxyfile used in UPP is pretty old can can be updated. Also, warnings for missing documentation can be turned on. These warnings will show up in the build, when -DENABLE_DOCS=ON is used.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #389 

Updated the Doxyfile.in to most recent version, also turned on warnings in doxygen to show what remains to be documented.

### CODE REVIEW

**Comment by fossell** [comment]
@edwardhartnett - thanks for demonstrating the warn as error feature. This can be a handy check to ensure new code is well documented by developers.  One question, does the workflow abort after the first instance of undocumented routine? Or will it indicate all undocumented routines? Specifically for example in this PRs failed checks, is AVIATION the only file with undocumented subroutine?

**Comment by edwardhartnett** [comment]
@fossell excellent question. Doxygen can be set to do one of three things:
1 - Print warnings and ignore them (the current settings).
2 - Fail at first warning.
3 - List all warnings and then fail.

After current PRs are merged, we will be in state 1. Doxygen warnings will be in the CI output, but will not cause the build to fail, so CI will still passs.

I have entered another issue (#392) which lists all the current warnings. Once these are fixed, we can turn on checking for new code, which is very worthwhile.

Once we are checking new code, we can fail on first error or fail after all errors.

**Comment by fossell** [comment]
This make sense and will be a great feature, thanks for the explanation!

**Review by fossell — APPROVED** [review]

**Comment by fossell** [comment]
@WenMeng-NOAA - This is just an update to the Doxygen file and has no code changes. I approve and it can merged as your discretion.

**Pull request merged**
