### PR TITLE
Cherry-pick #170 cloud fraction mod for FV3LAM

### PR DESCRIPTION
**Pull request by fossell**
Merge #170 mods to the release/public-v2 branch for SRW release.  @ericaligo-NOAA - Can you please confirm your mods need to go into this branch/release?  If yes, does this need to be tested by SRW team prior to merging this PR?

### CODE REVIEW

**Review by ericaligo-NOAA — APPROVED** [review]
cld_amt was read in from the dyn file, but since that will be replaced by cldfra, which is read in from the phy file, we read in one less record (14 not 15) and we can eliminate the read of cld_amt.

**Comment by fossell** [comment]
@JeffBeck-NOAA - Did you or anyone else want to review this or are we good to go with merging in Eric's mods?

**Comment by JeffBeck-NOAA** [comment]
@fossell Based on the email threads I've reviewed, I think we're ready to merge!

**Comment by fossell** [comment]
@JeffBeck-NOAA Great, thanks for confirming!

**Pull request merged**
