### PR TITLE
RRFS: Include echo top and two VIL-related fields in native-level output

### LINKED ISSUE #857: RRFS:  Add radar VIL and echo top to native-level, full-domain output
Developers at MIT / Lincoln Lab have requested that two 2D fields (radar VIL and echo top) be included in the RRFS full-domain, native-level GRIB2 files.  These fields will support planned development of aviation-related tools.  Some info:

(1) Looking at `fv3lam_rrfs.xml`, it looks like two VIL-related fields may already be present: **VIL_ON_ENTIRE_ATMOS** and **GSD_VIL_ON_ENTIRE_ATMOS**.  Adding **GSD_RADARVIL_ON_ENTIRE_ATMOS** would make a third field.  @EricJames-NOAA — Do you happen to have any background knowledge on the VIL-related output?  The PR from Oct 2023 (https://github.com/NOAA-EMC/UPP/pull/800/files) suggests that RADARVIL was being provided in the output, but I do not see the string "RADARVIL" in the control files from that time.  Thanks for any hints!

(2) Regarding echo top, this request may be straightforward:  **RETOP_ON_ENTIRE_ATMOS_SINGLE_LYR** is provided in the pressure-level grids, and seemingly just needs to be added to the native-level grids.

This issue can be assigned to me (@jaymes-kenyon).

### PR DESCRIPTION
**Pull request by jaymes-kenyon**
Echo top and two VIL-related fields (using hydrometeor- and radar-based calculations) are currently available in RRFS pressure-level output.  This PR brings these fields into the native-level output in support of #857.

### CODE REVIEW

**Comment by jaymes-kenyon** [comment]
This PR has been successfully tested in a RRFS case on Hera.  No accompanying changes are needed for the UPP executable.  The PR is ready for review.

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon From my test at /scratch1/NCEPDEV/stmp2/Wen.Meng/fv3r_2023062800, three new variables added in RRFS product list were generated as:
```
[Wen.Meng@hfe02 fv3r_2023062800]$ wgrib2 NATLEV10.tm00 -match VIL -s -stats
1237:925542459:d=2023062800:VIL:entire atmosphere (considered as a single layer):10 hour fcst::ndata=1905141:undef=0:mean=0.0453231:min=0.00133403:max=183.643:cos_wt_mean=0.0456169
1238:925917686:d=2023062800:VIL:entire atmosphere:10 hour fcst::ndata=1905141:undef=0:mean=0.0998323:min=0:max=92.7872:cos_wt_mean=0.097041
[Wen.Meng@hfe02 fv3r_2023062800]$ wgrib2 NATLEV10.tm00 -match RETOP -s -stats                                   
1243:933862515:d=2023062800:RETOP:entire atmosphere (considered as a single layer):10 hour fcst::ndata=1905141:undef=0:mean=-4745.81:min=-5000:max=16747.2:cos_wt_mean=-4758.2

```
Please verify my test and let me know if you see any discrepancies in comparison to your test.

**Comment by jaymes-kenyon** [comment]
Hi @WenMeng-NOAA — Thanks for running the test.  These results are expected; looks good to me!

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2, Hera and Orion. There will be baseline re-creation for fv3r and 3drtma with this PR.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
