### PR TITLE
Remove upp lib dependency on ip, sp and w3nco

### LINKED ISSUE #264: Compiling UPP via cmake without openmp option
The current UPP is not threading safe. It was found that building upp library via cmake having **openmp** option involved. 
` [ 2%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CTLBLK.f.o
cd /home/Wen.Meng/stmp2/develop/EMC_post/tests/build/sorc/ncep_post.fd && /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/ifort -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/bacio/2.4.1/include_4 -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/crtm/2.3.0/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/g2/3.4.1/include_4 -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/png/1.6.35/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/zlib/1.2.11/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/g2tmpl/1.9.1/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/ip/3.3.3/include_4 -I/apps/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/sp/2.3.3/include_4 -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/w3nco/2.4.1/include_4 -g -traceback -fp-model source -free -convert big_endian -O3 -module include -qopenmp -c /home/Wen.Meng/stmp2/develop/EMC_post/sorc/ncep_post.fd/CTLBLK.f -o CMakeFiles/upp.dir/CTLBLK.f.o `

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
The upp library does not depend on ip, sp and w3nco libraries. The upp executable does.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Will this PR make -qopenmp disabled in upp compiling?

**Review by aerorahul — APPROVED** [review]
These changes removes the unnecessary dependencies from the UPP library.
The executable is unchanged.
This PR will allow the UPP library to be built without OpenMP as the transitive dependencies with OpenMP are no longer part of the library.
This needs to be tested.

**Comment by aerorahul** [comment]
> @DusanJovic-NOAA Will this PR make -qopenmp disabled in upp compiling?

Yes if one wishes to build the UPP library without OpenMP.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Will this PR make -qopenmp disabled in upp compiling?

Yes. If you pass BUILD_POSTEXEC=OFF and do not turn on OPENMP. I tested only on my laptop using GNU compiler, it needs to be tested on HPCs.

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA and @aerorahul Thanks for clarifying. I tested upp lib building on Hera, Venus and saw -qopenmp removed in compiling logs. My test versions are at
/scratch1/NCEPDEV/stmp2/Wen.Meng/dusan/EMC_post/tests/install on Hera
/u/Wen.Meng/noscrubd6/ncep_post/Dusan/EMC_post/tests/install on Venus

**Comment by aerorahul** [comment]
Thanks to @DusanJovic-NOAA for really drilling into this issue.

**Comment by junwang-noaa** [comment]
@wenmeng-noaa, do you want to have the changes included in next upp tag for
hpc-stack so that it can be used in inline post?

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa I have the same thought as you. I will run a quick rt test with the ufs-weather-model and might redo tag upp_v10.0.4.

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were conducted on WCOSS-Dell, WCOSS-Cray and Hera. No changed results were found. The rt test for regional in-line post in the ufs-weather-model were conducted to test new built upp lib on WCOSS-Dell and Hera. This PR is ready for merging.

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA and @aerorahul Thanks for your help!

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa I recreated the tag upp_v10.0.4 with this new commit for installing upp/10.0.4 at the hpc-stack to support the regional in-line post.

**Comment by HuiyaChuang-NOAA** [comment]
@WenMeng-NOAA should we have Jesse test this in GFS inline post following Qingfu's procesure?

**Comment by HuiyaChuang-NOAA** [comment]
@DusanJovic-NOAA @aerorahul thank you for your help.

**Comment by WenMeng-NOAA** [comment]
@HuiyaChuang-NOAA 

>  should we have Jesse test this in GFS inline post following Qingfu's procesure?
There is no procedure to verify in-line post for FV3GFS yet. It would be great to adapt Qingfu's procedure and set up an standard UPP global in-line post verifying procedure as a part of UPP regression tests in the future. And also consider to expand for regional in-line post.

**Pull request merged**
