### PR TITLE
Post xml unify

### LINKED ISSUE #277: remove excess prints from stdout
Running UFS with the inline post, the stdout written by the post is excessive. Each task writes numerous lines of information that are not useful. If they do provide something of value for debugging, please create a debug_print flag and use that. Here are a few (written by every task). We have 144 write tasks

283:  in post_getattr_lam,output_grid=lambert_conformalnfb=           1
283:  in post_getattr_lam, lon1=  -122.1736      0.0000000E+00   21.88589
283:  in post_getattr_lam,output_grid=lambert_conformalnfb=           1
283:  in post_getattr_lam, lon1=  -122.1736      0.0000000E+00   21.88589
283:   0.0000000E+00  0.0000000E+00  0.0000000E+00
283:  in post_getattr_lam,output_grid=lambert_conformalnfb=           2
283:  in post_getattr_lam, lon1=  -122.1736      0.0000000E+00   21.88589
283:   0.0000000E+00  0.0000000E+00  0.0000000E+00
283:   nlunit=         777  post_namelist=
283:  itag
283:
283:  komax,iret for nampgb=           70           0
283:  komax,kpo,kth,th,kpv,pv,popascal==           70          47           6
283:    310.0000       320.0000       350.0000       450.0000       550.0000
283:    650.0000               8  0.5000000     -0.5000000       1.000000
283:   -1.000000       1.500000      -1.500000       2.000000      -2.000000     F
283:   gocart_on= F
283:  using pressure levels from POSTGPVARS
283:  LSM, SPL =           47   100.0000       200.0000       300.0000
283:    500.0000       700.0000       1000.000       2000.000       3000.000
283:    5000.000       7000.000       10000.00       12500.00       15000.00
283:    17500.00       20000.00       22500.00       25000.00       27500.00
283:    30000.00       32500.00       35000.00       37500.00       40000.00
283:    42500.00       45000.00       47500.00       50000.00       52500.00
283:    55000.00       57500.00       60000.00       62500.00       65000.00
283:    67500.00       70000.00       72500.00       75000.00       77500.00
283:    80000.00       82500.00       85000.00       87500.00       90000.00
283:    92500.00       95000.00       97500.00       100000.0      pthresh=
283:   1.0000000E-06
283:  set default value, ivegsrc =            1 novegtype=          20 icu_physics=
283:            4 isf_surface_physics=           2
283:  inmdl2p,pslp=   102689.9       100116.4
283:  inmdl2p,point pslp=   102033.2       100274.1     cfld=         790
283:  id(18),tinvstat,IFHR,ITMAXMIN in rhmax=            0           0           0
283:            1
283:  in calwxtbg, jsta,jend=         860         890  im=        1746
283:  in calwxtbg,me=          27 iseed=    70715701
283:  incalwxtbg, rn  0.9999999      4.6566129E-10
283:  min/max WH(:,:,20)::   -1.602954       1.287925

### LINKED ISSUE #283: Unify avblflds xml file
The avblflds xml file has all field definition to output in GRIB2.  This file is used to convert user defined control xml file into flat text file which is read in UPP. Currently there are a couple versions of  avblflds xml files used by GFS/GEFS, FV3LAM, 3DRTMA and RAP/HRRR.  An unified avblflds xml file would benefit UPP product integrity.

### LINKED ISSUE #288: duplicate code in SURFCE.f
The code in lines 5860-5909 are identical to lines 5912-5960 in SURFCE.f. So the field AKHS and AKMS (iget(503) and iget(504)) will be output twice if requested. Please remove lines 5912-5960 in  SURFCE.f

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main changes are:
1) unify avbfld xml files  used by gfs/gefs, fv3r/hafs, 3drtma perspective. The new avbfld xml file will be used in gfs, gefs, fv3lam, hafs and 3drtma.
2) modify fv3lam control file accordingly.
3) modify 3drtma control file accordingly.
4) bug fix in time stamps of averaged total TCDC and  CDLYR in fv3lam dataset.
5) remove excess printouts in UPP code via adding debugprint flag.
6) remove duplicated code for UPP ID 503 and 504.
7) remove some fields from fv3lam control file which are not available in fv3lam model output.
8) remove legacy gfs grib1 control files under parm/ and driver scripts at the top level.

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@WenMeng-NOAA would you please remove the fields 501(time averaged surface pressure), 502(time averaged/inst 10m tmp), 503(time averaged exchange coefficients for mass) and 504(time averaged exchange coefficients for wind) from LAM post control file? Currently model does not output those fields and the POST does not compute them. Those fields currently have value zero in post files.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa I could modify fv3lam control file for removing these fields but need comments from the fv3lam team.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa Please review the change 5) and 6). Thanks!

**Comment by WenMeng-NOAA** [comment]
@EdwardColon-NOAA Please let me know your comments on the changes in 3drtma control files (xml, txt). Thanks!

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa I would like to submit another PR for initializing all allocated arrays in  ALLOCATE_ALL.f.

**Review by EdwardColon-NOAA — APPROVED** [review]
Approve

**Review by junwang-noaa — APPROVED** [review]

**Review by EricRogers-NOAA — APPROVED** [review]
Approved

**Review by EdwardColon-NOAA — APPROVED** [review]
Approved

**Comment by WenMeng-NOAA** [comment]
@fossell Please review the removed legacy files. Thanks!

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were conducted on WCOSS-Dell, WCOSS-Cray and Hera. With this PR merging, the baselines for gfs, gefs, fv3lam, hafs will be re-created.

**Comment by WenMeng-NOAA** [comment]
The detail of UPP regression baseline changes were documented in issue #283 and #288.

**Review by HuiyaChuang-NOAA — APPROVED** [review]

**Pull request merged**
