### PR TITLE
Update RRFS products to switch  to WMO gribs IDs

### LINKED ISSUE #888: Removing duplicate NCEP local use ids that are used by the RRFS.
#886 Parm files need to be edited to so that WMO GRIB2 ids are used for products where duplicate NCEP local use GRIB2 ids are currently being used.

### PR DESCRIPTION
**Pull request by AndrewBenjamin-NOAA**
The following products have removed <table_info> NCEP <table_info> from fv3lam_rrfs.xml in an effort to use official WMO grib2 ids over redundant NCEP local use id's

1. REFZR
2. REFZI
3. BMIXL
4. CNWAT
5. SNOWC
6. SSRUN
7. BGRUN
8. SNOHF
9. PEVAP
10. FRICV
11. CD
12. SFEXC
13. TCOLI
14. TCOLR
15. TCOLS
16. CDLYR
17. DSWRF
18. DLWRF
19. USWRF
20. ULWRF
21. UPHL
22. VWSH
23. SNFALB
24. MSTAV

WCOSS2 test available at /lfs/h2/emc/ptmp/andrew.benjamin/post_rrfs_2023062800.240639. Removal of table_info has desired results to intended products only.

### CODE REVIEW

**Comment by AndrewBenjamin-NOAA** [comment]
@WenMeng-NOAA pushed commit to include MSTAV. Separate WCOSS2 test can be found in:
/lfs/h2/emc/ptmp/andrew.benjamin/post_rrfs_2023062800.167123

Awaiting review.

**Comment by WenMeng-NOAA** [comment]
@AndrewBenjamin-NOAA Please open an UPP issue to link this PR.

**Comment by WenMeng-NOAA** [comment]
@AndrewBenjamin-NOAA Please sync your branch with the latest UPP develop.

**Comment by AndrewBenjamin-NOAA** [comment]
@WenMeng-NOAA Done.

**Comment by WenMeng-NOAA** [comment]
@AndrewBenjamin-NOAA It appears to me there are duplicated  CNWAT entries in dataset NATLEV. You can delete the entry start at line 3027 in fv3lam_rrfs.xml. The total fields generated in NATLEV will not be changed.

**Comment by AndrewBenjamin-NOAA** [comment]
@WenMeng-NOAA The duplicate CNWAT entry has been removed.

**Comment by WenMeng-NOAA** [comment]
@AndrewBenjamin-NOAA Please sync your branch one more time for our final processing.

**Comment by AndrewBenjamin-NOAA** [comment]
@WenMeng-NOAA My branch is synced.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 and Hera. There will be baseline updates for fv3r and 3drtma with this PR.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my RT results on Hera are at /scratch1/NCEPDEV/stmp2/Wen.Meng:
```
[Wen.Meng@hfe01 ~/stmp2]$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp    75 Mar 10 00:37 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp  1951 Mar 10 00:39 fv3r_2023062800/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  1951 Mar 10 00:39 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14748 Mar 10 00:40 rtma_2023040400_pe_test/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14748 Mar 10 00:40 rtma_2023040400/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14594 Mar 10 00:41 fv3r_2023062800/NATLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14594 Mar 10 00:41 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  2516 Mar 10 00:42 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  2516 Mar 10 00:42 rtma_2023040400/PRSLEV00.tm00.diff
```
This PR is for updating some grib2 metadata in fv3r and 3drtma. There are no actual variable value changes.

**Comment by FernandoAndrade-NOAA** [comment]
Leaving a status update here, Hera still has most jobs in the queue, Orion is waiting on the hafs test cases in queue. Hercules results match with your .diff changes.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my RT results on Hera are at /scratch1/NCEPDEV/stmp2/Wen.Meng:
> 
> ```
> [Wen.Meng@hfe01 ~/stmp2]$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp    75 Mar 10 00:37 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp  1951 Mar 10 00:39 fv3r_2023062800/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  1951 Mar 10 00:39 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14748 Mar 10 00:40 rtma_2023040400_pe_test/NATLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14748 Mar 10 00:40 rtma_2023040400/NATLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14594 Mar 10 00:41 fv3r_2023062800/NATLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14594 Mar 10 00:41 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  2516 Mar 10 00:42 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  2516 Mar 10 00:42 rtma_2023040400/PRSLEV00.tm00.diff
> ```
> 
> This PR is for updating some grib2 metadata in fv3r and 3drtma. There are no actual variable value changes.

I've rerun the Hera RTs under nems temporarily, the changes match yours for fv3r and 3drtma. I've restarted RTs for the hafs test case on Orion; the expected diffs in fv3r and 3drtma are present, and the non-pe_test of the hafs case had showed no changes. If the hafs case is still in queue tomorrow morning, I would be ok with skipping that test case as it seems to be more of an issue with the long queue times.

**Review by FernandoAndrade-NOAA — APPROVED** [review]
Hera, Orion, and Hercules RTs show expected changes in results for fv3r and 3drtma cases. After today's weekly UPP discussion, we will be skipping Orion's fv3hafs_pe_test case for this PR.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
