### PR TITLE
Documentation Updates

### LINKED ISSUE #354: Documentation Updates
Documentation updates to be more inline with develop branch
- Major update to AddNewVariable document
- Update executable name
- Update table of UPP output (include satellite additions)

Link to readthedocs: https://upp-hertneky.readthedocs.io/en/update_docs_tjh/

#355

### PR DESCRIPTION
**Pull request by hertneky**
#354 Updates to documentation to be more inline with develop

### CODE REVIEW

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@hertneky All of the changes are under docs/ directory. I assume there is no need for running the UPP regression tests. Could you give the instructions of reviewing these documents in rst format online? Thanks!

**Comment by hertneky** [comment]
@WenMeng-NOAA Only documentation changes were made. These can be viewed from my fork https://upp-hertneky.readthedocs.io/en/update_docs_tjh/ or do you mean some other way?

**Comment by WenMeng-NOAA** [comment]
@hertneky That's the link I need. When your PR merged, could you add a link of  documents on a WIKI page so our UPP users can review online. Thanks!

**Comment by hertneky** [comment]
@WenMeng-NOAA That is actually on my list to do in terms of wiki updates. Kate and I discussed this yesterday, to have a link to the latest (develop) and also latest community release (v9.0.0).

**Comment by WenMeng-NOAA** [comment]
@hertneky That would be great, Thanks!

**Comment by hertneky** [comment]
@WenMeng-NOAA I added the links to the wiki. The 'latest' will update automatically when the PR is merged.

**Comment by WenMeng-NOAA** [comment]
@hertneky It looks good to me. Could you update your feature branch with upstream/develop? For your case, you may click "Fetch upstream" at your UPP fork. Thanks!

**Comment by hertneky** [comment]
@WenMeng-NOAA Done

**Comment by WenMeng-NOAA** [comment]
@hertneky It looks good to me. I might wait for @fossell 's comments for final merging. Thanks!

**Review by fossell — APPROVED** [review]
@hertneky - This looks great, thanks for all your work on these enhancements!

**Comment by WenMeng-NOAA** [comment]
There are no changed results from the UPP regression tests. This PR is ready for merging.

**Pull request merged**
