### PR TITLE
Add aerosol fields in the gefs UPP control files

### LINKED ISSUE #1032: Fix files should be in `fix/` directory and not `parm/`
Several `.dat` files such as:
``` bash 
$> ls -1 parm/*.dat
parm/hires_micro_lookup.dat
parm/nam_micro_lookup.dat
parm/rap_micro_lookup.dat
```
should be relocated to the `fix/` directory, as these are `fix/` files.

### LINKED ISSUE #1051: Add aerosol fields in the UPP control files for GEFS
Add aerosol fields in the UPP control files for GEFS.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main changes are:

- Add aerosol fields in the gefs UPP control files
- Relocate "micro_lookup" files to the fix directory

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
Moving of the fix files to `fix/` directory looks good to me.
I am not familiar with the GEFS control file contents.

**Review by lipan-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA @gspetro-NOAA You may start the UPP RTs on R&D platforms. All job cards are needed to be updated with this PR. You can get sync my job cards at /home/Wen.Meng/ovp/ncep_post/post_regression_test_new/jobs on Hera.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have completed on WCOSS2 without baseline changes.

**Review by gspetro-NOAA — APPROVED** [review]
I updated the job cards, and tests ran successfully on Hera, Orion, and Hercules with no baseline changes.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
