### PR TITLE
Jenkins RT Improvements

### LINKED ISSUE #838: Improvements to the Jenkins RT Pipeline
The Jenkins UPP RT pipeline will have added functionality for clarifying and summarizing RT results within the relevant PR once the appropriate label has been added to begin RTs across supported machines. The improvements will consist of Jenkins' added capability to comment on the relevant PR on the RT results for each machine - whether RTs simply passed or additional information if tests fail including the run directory and which cases did not pass. Jenkins will also be reconfigured to continue its tests regardless of earlier failures on other machines as results occasionally differ machine to machine and it will be helpful for tracking differences in results across systems. The current configuration will stop if the first machine fails its RTs.

### PR DESCRIPTION
**Pull request by FernandoAndrade-NOAA**
This PR introduces additional functionality to clearly display UPP regression test results on the relevant PR once initial review has been completed and the appropriate label has been added to the PR. Jenkins will now leave comments summarizing RT results on head machine. Jenkins currently runs on Hera, Orion, and with this PR, Hercules as well. Failures will be accompanied with the run directory in order to verify changes in results or diagnose issues.

- Addresses and closes #838

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
The parm/ changes were for testing purposes, it will be reverted to sync up with develop.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Do you have an UPP issue linking to this PR? Please sync parm/*fv3lam_rrf* in your branch with the UPP develop branch.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA Do you have an UPP issue linking to this PR? Please sync parm/_fv3lam_rrf_ in your branch with the UPP develop branch.

Issue created and linked, I've also reverted the rrfs dummy changes used in testing, they should match develop now.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Can you sync your branch with the latest UPP develop branch?

**Comment by FernandoAndrade-NOAA** [comment]
PR was synced and taken out of draft

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RT on Hera and Orion. Thanks!

**Comment by FernandoAndrade-NOAA** [comment]
Jenkins as of this morning is having issues connecting to the Tier1 systems and the platform team is working with system admins to get that resolved, I'll be running manually.

From a meeting discussion earlier, the degradation in performance on my side for Hera may potentially be caused by a significantly lower allocation this month for Hera specifically. Orion seems to be running fine and Hercules I'm still trying to get to fully complete RT runs. It seems at this time I will only be able to run tests for Orion while issues for the other two are resolved.

**Comment by FernandoAndrade-NOAA** [comment]
No changes in Orion UPP RTs available here:
`/work2/noaa/epic/nandoam/regression-testing/upp/orion/837/UPP/ci/rundir/upp-ORION`

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA if you could confirm your RTs were successful for Hera, could you provide a run directory? I can update the epic baselines on Hera with your files if you aren't running into any issues with your RT runs.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA if you could confirm your RTs were successful for Hera, could you provide a run directory? I can update the epic baselines on Hera with your files if you aren't running into any issues with your RT runs.

@FernandoAndrade-NOAA Please see my baselines of the UPP RT at /scratch2/NCEPDEV/ovp/Wen.Meng/ncep_post/post_regression_test_new/data_out. The run directories of this PR testing are at /scratch1/NCEPDEV/stmp2/Wen.Meng

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 and Hera without changed results. This PR is ready for merging.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
