### PR TITLE
Fix doxygen in AVIATION.f

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #392 

In this PR I fix the doxygen in the file AVIATION.f, to eliminate doxygen warnings for that file.

I cannot fix all your legacy documentation - this is just a sample to show how it should be done. ;-)

Some things to note for doxygen conversion:
* Efforts to align text in the comments with extra spaces are not needed and shouldn't be attempted. Doxygen reformats the text nicely, so all whitespace is ignored by doxygen.
* Extra documentation elements like "ABSTRACT", "INPUT PARAMETERS", "USAGE", and others can all be removed.
* Doxygen automatically finds all the functions that have been called by, and all the functions calling, a subroutine, so no need to attempt to document these manually.
* Last line of doxygen docblock has author and date.
* First sentence of each subroutine/function documentation block is important: it is the "brief description" of the function. It should be a complete sentence, with description of the function, properly punctuated.

In general, punctuation is missing from much of the documentation. Fortran programmers apparently are trying to save on keystrokes by refraining from putting a period on the end of the sentences. ;-) That's not good. Documentation should be punctuated properly to aid understanding.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@fossell Would you please review the PR? Thanks!

**Review by fossell — APPROVED** [review]

**Comment by fossell** [comment]
@edwardhartnett - Thanks for providing this an example of porting to doxygen syntax and standards.  We will use this as guidance to translate other routines as well.

@WenMeng-NOAA - This PR is just comment changes that Ed has provided as an example for doxygen. I have not tested this PR, just visually inspected. Only comments were changed in the routine, but if you want to run RTs to ensure no issues that's ok, either way is fine with me.

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett Could you sync your branch with upstream/develop? Thanks!

**Comment by edwardhartnett** [comment]
@WenMeng-NOAA I have synced branch...

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett Do you have an UPP issue linking to this PR?

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by edwardhartnett** [comment]
@WenMeng-NOAA this relates to issue #392.

**Comment by WenMeng-NOAA** [comment]
@fossell With this PR merged, would DTC put efforts to solve the list of warnings in issue #392?

**Pull request merged**
