### PR TITLE
bug fixes needed for running with libIFI

### LINKED ISSUE #641: CI failures - 'Cache not found for input keys'
I'm creating this issue to track CI errors reported by @WenMeng-NOAA @wzzheng90. They manifest as `/opt/intel/oneapi/setvars.sh: No such file or directory` but appear to be caused by a missed cache hit in the previous step: `Cache not found for input keys:`

So far, clearing the cache and trying a modified cache key have not resolved the problem.

WW3 (@JessicaMeixner-NOAA @MatthewMasarik-NOAA) have been running into what appears to be the same issue: https://github.com/NOAA-EMC/WW3/actions/runs/4262723840/jobs/7419335683#step:4:28

### LINKED ISSUE #647: compile_upp.sh cannot build with internal IFI due to error in argument parsing
The tests/compile_upp.sh was changed to require an argument to the `-I` flag, which it should not need.

This issue was found by @WenMeng-NOAA and is fixed in #646.

### LINKED ISSUE #648: Indexing error in qpf_comp causes crash in inline post when libIFI is used
The outgrid array is indexed wrong in qpf_comp. This causes a crash in the inline post when it is compiled with libIFI.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
Fixes #647, fixes #648, and fixes #641

1. Standalone UPP build script can't build libIFI internally due to an error in compile_upp.sh discovered by @WenMeng-NOAA (#647)
2. An indexing error in qpf_comp in SURFCE.f causes a segfault when libIFI is used in inline post. This error is unrelated to libIFI, but somehow affects it at runtime. (#648)
3. Fix from @WenMeng-NOAA to update the version of ubuntu to run github checks (#641)

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA Can you open a new UPP issue to link this PR?

**Comment by SamuelTrahanNOAA** [comment]
> Can you open a new UPP issue to link this PR?

I have given you not one, but *two* issues, one for each bug.

**Comment by SamuelTrahanNOAA** [comment]
The `Intel Linux Build / build (pull_request)` step failure is unrelated to my changes:

```
/home/runner/.bash_profile: line 2: /opt/intel/oneapi/setvars.sh: No such file or directory
```

**Comment by WenMeng-NOAA** [comment]
> The `Intel Linux Build / build (pull_request)` step failure is unrelated to my changes:
> 
> ```
> /home/runner/.bash_profile: line 2: /opt/intel/oneapi/setvars.sh: No such file or directory
> ```

Yes, this issue was addressed in #641. Could you pick up the changes from [here](https://github.com/WenMeng-NOAA/UPP/commit/ad3f74ded9510b2eb357a9e69d3f0e97042c9d8f) to combine in your PR? Also sync your branch with the top of the UPP develop branch. I will process this PR first. Thanks!

**Comment by SamuelTrahanNOAA** [comment]
Your fix is in the branch. We shall soon see if it works in my fork.

**Comment by SamuelTrahanNOAA** [comment]
I'm seeing two warnings, but no errors yet:

```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by SamuelTrahanNOAA** [comment]
All of the checks are successful, so it seems the bugs are fixed. I've opened a new issue about the warnings:

https://github.com/NOAA-EMC/UPP/issues/649

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA Can you review intel.yml update regarding CI failed at intel build? Thanks!

**Comment by AlexanderRichert-NOAA** [comment]
@WenMeng-NOAA Yep, CI changes look good to me.

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on WCOSS2, Hera and Orion. No baseline update is needed with this PR.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
