### PR TITLE
Relocate gfs/gefs/sfs control files

### LINKED ISSUE #921: Improve organization of application specific configuration files in the UPP repository.
Presently, all application configuration files or `parm` files reside under [parm/](https://github.com/NOAA-EMC/UPP/tree/develop/parm).  There are mixed conventions used in identifying the applications and their associated sub-cycles; UPPERCASE, lowercase; e.g. GFS, gfs, GEFS, gefs.  In some instances `aerosol` is used while in some other cases `chem`.  These are just some examples.  They are not exhaustive and are simply used to illustrate the point.

A proposal here is to create subdirectories under parm based on the `modelname` (gfs, gefs, rrfs, hafs, etc.) so that it makes it easier to locate, identify, and manage the versions of the various configuration files for these and upcoming applications.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Relocate gfs/gefs/sfs control files.

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
Looks good.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2  without baseline changes.

**Comment by FernandoAndrade-NOAA** [comment]
Hera RTs completed with no changes to results, I will go ahead and make the appropriate updates to the Orion job scripts as well.

**Comment by FernandoAndrade-NOAA** [comment]
No changes on Orion's RTs as well. Hercules is showing unexpected changes in 3drtma and fv3r NATLEV, as well as gfs special. There were no errors during runtime so I'm trying to figure out what's occurring there. @WenMeng-NOAA FYI I'm checking in with Zach as I believe he ran into unusual file issues as well somewhat recently following system maintenance. I may just need to recreate baselines on Hercules again.

**Review by FernandoAndrade-NOAA — APPROVED** [review]
No changes across Hera, Hercules, and Orion RTs. Hercules 3drtma, fv3r, and gfs baselines were recreated and passed RTs with no changes.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
