### PR TITLE
Small updates for RRFS snow variables

### LINKED ISSUE #592: Small changes related to frozen precip variables in RRFS
The GSL algorithm for variable density snow accumulation is not yet being output in RRFS.  Also, the accumulation period is incorrect for run total snow water equivalent accumulation.

### LINKED ISSUE #598: Correct GRIB2 labeling for MAXUVV / MAXDVV used in RRFS.
MAXUVV and MAXDVV fields are currently defined in GRIB2 as calculated over a range of pressures above ground, but in truth FV3 computes them for pressures > 100 hPa.  We should correct these fields for RRFS.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
This PR turns on the variable density snow accumulation variable.  The PR also corrects the GRIB2 encoding for run total snowfall accumulation for both WEASD and variable density snow accumulation; these were incorrectly encoded as 1-h accumulations.  

The code produces bitwise identical results for all regression tests.  It has been tested for RRFS_CONUS_3km system (RRFS_B) on Jet.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Will you combine the changes for the issue #598 in this PR or a separate PR? Thanks!

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Will you combine the changes for the issue #598 in this PR or a separate PR? Thanks!

@WenMeng-NOAA good idea to combine these changes.  I will update my branch shortly.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Your PR will be the next one to be processed. Can you sync your branch with upstream/develop? Thanks!

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA My UPP test with the RRFS model history files provided by you is at
/scratch1/NCEPDEV/stmp2/Wen.Meng/rrfs_2022102713
Please verify and let me know if it is consistent with your test. Thanks!

**Review by MatthewPyle-NOAA — COMMENTED** [review]
Things look good from my perspective (focusing more on the MAXUVV/MAXDVV labeling issue).

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA My UPP test with the RRFS model history files provided by you is at /scratch1/NCEPDEV/stmp2/Wen.Meng/rrfs_2022102713 Please verify and let me know if it is consistent with your test. Thanks!

@WenMeng-NOAA your results look consistent with my test!  Thanks!

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on WCOSS2, Hera and Orion. No baseline update is needed with this PR.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
