### PR TITLE
Update UPP for GFS V17 HR4

### LINKED ISSUE #738: Remove time averaged P-type products for GFS V17
Per EMC MEG team's suggestion, time averaged P-type products should be removed for GFS V17.

### LINKED ISSUE #767: Remove several ice products from UPP output for GFS V17
It is decided that following ice products will be generated from the Ocean/Ice component for GFS V17:

- ICEC (ice cover or sea ice concentration)
- ICETK (ice thickness)
- ICETMP (ice temperature)

Therefore, these variables will be removed from the UPP GFS control files and related pgrb2 product list for GFS V17.

### LINKED ISSUE #891: Reading 3D Soil-related variables
Update the interface of FV3 based models to read 3D soil-related variables.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main updates are:

- Remove ICETMP and ICEG
- Remove time averaged P-types
- option for reading 3D soil fields

### CODE REVIEW

**Review by HuiyaChuang-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2. The changes will be in gfs baseline only. The following fields will be removed from GFS master and related pgrb2/pgrb2b files:
```
CSNOW:surface:0-6 hour ave fcst:
CRAIN:surface:0-6 hour ave fcst:
CICEP:surface:0-6 hour ave fcst:
CFRZR:surface:0-6 hour ave fcst:
VVEL:?? mb
VVEL:0.995 sigma level
ICETMP:surface
ICEG:10 m above mean sea level
```
The total fields in master file is 1045.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA This PR is ready for testing on Hera and Orion.

**Comment by FernandoAndrade-NOAA** [comment]
> The UPP RTs were completed on WCOSS2. The changes will be in gfs baseline only. The following fields will be removed from GFS master and related pgrb2/pgrb2b files:
> 
> ```
> CSNOW:surface:0-6 hour ave fcst:
> CRAIN:surface:0-6 hour ave fcst:
> CICEP:surface:0-6 hour ave fcst:
> CFRZR:surface:0-6 hour ave fcst:
> VVEL:?? mb
> VVEL:0.995 sigma level
> ICETMP:surface
> ICEG:10 m above mean sea level
> ```
> 
> The total fields in master file is 1045.

Hera, Hercules, and Orion RTs match with your results.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa @HuiyaChuang-NOAA Following our discussion, VVEL products have been retained in the HR4 product list. Removal will be addressed later.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA This PR is ready for testing. You may refer my tests on Hera at /home/Wen.Meng/stmp2:
```
[Wen.Meng@hfe11 stmp2]$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp    75 Mar 21 23:54 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp 21144 Mar 22 00:07 gfs.20190830/gfs.t00z.master.grb2f006.diff
-rw-r--r-- 1 Wen.Meng stmp 21144 Mar 22 00:08 gfs.20190830_pe_test/gfs.t00z.master.grb2f006.diff
```
The GFS master file is changed from 1109 fields to 1103 fields.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA This PR is ready for testing. You may refer my tests on Hera at /home/Wen.Meng/stmp2:
> 
> ```
> [Wen.Meng@hfe11 stmp2]$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp    75 Mar 21 23:54 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp 21144 Mar 22 00:07 gfs.20190830/gfs.t00z.master.grb2f006.diff
> -rw-r--r-- 1 Wen.Meng stmp 21144 Mar 22 00:08 gfs.20190830_pe_test/gfs.t00z.master.grb2f006.diff
> ```
> 
> The GFS master file is changed from 1109 fields to 1103 fields.

RTs on Hera, Hercules, and Orion are showing the same results.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
