### PR TITLE
Correct total soil moisture from SOIMOI to CISOIM

### LINKED ISSUE #914: Change grib2 name of total soil moisture
@EricJames-NOAA indicated that UFS based models output total soil moisture in units kg/m2 but the UPP read this variable and write out as SOILMOI, which uses units kg/m3. The fix involves replacing SOILMOI with CISOILM which uses units kg/m2.

### LINKED ISSUE #923: The inline post failure at ufs-weather-model for debug mode
The inline post failed at ufs-weather-model debug mode ([here](https://github.com/ufs-community/ufs-weather-model/pull/2213)).

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main updates include:

- Change the grib2 name of total soil moisture from SOILMOI into CISOILM.
- Update CMake debug option to solve inline post failure at ufs-weather-model debug mode.

### CODE REVIEW

**Review by HuiyaChuang-NOAA — APPROVED** [review]
Thanks.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 with baseline change for gfs.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. The expected changes are:
```
-rw-r--r-- 1 wen.meng emc 777 Apr  8 19:28 gfs.20190830/gfs.t00z.sfluxgrbf006.grib2.diff
-rw-r--r-- 1 wen.meng emc 777 Apr  8 19:40 gfs.20190830_pe_test/gfs.t00z.sfluxgrbf006.grib2.diff
```
The actual change is in metadata of gfs.t00z.sfluxgrbf006:
```
from 
  21:45715792:d=2019083000:SOILMOI:0-2 m below ground
into
  21:45715792:d=2019083000:CISOILM:0-2 m below ground
```

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may refer to my testing at /home/Wen.Meng/stmp2/ on Hera:
```
Wen.Meng@hfe08 stmp2$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp  75 Apr  8 23:07 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp 417 Apr  8 23:15 gfs.20190830/gfs.t00z.sfluxgrbf006.grib2.diff
-rw-r--r-- 1 Wen.Meng stmp 417 Apr  8 23:16 gfs.20190830_pe_test/gfs.t00z.sfluxgrbf006.grib2.diff
```

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may refer to my testing at /home/Wen.Meng/stmp2/ on Hera:
> 
> ```
> Wen.Meng@hfe08 stmp2$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp  75 Apr  8 23:07 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp 417 Apr  8 23:15 gfs.20190830/gfs.t00z.sfluxgrbf006.grib2.diff
> -rw-r--r-- 1 Wen.Meng stmp 417 Apr  8 23:16 gfs.20190830_pe_test/gfs.t00z.sfluxgrbf006.grib2.diff
> ```

Hera, Hercules, and Orion RTs match with your results on my side, thank you.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
