### PR TITLE
Change gtg_algo inputs (MDLFLD.f)

### LINKED ISSUE #1073: Update UPP interface with GTG4 to use instantaneous fluxes
UPP interface with GTG currently uses **time-averaged** sensible and latent heat fluxes most likely because GFS used to only output
time-averaged fluxes.  During recent exercise to validate UPP GTG4 using HRRR output, it was discovered **instantaneous fluxes** are used for producing GTG for HRRR. 

 **NCAR decided they want to use instantaneous fluxes for all models.**  

@hsinmulin-NOAA already updated his local version of UPP code and make comparison plots using HRRR output.  He will attach plots.
@YaliMao-NOAA will make and attach comparison plots for her GFS benchmark case.

### PR DESCRIPTION
**Pull request by hsinmulin-NOAA**
Change inputs for gtg_algo from averaged (sfcshx, sfclhx) to instantaenous (twbs, qwbs)

Per [issue 1073](https://github.com/NOAA-EMC/UPP/issues/1073)

### CODE REVIEW

**Comment by hsinmulin-NOAA** [comment]
This PR is additional to the RELEASE/RRFS V.1.
The change will also be used in WAFS (GFS), HRRR for Aviation

**Comment by WenMeng-NOAA** [comment]
@hsinmulin-NOAA @YaliMao-NOAA Please validate my GTG generation tests on WCOSS2:
GTG-GFS: 
Before: /u/wen.meng/ptmp/post_gfs_wafs_2019083000-before
After: /u/wen.meng/ptmp/post_gfs_wafs_2019083000-after

GTG-RRFS:
Before: /u/wen.meng/ptmp/post_rrfs_2022022412-before
After: /u/wen.meng/ptmp/post_rrfs_2022022412-after

**Comment by hsinmulin-NOAA** [comment]
Hi, Wen

The results for RRFS are expected and consistent with the changes.

CATEDR
<https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/zzz/2022022412-diff-CATEDR_org-new.plots-conus3km-bilinear/CATEDR_org-new_diff.gif>
CITEDR
<https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/zzz/2022022412-diff-CITEDR_org-new.plots-conus3km-bilinear/CITEDR_org-new_diff.gif>
EDPARM
<https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/zzz/2022022412-diff-EDPARM_org-new.plots-conus3km-bilinear/EDPARM_org-new_diff.gif>
MWTURB
<https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/zzz/2022022412-diff-MWTURB_org-new.plots-conus3km-bilinear/MWTURB_org-new_diff.gif>
MXEDPRM
<https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/zzz/2022022412-diff-MXEDPRM_org-new.plots-conus3km-bilinear/MXEDPRM_org-new_diff.gif>


Thanks

Lin

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA You may start the UPP RTs on R&D machines. There should be no baseline changes with this PR since the GTG testing is not included.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2 with no baseline changes.

**Review by gspetro-NOAA — APPROVED** [review]
RTs passed on Hera, Orion, and Hercules with no baseline changes.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
