### PR TITLE
Changes needed for ufs-weather-model IFI regression tests on Acorn

### LINKED ISSUE #656: Updates needed for IFI on Acorn & inline post
In its pull request to ufs-weather-model, the IFI is getting regression tests on Acorn. These are two related problems in UPP

1. The standalone UPP build system has the wrong path for libifi on acorn.
2. The fv3lam.xml and associated txt do not request the IFI fields.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
In its pull request to ufs-weather-model, the IFI is getting regression tests on Acorn. These are two related problems in UPP

1. The standalone UPP build system has the wrong path for libifi on acorn.
2. The fv3lam.xml and associated txt do not request the IFI fields.

Issue is here:

https://github.com/NOAA-EMC/UPP/issues/656

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA Can you open an UPP issue for this PR? Thanks!

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA Can you sync your branch with the top of the UPP develop?

**Comment by SamuelTrahanNOAA** [comment]
I just synced it.

**Comment by WenMeng-NOAA** [comment]
The testing of building UPP excitable with IFI lib on WCOSS2_Acorn looks good.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on WCOSS2, Hera and Orion. The new baseline for rrfs will be recreated with this PR. This PR is ready for merging.

**Pull request merged**
