### PR TITLE
Cam update ug

### PR DESCRIPTION
**Pull request by camshe**
Issue #596

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@camshe Could you find why the latest commit of your branch cam_update_ug failed at build on github?

**Comment by WenMeng-NOAA** [comment]
@camshe Can you sync your branch with upstream/develop?

**Comment by WenMeng-NOAA** [comment]
@fossell and @hertneky Please review and comment this PR.

**Comment by camshe** [comment]
Changes failing in fork

**Pull request closed without merging**
