### PR TITLE
Correct model name for RRFS in-flight icing and update GTG version

### LINKED ISSUE #897: correct model name for RRFS in-flight icing output
@AndrewBenjamin-NOAA discovered RRFS IFI output uses HRRR as the model name rather than RRFS.
@hsinmulin-NOAA made a correction to fv3lam_rrfs.xml (RRFS UPP control file) and demonstrated this fixed the issue.
Including @jaymes-kenyon, @EricJames-NOAA, @MatthewPyle-NOAA @SamuelTrahanNOAA for awareness.

### LINKED ISSUE #899: Upgrade GTG revision number in UPP
GTG has a new version v4.16.2 and can be updated in UPP now.

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
- Correct model name for RRFS in-flight icing output #897 
- Update GTG version to v4.16.2

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA Do you have an UPP issue for GTG version upgrade? If not, please open a new one.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA Can you sync your branch for processing?

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA From my UPP GTG generation testing with GFS, there is no changed results in wafs dataset. Please confirm that is expected.

**Comment by YaliMao-NOAA** [comment]
Yes, it is as expected for GFS GTG. GTG code just has some printout modifications.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 without changed results.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. The changes with this PR will be in metadata of fv3r and 3drtma baselines.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may refer to my tests on Hera at /home/Wen.Meng/stmp2:
```
Wen.Meng@hfe06 stmp2$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp    75 Mar 25 20:05 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp 14330 Mar 25 20:06 rtma_2023040400_pe_test/IFIFIP00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14330 Mar 25 20:06 rtma_2023040400/IFIFIP00.tm00.diff
```

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may refer to my tests on Hera at /home/Wen.Meng/stmp2:
> 
> ```
> Wen.Meng@hfe06 stmp2$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp    75 Mar 25 20:05 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp 14330 Mar 25 20:06 rtma_2023040400_pe_test/IFIFIP00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14330 Mar 25 20:06 rtma_2023040400/IFIFIP00.tm00.diff
> ```

UPP RTs have completed on Hera, Hercules, and Orion with the same results, looks good from my side.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Comment by WenMeng-NOAA** [comment]
The baseline recreation is needed for fv3r and 3drtma.

**Pull request merged**
