### PR TITLE
Add flux interpolation for coupled

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
Brings the changes that were made to create interpolated flux files for coupled forecasts that are in global-workflow back to UPP.

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Unlike the aborted PR, this only adds the coupled functionality.

**Comment by WenMeng-NOAA** [comment]
@WalterKolczynski-NOAA I guess this PR is not needed since you already adapt gfs post process scripts in global-workflow repository, right?

**Comment by WenMeng-NOAA** [comment]
@WalterKolczynski-NOAA It seems to me that you already adapted some gfs post process scripts in global-workflow repos., would you like this PR still merged in UPP develop branch?

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA It seems to me that you already adapted some gfs post process scripts in global-workflow repos., would you like this PR still merged in UPP develop branch?

That's up to you. I opened these PRs at your request, and we aren't even using these versions of the scripts anymore. So if you want to forgo them, I have no problem with that.

**Comment by WenMeng-NOAA** [comment]
Close this PR since all gfs post process scripts will be transitioned to the global-workflow repository.

**Pull request closed without merging**
