### PR TITLE
Support IntelLLVM compiler

### LINKED ISSUE #1002: Upgrade to Intel LLVM Compiler
The 'classic' Intel compilers (ifort, icc, and icpc) are now discontinued and the new LLVM compilers (ifx and icx) are the only option starting with version 2024.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
This PR adds support for Intel LLVM compiler.

`CMakeLists.txt` and `sorc/ncep_post.fd/CMakeLists.txt` are updated to recognize 'IntelLLVM' compiler id as an Intel compiler and to define compiler flags.

See https://github.com/ufs-community/ufs-weather-model/pull/2224 for details

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@FerdousiAfroz-NOAA You may start the UPP RT on R&D machines. There should be no baseline update.

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Do you know if IntelLLVM compiler has been installed on WCOSS2 and R&D machines?

**Review by FernandoAndrade-NOAA — APPROVED** [review]
UPP RTs completed. No changes in results across Hera, Hercules, and Orion.

**Comment by DusanJovic-NOAA** [comment]
Please wait with merging this PR until we run all ufs-weather-model regression test to confirm everything works as expected.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
