### PR TITLE
Revert "Feature/cleanup"

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Reverts NOAA-EMC/EMC_post#95

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
I assume all is good.

**Comment by WenMeng-NOAA** [comment]
@fossell I think you have merged this PR. Do you think  the branch revert-95-feature/cleanup should be deleted now?

**Comment by aerorahul** [comment]
@WenMeng-NOAA I think it is safe to delete `revert-95-feature/cleanup`.

**Comment by WenMeng-NOAA** [comment]
@aerorahul Thanks for confirming.

**Pull request merged**
