### PR TITLE
Bug fix in qrmax initialization.

### LINKED ISSUE #718: Duplicate UPP ID 689
In `post_avblflds.xml`, 689 is used twice as a `post_avblfldidx` attribute, once for `NH4_ON_HYBRID_LVL` and once for `SU_AER_SFC_MASS_CON`. Since `post_avblfldidx` corresponds to the UPP ID, which is a unique ID, this needs to be fixed so that each variable in fact has its own unique ID.

### LINKED ISSUE #720: GFS Failure on WCOSS2
It was found the GFS test failed on WCOSS2 as:
```
nid001601.dogwood.wcoss2.ncep.noaa.gov 41: forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source          
upp.x              0000000000F53ECA  Unknown               Unknown  Unknown
libpthread-2.31.s  000014FA072818C0  Unknown               Unknown  Unknown
libiomp5.so        000014FA088A4511  Unknown               Unknown  Unknown
libiomp5.so        000014FA088A6424  Unknown               Unknown  Unknown
upp.x              0000000000F93E5D  Unknown               Unknown  Unknown
upp.x              00000000005FD0A2  de_allocate_              399  DEALLOCATE.f
upp.x              000000000057555A  MAIN__                    722  WRFPOST.f
upp.x              0000000000410B52  Unknown               Unknown  Unknown
libc-2.31.so       000014FA0695C2BD  __libc_start_main     Unknown  Unknown
upp.x              0000000000410A6A  Unknown               Unknown  Unknown

```

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Bug fix in qrmax initialization in INITPOST_NECDF.f.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Please conduct the UPP RT tests on Hera and Orion and check gfs runtime logs to see if the error messages in issue #720 are solved.

**Review by zhanglikate — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA UPP RTs have finished on Hera and Orion with no changes to results. I did not see any GFS segmentation fault errors with this PR

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA UPP RTs have finished on Hera and Orion with no changes to results. I did not see any GFS segmentation fault errors with this PR

@FernandoAndrade-NOAA Great! Thanks for confirming. I just combined another fix in this PR and don't think RT tests are needed again since the change is in post_avblflds.xml only.

**Comment by WenMeng-NOAA** [comment]
The UPP control flat files were regenerated with updated post_avblflds.xml file on WCOSS. No updates for flat text files are needed.

**Pull request merged**
