### PR TITLE
Move package config to top-level CMakeLists.txt

### LINKED ISSUE #375: Move cmake 'Package config' code to the top-level CMakeLists.txt
In order to use (and build) UPP as a submodule of another project, the 'package config' cmake code should be moved from `sorc/ncep_post.fd/CMakeLists.txt` to the top-level `CMakeLists.txt`.
Also, in `configure_package_config_file` function `${CMAKE_SOURCE_DIR}` should be changed to `${CMAKE_CURRENT_SOURCE_DIR}`.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
Fixes #375.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Thanks for bringing the new feature to enhance inline post. Do you have suggestions on checking out 
UPP branch or tag in FV3? Not all of commits in UPP develop branch are for inline post.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Thanks for bringing the new feature to enhance inline post. Do you have suggestions on checking out UPP branch or tag in FV3? Not all of commits in UPP develop branch are for inline post.

We will update upp submodule in FV3 only when there's a bugfix or a new functionality that inline post in FV3 needs. Definitely not after every UPP commit.

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Could you update VERSION to 10.0.11? I would like to recognize this PR as a new progress in UPP enhancement. Thanks!

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were successfully completed on WCOSS-Dell, WCOSS-Cray and Hera. No changed results were found. This PR is ready for merging.

**Review by WenMeng-NOAA — APPROVED** [review]

**Review by fossell — APPROVED** [review]

**Pull request merged**
