### PR TITLE
Port and optimize build and job scripts for S4

### LINKED ISSUE #341: Port to S4
EMC_post should be ported to SSEC's S4 cluster to enable UFS and DA research efforts on that system.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
The build scripts have been ported to S4.  Additionally, a few of the job scripts supporting the global workflow have been optimized for running on S4.  Since S4 is a small cluster (80 nodes, with 40 usable by any one user at a time), the post jobs were reduced to using one node each on the s4 partition.  To help with this, wgrib2 is restricted to one CPU per call (-ncpu=1) when called in the [srun --multi-prog call of fv3gfs_dwn_nems.sh from fv3gfs_downstream_nems.sh](https://github.com/NOAA-EMC/EMC_post/blob/11b75ffcb0076950547eb9dc7c2ed563de6a88fc/ush/fv3gfs_downstream_nems.sh#L184).  This greatly improved run times (gdasposts run in ~60s, gfsposts average ~450s).

Two cycled tests have been performed on S4, one at 192/96 from 2020073118 through 2020081000 and the other at 384/192 from 2020073118 through 2020080400.  Logs and data from these runs are available on Orion:
__192/96__
Logs: /work/noaa/nesdis-rdo2/dhuber/s4_logs/test_dev
Comrot (2020081000 only): /work/noaa/nesdis-rdo2/dhuber/s4_data/comrot/test_dev
Archive: /work/noaa/nesdis-rdo2/dhuber/s4_data/archive/test_dev

__384/192__
Logs: /work/noaa/nesdis-rdo2/dhuber/s4_logs/test_dev_384
Comrot (2020081000 only): /work/noaa/nesdis-rdo2/dhuber/s4_data/comrot/test_dev_384
Archive: /work/noaa/nesdis-rdo2/dhuber/s4_data/archive/test_dev_384

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@DavidHuber-NOAA Can you sync your branch with the latest commit in develop  branch on the authoritative repos.? The procedure can be found at https://github.com/NOAA-EMC/EMC_post/wiki/UPP-Code-Development#update-your-branch-at-your-fork-with-branch-develop-at-authoritative-repository. Your PR will be the next for merging. Thanks!

**Comment by DavidHuber-NOAA** [comment]
@WenMeng-NOAA Alright, I've updated the branch.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were conducted on WCOSS-Dell, WCOSS-Cray and Hera. No changed results were found. This PR is ready for merging.

**Comment by DavidHuber-NOAA** [comment]
@WenMeng-NOAA Thank you!

**Comment by WenMeng-NOAA** [comment]
@DavidHuber-NOAA Thanks for adding support for s4.

**Pull request merged**
