### PR TITLE
ufs_release_1.0: cleanup work 2020/01/06

### PR DESCRIPTION
**Pull request by climbfuji**
- update submodule pointer for cmake, add branch information
- update include/lib flags for nemsio, sigio, sfcio in `sorc/ncep_post.fd/CMakeLists.txt`
- add REQUIRED attribute to find_package calls

### CODE REVIEW

**Comment by climbfuji** [comment]
@DusanJovic-NOAA do you know if LAPACK is a required dependency for NCEPLIBS-post? If I comment out find_package(LAPACK) it still compiles fine, but I don't know if this is because the system finds the lapack libraries automatically in the system include/library paths. Similar question for NCEPLIBS-grib_util. Thanks!

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA do you know if LAPACK is a required dependency for NCEPLIBS-post? If I comment out find_package(LAPACK) it still compiles fine, but I don't know if this is because the system finds the lapack libraries automatically in the system include/library paths. Similar question for NCEPLIBS-grib_util. Thanks!

I think it does not require LAPACK. I also commented out find_package(LAPACK) and successfully built the EMC_post.

**Comment by climbfuji** [comment]
Thanks, will comment them out in the PRs.

**Comment by climbfuji** [comment]
@Hang-Lei-NOAA actually can you merge this PR, please? I do not have write access to EMC_post. Thanks! It is ready to go.

**Comment by fossell** [comment]
@climbfuji - I'll merge this for you.

**Comment by Hang-Lei-NOAA** [comment]
I don’t have the write access either.
Ask mark Potts, he has super access to all EMC repo. Or ask post people:
Jesse.Meng@noaa.gov

Hang

**Comment by Hang-Lei-NOAA** [comment]
Thanks Kate!

**Comment by climbfuji** [comment]
Thanks to both of you, Kate and Hang!

**Comment by DusanJovic-NOAA** [comment]
${GFSIO_INC} should be ${GFSIO_INC4} in sorc/ncep_post.fd/CMakeLists.txt, here:

https://github.com/NOAA-EMC/EMC_post/blob/9bd8aed6418550842dfae1e0d9fd3a8aa915908f/sorc/ncep_post.fd/CMakeLists.txt#L191

For example, these are environment variables set by gfsio module on wcoss_dell_p3:
```
$ module show gfsio/1.1.0
--------------------------------------------------------------------------------------------------------------------------------------------
   /gpfs/dell1/nco/ops/nwprod/modulefiles/compiler_prod/ips/18.0.1/gfsio/1.1.0:
--------------------------------------------------------------------------------------------------------------------------------------------
conflict("gfsio")
setenv("COMP","ips")
setenv("GFSIO_SRC","/gpfs/dell1/nco/ops/nwprod/lib/gfsio/v1.1.0/src")
setenv("GFSIO_INC4","/gpfs/dell1/nco/ops/nwprod/lib/gfsio/v1.1.0/ips/18.0.1/include/gfsio_v1.1.0_4")
setenv("GFSIO_LIB4","/gpfs/dell1/nco/ops/nwprod/lib/gfsio/v1.1.0/ips/18.0.1/libgfsio_v1.1.0_4.a")
setenv("GFSIO_VER","v1.1.0")
help([[Set environment variables for gfsio library, including GFSIO_SRC, GFSIO_INC4, and GFSIO_LIB4]])
```

**Comment by climbfuji** [comment]
> ${GFSIO_INC} should be ${GFSIO_INC4} in sorc/ncep_post.fd/CMakeLists.txt, here:
> 
> https://github.com/NOAA-EMC/EMC_post/blob/9bd8aed6418550842dfae1e0d9fd3a8aa915908f/sorc/ncep_post.fd/CMakeLists.txt#L191

Thanks, will fix it in a minute.

**Comment by climbfuji** [comment]
> > ${GFSIO_INC} should be ${GFSIO_INC4} in sorc/ncep_post.fd/CMakeLists.txt, here:
> > https://github.com/NOAA-EMC/EMC_post/blob/9bd8aed6418550842dfae1e0d9fd3a8aa915908f/sorc/ncep_post.fd/CMakeLists.txt#L191
> 
> Thanks, will fix it in a minute.

See here: https://github.com/NOAA-EMC/EMC_post/pull/43 - will merge right away.

**Pull request merged**
