### PR TITLE
Spack Stack 1.8.0

### LINKED ISSUE #1020: Update UPP with spack-stack 1.8.0
According to EIB, spack-stack 1.8.0 will be released and installed soon.  The ufs-weather-model side will update modulefiles with the spack-stack 1.8.0, the same updates should be implemented in the UPP develop branch.

### LINKED ISSUE #1063: ip 5/5.1
Just as a headsup, the sp library is deprecated and its functionality is now under ip 5.0 (present in spack-stack-1.8.0; #983). Moving to ip 5.0 should be fairly straightforward, and involves removing/replacing `find_package(sp)` and `target_link_libraries(sp:sp_*)`. For ip 5.1, which will hopefully be in spack-stack-1.9.0, the sp functionality is in a module and therefore must be accessed through `use sp_mod`.

### PR DESCRIPTION
**Pull request by FernandoAndrade-NOAA**
This PR upgrades UPP to spack-stack 1.8.0 ~~and CRTMv3~~ alongside UFS WM PR 2453. Updates to the UPP RT scripts will be required across machines with the matching spack-stack 1.8.0 env.

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
To be safe, I created a PR based on your branch so you can review the changes: https://github.com/FernandoAndrade-NOAA/UPP/pull/3

I tested it with sp, ip 5.0, and ip 5.1, and it builds successfully for all three.

**Comment by FernandoAndrade-NOAA** [comment]
CRTMv3 will be split into a different issue.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2 with no baseline changes.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by gspetro-NOAA** [comment]
@FernandoAndrade-NOAA On Orion & Hercules, I'm getting the following error in `nohup.out`: Lmod has detected the following error: The following module(s) are unknown: "ip/5.0.0" "cmake/3.27.9". Tests passed on Hera w/no baseline changes.

**Review by gspetro-NOAA — APPROVED** [review]
RTs pass on Hera, Orion, and Hercules with no baseline changes.

**Comment by gspetro-NOAA** [comment]
This PR is ready for merging.

**Comment by jaymes-kenyon** [comment]
Hi @FernandoAndrade-NOAA — When trying to compile UPP on Jet, I am encountering this issue:
```
[jet|fe4]/mnt/lfs5/BMC/rtwbl/kenyon/mpas_upp/UPP.mpas_updates/tests> ./compile_upp.sh 
Building for machine jet, compiler intel
Lmod has detected the following error:  These module(s) or extension(s) exist but cannot be loaded as requested: "hdf5/1.14.3",
"ip/5.0.0"
   Try: "module spider hdf5/1.14.3 ip/5.0.0" to see how to load the module(s).

Executing this command requires loading "hdf5/1.14.3" which failed while processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    upp_common       /mnt/lfs5/BMC/rtwbl/kenyon/mpas_upp/UPP.mpas_updates/modulefiles/upp_common.lua
    jet              /mnt/lfs5/BMC/rtwbl/kenyon/mpas_upp/UPP.mpas_updates/modulefiles/jet.luaExecuting this command requires loading "ip/5.0.0" which failed while processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    upp_common       /mnt/lfs5/BMC/rtwbl/kenyon/mpas_upp/UPP.mpas_updates/modulefiles/upp_common.lua
    jet              /mnt/lfs5/BMC/rtwbl/kenyon/mpas_upp/UPP.mpas_updates/modulefiles/jet.lua
```
Do you have any advice on what might need to be changed?  Thanks!

**Comment by AlexanderRichert-NOAA** [comment]
@jaymes-kenyon it should work if you point the jet modulefile to /contrib/spack-stack/spack-stack-**1.8.0**/envs/ue-intel-2021.5.0/install/modulefiles/Core

**Pull request merged**
