### PR TITLE
Gefs v12 release

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**
To rename the existing files to new name and update to 64 levels for GEFS-Aerosol.

### CODE REVIEW

**Review by lipan-NOAA — APPROVED** [review]
I looks fine for me

**Review by lipan-NOAA — APPROVED** [review]
it looks good

**Review by lipan-NOAA — APPROVED** [review]
looks good

**Comment by WenMeng-NOAA** [comment]
Li, Thanks for reviewing.
I will merge the PR soon.

**Pull request merged**
