### PR TITLE
Sync the RRFS hotfix #967 and #968.

### LINKED ISSUE #980: Sync the RRFS hotfix #967 and #968 in develop
The RRFS v1 hotfix #967 and #968 should be synced in the develop branch.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Sync the RRFS hotfix #967 and #968.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. There are baseline updated for fv3r, 3drtma and gfs in this PR. You may refer to my testing on Hera at /home/Wen.Meng/stmp2:
```
Wen.Meng@hfe07 stmp2$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp   75 Jun 18 13:28 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp  724 Jun 18 13:28 fv3r_2023062800/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 1086 Jun 18 13:29 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  724 Jun 18 13:29 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 1086 Jun 18 13:29 rtma_2023040400/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 3387 Jun 18 13:40 gfs.20190830/gfs.t00z.master.grb2f006.diff
-rw-r--r-- 1 Wen.Meng stmp 3387 Jun 18 13:40 gfs.20190830_pe_test/gfs.t00z.master.grb2f006.diff
```

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. There are baseline updated for fv3r, 3drtma and gfs in this PR. You may refer to my testing on Hera at /home/Wen.Meng/stmp2:
> 
> ```
> Wen.Meng@hfe07 stmp2$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp   75 Jun 18 13:28 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp  724 Jun 18 13:28 fv3r_2023062800/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 1086 Jun 18 13:29 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  724 Jun 18 13:29 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 1086 Jun 18 13:29 rtma_2023040400/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 3387 Jun 18 13:40 gfs.20190830/gfs.t00z.master.grb2f006.diff
> -rw-r--r-- 1 Wen.Meng stmp 3387 Jun 18 13:40 gfs.20190830_pe_test/gfs.t00z.master.grb2f006.diff
> ```

My Hera run looks to match with your results. Hercules is running into file generation issues right now likely due to the disk quota being exceeded, I'm rerunning elsewhere. I believe Orion is still being tested on 1.6.0 with a unified-env-rock9 path, however I don't believe that contains the required g2tmpl version at the moment.

**Review by EricJames-NOAA — APPROVED** [review]
Looks good to me!  I tested the code for RRFS, and got consistent results with my previous tests.  Thanks for working on this.

**Comment by FernandoAndrade-NOAA** [comment]
Test results match on Hercules as well, @WenMeng-NOAA you may want to check in on Sam's comment within PR #974

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2. The baseline for gfs,fv3r and 3drtma will be recreated with this PR.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
