### PR TITLE
Enhancements for MPAS applications

### LINKED ISSUE #1039: Modifications for running UPP on MPASSIT output which contains gridpoints with missing values
Some MPAS / MPASSIT configurations produce GRIB2 output with missing sections of the domain.  This requires some added checks for SPVAL in INITPOST_MPAS code.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
Based on realtime testing with MPASSIT and UPP for a 1-km MPAS domain, we need to add some checks for SPVAL in INITPOST_MPAS.  

The log prints regarding "ABNORMAL 2MT" is also commented out to save space, because 0-h MPAS output does not have 2-m temperature (it is all zeroes).  

This PR also includes some control file updates associated with Jaymes Kenyon's recent PR.  

Testing was carried out for a realtime 1-km MPAS case on Hera.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Do you have an UPP issue linked to this PR?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Do you have an UPP issue linked to this PR?

I just created an issue...sorry about that.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you sync your branch with latest UPP develop branch for reviewing and testing?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Can you sync your branch with latest UPP develop branch for reviewing and testing?

@WenMeng-NOAA I synced it.  Thanks.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Do you have 1-km MPAS model output for my UPP standalone test?

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA My test with MPAS 3-km model output is at /home/Wen.Meng/stmp2/mpas_2024082112 on Hera. Please validate and let me know if you see issues.

**Review by jaymes-kenyon — APPROVED** [review]
@WenMeng-NOAA — These changes look good to me!  Thanks, @EricJames-NOAA!

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Do you have 1-km MPAS model output for my UPP standalone test?

@WenMeng-NOAA I have test 1-km MPAS / MPASSIT output here on Hera:

/scratch2/BMC/wrfruc/ejames/rrfs2/stmp/fire/1.0.1/rrfs.20240826/00/mpassit/00_00/MPAS-A_out.2024-08-26_00.00.00.nc

**Comment by WenMeng-NOAA** [comment]
> > @EricJames-NOAA Do you have 1-km MPAS model output for my UPP standalone test?
> 
> @WenMeng-NOAA I have test 1-km MPAS / MPASSIT output here on Hera:
> 
> /scratch2/BMC/wrfruc/ejames/rrfs2/stmp/fire/1.0.1/rrfs.20240826/00/mpassit/00_00/MPAS-A_out.2024-08-26_00.00.00.nc

@EricJames-NOAA Please validate my test with MPAS 1-km output at /home/Wen.Meng/stmp2/mpas_2024082600.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on R&D machines. There should be no baseline update with this PR.

**Comment by WenMeng-NOAA** [comment]
The UPP Rts have been completed on WCOSS2, without baseline change.

**Review by FernandoAndrade-NOAA — APPROVED** [review]
No changes across Hera, Hercules, and Orion RTs.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
