### PR TITLE
Add flight height SPFH and PRES in the RRFS product list

### LINKED ISSUE #936: Add PRES and SPFH @ 80m AGL back to RRFS control file
PRES and  SPFH @ 80m AGL need to be added back to RRFS control file according to FAA request for products on grid237.
Details:
      <param>
       <shortname>SPFH_ON_SPEC_HGT_LVL_ABOVE_GRND_FDHGT</shortname>
       <pname>SPFH</pname>
       <level>80.</level>
       <scale>5.0</scale>
        </param>

       <param>
       <shortname>PRES_ON_SPEC_HGT_LVL_ABOVE_GRND_FDHGT</shortname>
       <pname>PRES</pname>
       <level>80.</level>
       <scale>3.0</scale>
        </param>

### PR DESCRIPTION
**Pull request by hsinmulin-NOAA**
add 
1. 80 m for SPFH_ON_SPEC_HGT_LVL_ABOVE_GRND_FDHGT
2. 80 m for PRES_ON_SPEC_HGT_LVL_ABOVE_GRND_FDHGT

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
The UPP RTs are completed on WCOSS2. There will be baseline updates for fv3r and 3drtma tests.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my testing on Hera are at /home/Wen.Meng/stmp2:
```
Wen.Meng@hfe02 stmp2$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp    75 Apr 23 15:13 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp  8950 Apr 23 15:14 fv3r_2023062800/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  8950 Apr 23 15:14 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 10554 Apr 23 15:14 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 10554 Apr 23 15:15 rtma_2023040400/PRSLEV00.tm00.diff
```
New fields will be added in PRSLEV dataset in fv3r and 3drtma tests:
-------------------------
885:831483318:d=2023062800:SPFH:80 m above ground:10 hour fcst:
886:833790369:d=2023062800:PRES:80 m above ground:10 hour fcst:

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my testing on Hera are at /home/Wen.Meng/stmp2:
> 
> ```
> Wen.Meng@hfe02 stmp2$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp    75 Apr 23 15:13 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp  8950 Apr 23 15:14 fv3r_2023062800/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  8950 Apr 23 15:14 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 10554 Apr 23 15:14 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 10554 Apr 23 15:15 rtma_2023040400/PRSLEV00.tm00.diff
> ```
> 
> ## New fields will be added in PRSLEV dataset in fv3r and 3drtma tests:
> 
> 885:831483318:d=2023062800:SPFH:80 m above ground:10 hour fcst: 886:833790369:d=2023062800:PRES:80 m above ground:10 hour fcst:

Hera and Orion RTs are showing matching results. Hercules is showing changes for all cases, this is a system issue like last time as eventually after several reruns the results matched. I'll keep running Hercules in the meantime, but this PR should be good to go.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
