### PR TITLE
fix missing reflectivity bug by adding nssl mp to MP options for refl

### LINKED ISSUE #859: missing reflectivity when using inline post and NSSL microphysics with cumulus convection on
It was noticed there is missing reflectivity holes when using NSSL microphysics in RRFS ensemble. This happened when inline post is used and cumulus convection is turned on. Further debugging revealed that there is a missing hook in the post for NSSL MP (thanks to @ericaligo-NOAA). We should add imp_physics=17/18 for NSSL MP when UPP processes model reflectivity output. 

This issue will be fixed by 
#858 

[nssl_mp_refl_issue.pptx](https://github.com/NOAA-EMC/UPP/files/13991111/nssl_mp_refl_issue.pptx)

### PR DESCRIPTION
**Pull request by JiliDong-NOAA**
This PR will fix the missing reflectivity bug when using NSSL MP by adding nssl mp to microphysics options when assigning model reflectivity.

### CODE REVIEW

**Comment by JiliDong-NOAA** [comment]
another question for @WenMeng-NOAA: how often is the UPP submodule synced in ufs-weather-model to the latest UPP commit? It seems the current UPP hash in ufs-weather-model falls behind the latest code. This fix is particularly useful for inline post.

**Comment by WenMeng-NOAA** [comment]
@JiliDong-NOAA Do you have the sample model history files in netcdf with NSSL MP? I would like to do the UPP standalone test.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA Do you have the sample model history files in netcdf with NSSL MP? I would like to do the UPP standalone test.

Sure. They are here:

/scratch1/NCEPDEV/fv3-cam/Jili.Dong/physics_test/nssl_spinup/save_mem03_ctrl_fix/phyf00.nc and dynf00.nc

**Comment by WenMeng-NOAA** [comment]
@JiliDong-NOAA Can you sync your branch with the UPP develop?

**Comment by ericaligo-NOAA** [comment]
What microphysics scheme is imp_physics = 17 and 18?

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA Can you sync your branch with the UPP develop?

done

**Comment by JiliDong-NOAA** [comment]
> What microphysics scheme is imp_physics = 17 and 18?

@ericaligo-NOAA both for NSSL microphysics

**Review by ericaligo-NOAA — APPROVED** [review]
Looks good.

**Comment by WenMeng-NOAA** [comment]
@JiliDong-NOAA From my testing with your model history files, I saw the following changes in RRFS PRSLEV dataset:
```
before--
741:708678424:d=2023122000:REFZR:4000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-0.523923:min=-20:max=38.5:cos_wt_mean=-0.536283
742:708806748:d=2023122000:REFZI:4000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-3.39706:min=-20:max=42.4375:cos_wt_mean=-3.30476
744:709461679:d=2023122000:REFZR:1000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-4.68573:min=-20:max=50.625:cos_wt_mean=-4.73883
745:710228846:d=2023122000:REFZI:1000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-2.66859:min=-20:max=41.625:cos_wt_mean=-2.42332
test locations: /scratch1/NCEPDEV/stmp2/Wen.Meng/post_rrfs_2023122000
----------
after--
741:708714029:d=2023122000:REFZR:4000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
742:708952360:d=2023122000:REFZI:4000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
744:709384089:d=2023122000:REFZR:1000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
745:709622420:d=2023122000:REFZI:1000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
test location: /scratch1/NCEPDEV/stmp2/Wen.Meng/dong/post_rrfs_2023122000
```
Please let me know if you see any unexcepted changes.

**Comment by ericaligo-NOAA** [comment]
> @JiliDong-NOAA From my testing with your model history files, I saw the following changes in RRFS PRSLEV dataset:
> 
> ```
> before--
> 741:708678424:d=2023122000:REFZR:4000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-0.523923:min=-20:max=38.5:cos_wt_mean=-0.536283
> 742:708806748:d=2023122000:REFZI:4000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-3.39706:min=-20:max=42.4375:cos_wt_mean=-3.30476
> 744:709461679:d=2023122000:REFZR:1000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-4.68573:min=-20:max=50.625:cos_wt_mean=-4.73883
> 745:710228846:d=2023122000:REFZI:1000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-2.66859:min=-20:max=41.625:cos_wt_mean=-2.42332
> test locations: /scratch1/NCEPDEV/stmp2/Wen.Meng/post_rrfs_2023122000
> ----------
> after--
> 741:708714029:d=2023122000:REFZR:4000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
> 742:708952360:d=2023122000:REFZI:4000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
> 744:709384089:d=2023122000:REFZR:1000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
> 745:709622420:d=2023122000:REFZI:1000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
> test location: /scratch1/NCEPDEV/stmp2/Wen.Meng/dong/post_rrfs_2023122000
> ```
> 
> Please let me know if you see any unexcepted changes.

I'll add my two cents. The 0 values make sense to me since we don't need to compute the individual rain, snow and graupel components of reflectivity to come up with the total reflectivity. We use the total reflectivity that is passed into the UPP from the model. Lines 395 to 438 of MDLFLD.f show how in the NMMB and FA microphysics we 'estimated' the individual components (DBZR, DBZI, etc) from the total reflectivity and mixing ratios. That approach could be used or the approach from lines 681 to 709. These would be estimates for diagnostic purposes. If we left it as is, that would be fine.

**Comment by JiliDong-NOAA** [comment]
> > @JiliDong-NOAA From my testing with your model history files, I saw the following changes in RRFS PRSLEV dataset:
> > ```
> > before--
> > 741:708678424:d=2023122000:REFZR:4000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-0.523923:min=-20:max=38.5:cos_wt_mean=-0.536283
> > 742:708806748:d=2023122000:REFZI:4000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-3.39706:min=-20:max=42.4375:cos_wt_mean=-3.30476
> > 744:709461679:d=2023122000:REFZR:1000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-4.68573:min=-20:max=50.625:cos_wt_mean=-4.73883
> > 745:710228846:d=2023122000:REFZI:1000 m above ground:1 hour fcst::ndata=1905141:undef=0:mean=-2.66859:min=-20:max=41.625:cos_wt_mean=-2.42332
> > test locations: /scratch1/NCEPDEV/stmp2/Wen.Meng/post_rrfs_2023122000
> > ----------
> > after--
> > 741:708714029:d=2023122000:REFZR:4000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
> > 742:708952360:d=2023122000:REFZI:4000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
> > 744:709384089:d=2023122000:REFZR:1000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
> > 745:709622420:d=2023122000:REFZI:1000 m above ground:1 hour fcst::ndata=1905141:undef=1905141:mean=0:min=0:max=0
> > test location: /scratch1/NCEPDEV/stmp2/Wen.Meng/dong/post_rrfs_2023122000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please let me know if you see any unexcepted changes.
> 
> I'll add my two cents. The 0 values make sense to me since we don't need to compute the individual rain, snow and graupel components of reflectivity to come up with the total reflectivity. We use the total reflectivity that is passed into the UPP from the model. Lines 395 to 438 of MDLFLD.f show how in the NMMB and FA microphysics we 'estimated' the individual components (DBZR, DBZI, etc) from the total reflectivity and mixing ratios. That approach could be used or the approach from lines 681 to 709. These would be estimates for diagnostic purposes. If we left it as is, that would be fine.

I agree with @ericaligo-NOAA. REFZI and REFZR are reflectivity factors of rain and snow. When we switch the NSSL MP to use the model output for total reflectivity, we skip the part for diagnostic estimate of these two components. I think it is ok. The current RRFS parallel run with Thompson microphysics has REFZI and REFZR in grib2 but the values are always 0. Maybe we should have them removed from the grib2 product.

**Comment by WenMeng-NOAA** [comment]
@ericaligo-NOAA and @JiliDong-NOAA Thanks for explanation. We will leave calculations of REFI and REFR in UPP for diagnostic purpose.

**Comment by WenMeng-NOAA** [comment]
@MatthewPyle-NOAA Please let me know your comments on removing 1 and 4 km radar reflectivity factor for rain and snow (REFZR and REFZI) in  the RRFS dataset PRSLEV?

**Comment by ericaligo-NOAA** [comment]
@MatthewPyle-NOAA I believe these fields are nonzero in the NAM and NAM nest. The question is if these are required fields. Does anyone in the field look at them?

**Comment by ericaligo-NOAA** [comment]
@MatthewPyle-NOAA @WenMeng-NOAA @JiliDong-NOAA, do we have to decide now what to do with the DBZR, DBZI arrays or can we talk about it first, while committing this PR with those DBZX arrays being zero. As Jili pointed out, the values are 0 in RRFS. It's more important we get this working properly for NSSL MP runs.

**Comment by MatthewPyle-NOAA** [comment]
I will echo what Eric Aligo said about whether anyone uses these (seems like could be more of a microphysics developer kind of field), but also will bring in @JacobCarley-NOAA and @AndrewBenjamin-NOAA for their comments and awareness.

**Comment by JacobCarley-NOAA** [comment]
I concur with @ericaligo-NOAA and @MatthewPyle-NOAA 

That said, if they are zero then we should just remove them (unless there's a requirement they stay). Perhaps @AndrewBenjamin-NOAA knows?

**Comment by JiliDong-NOAA** [comment]
> @MatthewPyle-NOAA @WenMeng-NOAA @JiliDong-NOAA, do we have to decide now what to do with the DBZR, DBZI arrays or can we talk about it first, while committing this PR with those DBZX arrays being zero. As Jili pointed out, the values are 0 in RRFS. It's more important we get this working properly for NSSL MP runs.

I will echo what @ericaligo-NOAA  proposed too. It seems to me that all zero REFZI/REFZR in RRFS is a different issue.

**Comment by WenMeng-NOAA** [comment]
Okay. We will wrap this PR for the UPP RT and separate removal of REFZI and REFZR from the RRFS product list in another issue.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RT on Hera and Orion. There should be no baseline updates with this PR.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 and Orion without changed results. @FernandoAndrade-NOAA If you haven't started the RT yet, you might conduct on Hera only.

**Comment by FernandoAndrade-NOAA** [comment]
> The UPP RTs were completed on WCOSS2 and Orion without changed results. @FernandoAndrade-NOAA If you haven't started the RT yet, you might conduct on Hera only.

Understood thanks for the heads up, I'll start up RTs on Hera only shortly.

**Review by FernandoAndrade-NOAA — APPROVED** [review]
Hera UPP RTs completed successfully with no changes in test results.

**Comment by AndrewBenjamin-NOAA** [comment]
> I concur with @ericaligo-NOAA and @MatthewPyle-NOAA
> 
> That said, if they are zero then we should just remove them (unless there's a requirement they stay). Perhaps @AndrewBenjamin-NOAA knows?

To my knowledge, I don't know anyone who uses this operationally. At least I have not come any of these particular reflectivity products of these when I created the product lists for NOMADS and the SBN.

**Comment by WenMeng-NOAA** [comment]
> > I concur with @ericaligo-NOAA and @MatthewPyle-NOAA
> > That said, if they are zero then we should just remove them (unless there's a requirement they stay). Perhaps @AndrewBenjamin-NOAA knows?
> 
> To my knowledge, I don't know anyone who uses this operationally. At least I have not come any of these particular reflectivity products of these when I created the product lists for NOMADS and the SBN.

@AndrewBenjamin-NOAA Thanks for confirming. If you would like to remove these two fields from the RRFS product list, please submit a separate UPP PR.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Comment by ericaligo-NOAA** [comment]
> > > I concur with @ericaligo-NOAA and @MatthewPyle-NOAA
> > > That said, if they are zero then we should just remove them (unless there's a requirement they stay). Perhaps @AndrewBenjamin-NOAA knows?
> > 
> > 
> > To my knowledge, I don't know anyone who uses this operationally. At least I have not come any of these particular reflectivity products of these when I created the product lists for NOMADS and the SBN.
> 
> @AndrewBenjamin-NOAA Thanks for confirming. If you would like to remove these two fields from the RRFS product list, please submit a separate UPP PR.

I would like to talk about this with others before we remove them, if that's okay. Can someone confirm if these are present in the NAM/NAM nest with nonzero values?

**Comment by AndrewBenjamin-NOAA** [comment]
They are not on NOMADS or SBN for the NAMnest, which the RRFS is replacing. I am not sure if we will have enough space on NOMADS to include extra products for the RRFS. For v1.0 the priority needs to be to make sure current operational products make it on NOMADS/SBN.

**Comment by WenMeng-NOAA** [comment]
> > > > I concur with @ericaligo-NOAA and @MatthewPyle-NOAA
> > > > That said, if they are zero then we should just remove them (unless there's a requirement they stay). Perhaps @AndrewBenjamin-NOAA knows?
> > > 
> > > 
> > > To my knowledge, I don't know anyone who uses this operationally. At least I have not come any of these particular reflectivity products of these when I created the product lists for NOMADS and the SBN.
> > 
> > 
> > @AndrewBenjamin-NOAA Thanks for confirming. If you would like to remove these two fields from the RRFS product list, please submit a separate UPP PR.
> 
> I would like to talk about this with others before we remove them, if that's okay. Can someone confirm if these are present in the NAM/NAM nest with nonzero values?

@ericaligo-NOAA From our UPP regression tests for NAM, REFZR and REFZI are present with non missing values:
```
wgrib2 BGDAWP03.tm00.Grib2.HERA -match REF -s -stats
849:316517039:d=2014120818:REFZR:4000 m above ground:3 hour fcst::ndata=796590:undef=0:mean=-19.6287:min=-20:max=44.0625
850:316551950:d=2014120818:REFZI:4000 m above ground:3 hour fcst::ndata=796590:undef=0:mean=-17.2745:min=-20:max=48.125
```
We will not remove these calculation in UPP source code. Instead, I believe we are discussing updating the UPP RRFS control files  'fv3lam_rrfs.xml  postxconfig-NT-fv3lam_rrfs.txt' to remove these two fields from the RRFS 'PRSLEV' dataset.

**Comment by ericaligo-NOAA** [comment]
> They are not on NOMADS or SBN for the NAMnest, which the RRFS is replacing. I am not sure if we will have enough space on NOMADS to include extra products for the RRFS. For v1.0 the priority needs to be to make sure current operational products make it on NOMADS/SBN.

Thanks for checking! For diagnostic purposes, if one wants to add these they can add them to the flat files.

**Pull request merged**
