### PR TITLE
RRFS:  enable output of miscellaneous fields

### LINKED ISSUE #777: Miscellaneous new outputs for RRFS
We need to enable output of EFHL, RHPW, and TCDC on boundary layer in RRFS, to match legacy modeling systems.

### PR DESCRIPTION
**Pull request by jaymes-kenyon**
Enable various output fields in RRFS to match various legacy modeling systems. These fields are (listed by shortname):
- GSD_RH_WRT_PRECIP_WATER_ON_ENTIRE_ATMOS
- RH_ON_HGHST_TROP_FRZ_LVL
- HGT_ON_HGHST_TROP_-20C_LVL
- HGT_ON_EQUIL_LVL
- TCDC_ON_BOUND_LYR
- EFF_HLCY_ON_SPEC_HGT_LVL_ABOVE_GRND
- CRITICAL_ANGLE

Additionally, some updates/corrections to parameter names are also proposed. Specifically:
(1) For GSD_RH_WRT_PRECIP_WATER_ON_ENTIRE_ATMOS, update post_avblflds.xml with the new parameter name (was RH_PWAT, now RHPW; see number 242 in https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-0-1.shtml)
(2) For CRITICAL_ANGLE, update post_avblflds.xml to correct the parameter name (was DCAPE, should be CANGLE; see number 206 in https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-0-7.shtml)

Lastly, a "write" statement is commented-out in UPP_PHYSICS.f (in the subroutine for RHPW calculation).

This PR should address issue #777.  Thanks to @AndrewBenjamin-NOAA and @EricJames-NOAA for the collaboration.

### CODE REVIEW

**Review by EricJames-NOAA — APPROVED** [review]
Looks good to me!  Thanks for your quick work on these!

**Comment by FernandoAndrade-NOAA** [comment]
Apologies for the delay, I've run RTs with changes in fv3r and 3drtma NATLEV (1608-1755) and PRSLEV (887-1070), could you confirm these changes are consistent with your intended results on whichever system you can access for both sets of tests?
Hera: `/scratch2/NAGAPE/epic/Fernando.Andrade-maldonado/regression-tests/upp/795/rundir`
Orion: `/work/noaa/epic-ps/nandoam/upp-testing/orion/795/rundir-upp-ORION`

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2. The following seven new fields are added in PRSLEV and NATLEV datasets for both fv3r(RRFS), and 3drtma:

- RHPW:entire atmosphere
- EFHL:surface
- CANGLE:0-500 m above ground
- TCDC:boundary layer cloud layer
- RH:highest tropospheric freezing level
- HGT:253 K level
- HGT:equilibrium level

The changes in fv3r PRSLEV dataset are:
```
1681:1441800441:d=2023062800:HGT:253 K level:10 hourfcst::ndata=1905141:undef=0:mean=7532.47:min=6200:max=9060:cos_wt_mean=7589.76
1729:1512502953:d=2023062800:HGT:equilibrium level:10 hour fcst::ndata=1905141:undef=0:mean=5820.19:min=0:max=14900:cos_wt_mean=5977.71
1734:1518958964:d=2023062800:RHPW:entire atmosphere:10 hour fcst::ndata=1905141:undef=0:mean=44.0631:min=3:max=92:cos_wt_mean=43.565
1680:1441030220:d=2023062800:RH:highest tropospheric freezing level:10 hour fcst::ndata=1905141:undef=0:mean=47.0262:min=1:max=100:cos_wt_mean=45.783
1608:1343268371:d=2023062800:TCDC:boundary layer cloud layer:10 hour fcst::ndata=1905141:undef=0:mean=25.8258:min=0:max=100:cos_wt_mean=25.9689
1733:1517626881:d=2023062800:CANGLE:0-500 m above ground:10 hour fcst::ndata=1905141:undef=0:mean=64.1417:min=0:max=180:cos_wt_mean=64.0893
1732:1516813837:d=2023062800:EFHL:surface:10 hour fcst::ndata=1905141:undef=0:mean=14.1706:min=-250:max=454:cos_wt_mean=14.3734
```

**Comment by jaymes-kenyon** [comment]
Thanks, @FernandoAndrade-NOAA and @WenMeng-NOAA.

@AndrewBenjamin-NOAA — For RRFS, is the intent to include 2D fields in both the native- and pressure-level files?  I made this assumption in this PR, but want to confirm that this is the correct approach.

**Comment by AndrewBenjamin-NOAA** [comment]
@jaymes-kenyon  I don't what the intent is for all fields, but for these particular fields being added, it is good to have them on both, it will make things easier pulling fields for WMO headers

**Comment by WenMeng-NOAA** [comment]
> Thanks, @FernandoAndrade-NOAA and @WenMeng-NOAA.
> 
> @AndrewBenjamin-NOAA — For RRFS, is the intent to include 2D fields in both the native- and pressure-level files? I made this assumption in this PR, but want to confirm that this is the correct approach.

From the UPP perspective, the duplicated fields generated in both PRSLEV and NATLEV datasets cost additional time for processing. The workflow for RRFS might have a process to generate RRFS product files which are disseminated the users with the UPP output. @MatthewPyle-NOAA may chime in.

**Comment by WenMeng-NOAA** [comment]
> Apologies for the delay, I've run RTs with changes in fv3r and 3drtma NATLEV (1608-1755) and PRSLEV (887-1070), could you confirm these changes are consistent with your intended results on whichever system you can access for both sets of tests? Hera: `/scratch2/NAGAPE/epic/Fernando.Andrade-maldonado/regression-tests/upp/795/rundir` Orion: `/work/noaa/epic-ps/nandoam/upp-testing/orion/795/rundir-upp-ORION`

@FernandoAndrade-NOAA Your testing on Hera is consistent with my testing on Hera at /scratch1/NCEPDEV/stmp2/Wen.Meng

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon Please look at the changed results from my testing above. You may access the fv3r(RRFS) test case at /scratch1/NCEPDEV/stmp2/Wen.Meng/fv3r_2023062800. Please let me know if you see any unexpected results.

**Comment by jaymes-kenyon** [comment]
> @jaymes-kenyon Please look at the changed results from my testing above. You may access the fv3r(RRFS) test case at /scratch1/NCEPDEV/stmp2/Wen.Meng/fv3r_2023062800. Please let me know if you see any unexpected results.

Thanks, @WenMeng-NOAA.  How should the ".diff" files (e.g., `PRSLEV10.tm00.diff`) be interpreted?  I see lots of fields listed in these files that should not be affected by this PR.  Thanks for the explanation.

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon We use an utility to compare two grib2 files field by field (assume two files have the same record order). In your case, additional fields are added in the new grib2 file to make record order mismatching. We can ignore this kind of  grib2 comparison results and verify new field generation.

**Comment by jaymes-kenyon** [comment]
Okay, @WenMeng-NOAA—that makes sense—thanks!  The seven fields that you listed above would be expected, so I think we are in good shape.

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon Thanks for verifying.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA This PR is ready for merging. Please approve it.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
