### PR TITLE
Merge release/public-v3

### LINKED ISSUE #503: Merge release/public-v3 into develop
Merge documentation and public run script changes to develop branch.

### PR DESCRIPTION
**Pull request by fossell**
Bringing documentation and script mods from public-v3 branch to develop. No code changes, should not change results. This closes #503.

### CODE REVIEW

**Comment by fossell** [comment]
@WenMeng-NOAA - I need to update this with develop and make sure the VERSION remains on develop.  I'll let you know when it's ready.

**Review by hertneky — APPROVED** [review]

**Comment by fossell** [comment]
@WenMeng-NOAA - I'm going to delete this pull request and create a new one from a new branch that we can retain the different VERSION numbers in each and then we don't have to re commit an update. I'll just create a temporary branch to facilitate this merge. Sorry for the confusion.

**Comment by fossell** [comment]
> @WenMeng-NOAA - I'm going to delete this pull request and create a new one from a new branch that we can retain the different VERSION numbers in each and then we don't have to re commit an update. I'll just create a temporary branch to facilitate this merge. Sorry for the confusion.

@WenMeng-NOAA - Sorry Wen, it's Monday. Forgot you can't delete a PR. We'll just reconcile the VERSION after this merge as needed, that's probably easiest at this point.

**Comment by fossell** [comment]
@WenMeng-NOAA - Please take a look. I'll fix VERSION in the public-3 branch later. Just want to make sure develop is good to go first.

**Review by WenMeng-NOAA — APPROVED** [review]
The changes look good to me.

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on Hera. No changed results are found.

**Comment by WenMeng-NOAA** [comment]
@fossell The PR looks good to me. The tests were completed. Would we wait for the comment from @camshe ?

**Comment by fossell** [comment]
@WenMeng-NOAA - Thanks! You can go ahead and merge. I add @camshe on these because I'm having her virtually shadow me so she can learn about UPP and the procedures/tasks we are responsible for.  Thanks!

**Comment by WenMeng-NOAA** [comment]
@fossell Thanks for clarifying.

**Pull request merged**
