### PR TITLE
Remove old icing severity (ICSEV) from RRFS control file

### LINKED ISSUE #782: Remove old icing severity (ICSEV) from RRFS control file
The RRFS operational version will use the new icing severity (ICESEV). To save disk space, we want to remove the old icing severity.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
Removes `ICE_SEV_CAT_IFI_FLIGHT_LEVEL` from the fv3lam_rrfs.xml and corresponding .txt. This ensures the old icing severity will not be generated.

- fixes #782

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
Pinging @EricJames-NOAA @jaymes-kenyon @hu5970 who want this in the RRFS workflow.

**Comment by jaymes-kenyon** [comment]
Looks good to me—thanks @SamuelTrahanNOAA !

**Review by jaymes-kenyon — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA Please sync your branch with the latest UPP develop branch.

**Comment by SamuelTrahanNOAA** [comment]
I just did.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs are completed on WCOSS2.  The total number of records in the IFIFIP dataset for the fv3r and 3drtma tests is 180, with all ICSEV fields removed. The baselines for the fv3r and 3drtma tests will be recreated with this PR.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion.

**Comment by SamuelTrahanNOAA** [comment]
>  The total number of records in the IFIFIP dataset for the fv3r and 3drtma tests is 180, with all ICSEV fields removed.

Good. One hundred eighty records is the correct number. There are three fields with sixty levels (records) each.

**Comment by WenMeng-NOAA** [comment]
> > The total number of records in the IFIFIP dataset for the fv3r and 3drtma tests is 180, with all ICSEV fields removed.
> 
> Good. One hundred eighty records is the correct number. There are three fields with sixty levels (records) each.

@SamuelTrahanNOAA Thanks for confirming.

**Comment by FernandoAndrade-NOAA** [comment]
> The UPP RTs are completed on WCOSS2. The total number of records in the IFIFIP dataset for the fv3r and 3drtma tests is 180, with all ICSEV fields removed. The baselines for the fv3r and 3drtma tests will be recreated with this PR.

Tests have completed successfully on Hera and Orion and I'm seeing those results as well in 3drtma results for IFIFIP.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
