### PR TITLE
Add/modify RST documentation files for UPP release/public-v2

### PR DESCRIPTION
**Pull request by hertneky**
Adds new documentation:
Installation.rst - Building stand-alone
Running.rst - Running stand-alone
UPP_Grib2_table.csv/.rst - Available Grib2 fields
AddNewVariable.rst - Adding a new variable
_static/ - custom style sheets

Modifications to existing documentation for SRW/UPP stand-alone release

### CODE REVIEW

**Comment by fossell** [comment]
@hertneky - Can you sync with release/public-v2 again please?

**Comment by hertneky** [comment]
@fossell Done

**Comment by fossell** [comment]
@hertneky Thanks! One more request, in the Installation.rst (and elsewhere as needed), can we remove the entries for Hera-GNU?  It looks like this isn't going to part of the testing after all and won't be a Tier one supported platform/compiler combo. So let's just remove for now.

**Comment by hertneky** [comment]
@fossell This was only mentioned in the Installation page and is now removed.

**Comment by fossell** [comment]
@mkavulich Please just confirm/approve that we can add in our new documentation files. No changes to build or source codes.

**Review by mkavulich — APPROVED** [review]

**Pull request merged**
