### PR TITLE
Incorporate change from NCO

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Update JGLOBAL_ATMOS_POST_MANAGER with change from NCO.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA Please let me know if any changes should be in the PR. I will recreate tag upp_v8.1.0 after this PR is merged.

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good, thanks @WenMeng-NOAA !

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA Please let me know if any changes should be in the PR. I will recreate tag upp_v8.1.0 after this PR is merged.

I think this is it for right now. Feel free to merge this and recreate the UPP tag. Thanks!

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA The tag upp_v8.1.0 was recreated at 0168fbb.

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA The tag upp_v8.1.0 was recreated at [0168fbb](https://github.com/NOAA-EMC/UPP/commit/0168fbb0028d42d684d65ec9d4fdc524f99393f1).

Great, thanks @WenMeng-NOAA !

**Pull request merged**
