### PR TITLE
Update camke scripts for building upp lib.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**

### CODE REVIEW

**Review by fossell — APPROVED** [review]
This is official name change for GFS implementation of library, so it's ok with me to put this in develop.  We will update other aspects in future.  Note that UFS v2.0 (SRW) will keep nceppost as lib name for the upcoming release.

**Comment by WenMeng-NOAA** [comment]
@fossell Yes, upp lib is the official name for GFS V16 implementation.  I would expect other changes e.g. unifying executable name
in the place in the future. Thanks!

**Comment by aerorahul** [comment]
This PR is going to break the usage of nceppost in projects that use it via CMake.

**Comment by WenMeng-NOAA** [comment]
@aerorahul Are you meaning we should keep in EMC_post/CMAKEKists.txt
project(
  nceppost
  VERSION ${pVersion}
  LANGUAGES Fortran)

**Comment by aerorahul** [comment]
This change will require downstream users to change to:
`find_package(UPP)`
and then to link with `UPP::upp`
If modules are used, the modulefile will need to be updated to point to `UPP_ROOT` instead of `nceppost_ROOT`.
I am not sure yet what other changes may be needed.

**Comment by fossell** [comment]
@aerorahul - These would be required for projects who use develop branch only or are doing a sync to develop.  Would the preference for such a change be that there is a broad announcement to those projects of change? If so, how do we determine who is using the develop branch actively for their projects? What is your recommendation to make these types of changes in develop branch?  We generally operate with the understanding that projects that require stable versions are doing so within a branch or fork, not from develop where things are changing more often.  Please advise...

**Comment by WenMeng-NOAA** [comment]
@fossell and @aerorahul The intention of this PR is changing cmake scripts for building upp lib instead of nceppost lib at hpc-stack. I got some tweaking from a staff installing upp lib at hpc-stack. From my testing, the changes for nceppost into UPP will have no impacts on upp lib building under my account but not sure this is required by EIB installing under hpc-stack. I will check that.

**Comment by aerorahul** [comment]
As far as the `ufs-weather-model` is concerned, here is what we can do:

1. EMC_post develop is tagged as UPP v10.0.0
2. update hpc-stack to clone this UPP tag and build and install it.
3. update ufs-weather-model CMakeLists.txt to find_package(UPP 10.0.0) and target_link_libraries(UPP::upp) instead of nceppost

However, I am not sure if the UPP v10.0.0 is going to be identical to the nceppost SHA currently used in the weather model (dceca26)

Atleast this way, the UFS is using the latest `develop` of UPP/EMC_post.

**Comment by WenMeng-NOAA** [comment]
@aerorahul this upp/10.0.0 is not identical to the dceca26 which is a old version for GFS V16.

**Comment by WenMeng-NOAA** [comment]
Just confirm that it is not necessary to change nceppost in EMC_post/CMakeLists.txt during installing upp/10.0.0 in hpc-stack. I may revert the change. Please let me know your comments @aerorahul and @fossell.

**Comment by aerorahul** [comment]
changes in EMC_post/CMakeLists.txt have nothing to do with hpc-stack.

**Comment by junwang-noaa** [comment]
I have the upp lib related code changes in my ufs-weather-model branch
https://github.com/junwang-noaa/ufs-weather-model/tree/gfsv16_20201015. I
was using " find_package(upp REQUIRED)" (upp all lowcase).

**Comment by junwang-noaa** [comment]
The branch works with the upp in the test hpc stack Hang built on hera.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa So it looks EMC_post/CMakeList.txt should have
-----------------
project(
  upp
  VERSION ${pVersion}
  LANGUAGES Fortran)
----------------
Thanks for comments. I will add another change in the branch develop at UPP repos.

**Pull request merged**
