### PR TITLE
Replace mersenne twister in CALWXT_BOURG.f with standard Fortran RNG

### LINKED ISSUE #242: Mersenne Twister in in-line post
Dusan found the mersenne twister module in UPP routine CALWXT_BOURG.f are not working properly:

> [149]  incalwxtbg, rn  3.3978019E+38 -3.3952875E+38
> [145]  in calwxtbg, jsta,jend=          33          64  im=         384
> [145]  in calwxtbg,me=           1 iseed=   302134645
> [145]  incalwxtbg, rn  3.3978019E+38 -3.3952875E+38

The expected rn range should be within in 0 to 1. The mersenne_twister in UPP is from NCEPLIBS w3em. This issue is cased different library precision  used in ufs forecast component ( w3emc_d) and upp lib (w3emc_4) for in-line post.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
In applications like ufs, where different components are built using different precision of default reals, Mersenne twister from w3emc (which does not provide overloaded interfaces) can not be used. Replace it with standard Fortran RNG.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Can you sync your branch with upstream/develop? After that, there might be additional changes in
sorc/ncep_post.fd/TIMEF.f  due to "implicit none" implemented from the last commit. See the changes in my PR #243 
https://github.com/NOAA-EMC/EMC_post/pull/243/files#diff-855a3040248e9ead99fee9508ae601a579e01a9aaf7a9cc9cc7b1ac051af0ee4

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA 
There is a residue bug from last UPP commit, Could you add the changes in sorc/ncep_post/TIMEF.f in your branch as:
1) change
   real*8 timef
into 
   real* timef, etime
2) change
       real*8 rtc
   into
      real*8 rtc,etime

Thanks!

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA
> There is a residue bug from last UPP commit, Could you add the changes in sorc/ncep_post/TIMEF.f in your branch as:
> 
> 1. change
>    real_8 timef
>    into
>    real_ timef, etime
> 2. change
>    real_8 rtc
>    into
>    real_8 rtc,etime
> 
> Thanks!

I can add this. But `ETIME` is not standard Fortran function. Try to use only standard functions, for example `SYSTEM_CLOCK()`.

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA I might think TIMEF.f is an UPP legacy code. Could you add the upgrade in your branch too? Thanks!

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Will you update the file "VERSION" from 10.0.0 to 10.0.1?

**Review by HuiyaChuang-NOAA — APPROVED** [review]

**Review by SMoorthi-emc — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]
The code changes look good to me, but we do not have any testing on the Fortran random number generator, so the impact of the changes to post products is unknown. As Hui-ya pointed out, a new method may come soon, so this may be some temporary fix.

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests for GFS, GEFS, FV3/LAM, RAP, HRRR were conducted on WCOSS dell, cray and Hera. The precipitation types related fields will have changed results in GFS, GEFS, FV3/LAM products.  With this PR merged in develop branch, if there might be scientific concerns from the developing model parallel run, I will provide model developers the guidance of switching back to mersenne twister in their standalone post run.

**Pull request merged**
