### PR TITLE
Fix for hydrostatic runs - write out Omega and HGT from model output

### LINKED ISSUE #946: Write out HGT for hydrostatic run and omega from the model output
HGT and omega are not written out correctly in UPP for hydrostatic runs.
This issue should be fixed in offline UPP as the upcoming [update](https://github.com/XiaqiongZhou-NOAA/fv3atm/compare/da95cc428d8b626e99250fd57a4279b4980044f8...4bbb4e3f1a7bfaa7c041ef9d2415bf3c0bdef0d6#diff-44bb5bc1204d2d645d5b7152243b1a3558e1f8aef18118a02256f2bbd798b956) for inline post and the corresponding ufs-weather-model PR#[2255](https://github.com/ufs-community/ufs-weather-model/pull/2255).
This fix can also process omega in post when omega is written out by the model.

### PR DESCRIPTION
**Pull request by KarinaAsmar-NOAA**
This PR should fix UPP offline post hydrostatic runs by writing out Omega and HGT from model output. The fix is synced with inline post as described in [Issue #946 ](https://github.com/NOAA-EMC/UPP/issues/946). See issue for test results with GFSv17, GEFSv13, SFSv1.

### CODE REVIEW

**Review by XiaqiongZhou-NOAA — APPROVED** [review]
Looks good.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on R&D platforms. From my testing on Hera, no changed results.

**Comment by FernandoAndrade-NOAA** [comment]
Hera RTs completed with no changes, waiting on Hercules. Orion will be unavailable due to the OS migration.

**Comment by FernandoAndrade-NOAA** [comment]
> Hera RTs completed with no changes, waiting on Hercules. Orion will be unavailable due to the OS migration.

It looks like the fv3r pe_test did not run/complete. I will rerun on hera and append results to the log.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on R&D platforms. From my testing on Hera, no changed results.

RTs completed on Hera and Hercules, no changes in my results.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 without changed results.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
