### PR TITLE
Clean up labeling for 15-min accumulated fields

### LINKED ISSUE #772: Enable 15-min QPF output in RRFS
We need to get 15-min APCP output in RRFS since it is available in HRRR.  This will require some modifications to FV3.  Currently, it sounds like FV3 can only output a precipitation bucket that is the same length as the output frequency.  But the operational RRFS will likely have 15-min output frequency for the beginning of the forecast, then 1-h output frequency later in the forecast.  We will need both 1-h and 15-min APCP output for the first part of the forecast.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
This PR includes the following changes:

(1) corrects the time labeling for the 15-min accumulated fields for RRFS
(2) switch to use "BUCKET1" fields created for the HRRR 15-min output in RRFS
(3) add sub-hourly control files to UPP repository
(4) add output of 15-min graupel (which was included in HRRR) 

There will be a final update needed to read the correct (actual 15-min acccumulation) fields in SURFCE.f.

The code was tested for RRFS_NA_3km on Jet.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Do you have the sample model outputs for my testing on Hera?

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA I would suggest updating the parm/makefile to add new RRFS sub-hourly control files.

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Do you have the sample model outputs for my testing on Hera?

Yes, I have files here:

/scratch1/BMC/wrfruc/ejames/wen_subh/

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. No baseline update is expected.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. No baseline update is expected.

RTs completed across machines with no changes to results. Looks good to go from my side. Despite the option for maintainers to be able to make changes to the PR, I had to manually copy and paste log info due to permission issues on pushing logs, @EricJames-NOAA please double check your repository in case any repo settings are overriding push permissions.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
> > @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. No baseline update is expected.
> 
> RTs completed across machines with no changes to results. Looks good to go from my side. Despite the option for maintainers to be able to make changes to the PR, I had to manually copy and paste log info due to permission issues on pushing logs, @EricJames-NOAA please double check your repository in case any repo settings are overriding push permissions.

@FernandoAndrade-NOAA Do you have the instructions for updating the settings in developer's UPP fork so that RT logs can be automatically pushed?

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Comment by FernandoAndrade-NOAA** [comment]
> > > @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. No baseline update is expected.
> > 
> > 
> > RTs completed across machines with no changes to results. Looks good to go from my side. Despite the option for maintainers to be able to make changes to the PR, I had to manually copy and paste log info due to permission issues on pushing logs, @EricJames-NOAA please double check your repository in case any repo settings are overriding push permissions.
> 
> @FernandoAndrade-NOAA Do you have the instructions for updating the settings in developer's UPP fork so that RT logs can be automatically pushed?

I believe a quick fix for the push permissions to specific users would be to add Wen and myself as collaborators under your repo settings at the top > collaborators, that should allow us to push commits to your branches in the future.

**Pull request merged**
