### PR TITLE
RRFS updates

### LINKED ISSUE #931: Rename RRFS UPP control files
From coordination with Ben Blake (EMC), we need to change the name of the RRFS control files to get away from the fv3lam name:

fv3lam_rrfs.xml -> rrfs_postcontrol.xml
postxconfig-NT-fv3lam_rrfs.txt -> postxconfig-NT-rrfs.txt

### LINKED ISSUE #939: Miscellaneous RRFS updates
(1) Correct the reading the encoding of biomass burning emissions (it is a 3-D variable in history files, but we want to output vertically integrated emissions).
(2) Output hourly averaged HWP (hourly wildfire potential) instead of instantaneous HWP.
(3) Remove from output vertically integrated hydrometeor fields that do not account for subgrid components.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
This PR provides some updates for RRFS, including:

(1) Rename RRFS UPP control files as requested by Benjamin Blake (EMC) to get rid of "fv3lam" reference.
(2) Correct the reading of smoke emissions (EBB) to read the correct 3-D variable ebu_smoke.
(3) Enable output of 2-D smoke emissions computed as the vertically integrated smoke emissions.
(4) Update HWP to be a 1-h average (hwp_ave in netCDF files).
(5) Get rid of vertically integrated hydrometeor output which doesn't include subgrid components.

The code was tested for RRFS_NA_3km system on Jet.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you sync your branch with the latest UPP develop and provide me sample model files for testing?

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you open a new issue for your proposed changes 2) to 5)?

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA I have some test files for you here on Hera:

/scratch1/BMC/wrfruc/ejames/wen_ebb_hwp/

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA My test indicates regenerating the RRFS flat control file 'postxconfig-NT-rrfs.txt' is needed. Please validate my test results at /home/Wen.Meng/stmp2/rrfs_2024032812 on Hera.

**Review by BenjaminBlake-NOAA — APPROVED** [review]
@EricJames-NOAA  Thanks for including the RRFS file renaming changes, those look good to me.

**Comment by EricJames-NOAA** [comment]
> /scratch1/BMC/wrfruc/ejames/wen_ebb_hwp/

@WenMeng-NOAA thanks for catching that, I have regenerated the postxconfig-NT-rrfs.txt file.  

I accidentally copied over the wrong netCDF files.  Could you please run a test using these new ones:

/scratch1/BMC/wrfruc/ejames/wen_ebb_hwp/

I'm very sorry for my mistake.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Please see my new run at /home/Wen.Meng/stmp2/rrfs_2024042315.

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Please see my new run at /home/Wen.Meng/stmp2/rrfs_2024042315.

@WenMeng-NOAA your results are consistent with mine...I see the updated fields.  Thanks!

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Thanks for verifying. We will wrap this PR for the final testing.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my tests on Hera are at /home/Wen.Meng/stmp2:
```
Wen.Meng@hfe02 stmp2$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp    75 Apr 25 17:35 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp 13064 Apr 25 17:37 fv3r_2023062800/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 13064 Apr 25 17:37 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 25456 Apr 25 17:37 rtma_2023040400_pe_test/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 25456 Apr 25 17:37 rtma_2023040400/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 25172 Apr 25 17:39 fv3r_2023062800/NATLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 25172 Apr 25 17:39 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14470 Apr 25 17:39 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14470 Apr 25 17:39 rtma_2023040400/PRSLEV00.tm00.diff
```
You should change the control file 'postxconfig-NT-fv3rlam_rrfs.txt' into 'postxconfig-NT-rrfs.txt' in job cards run*fv3r* and run*3drtma*.

**Review by HuiyaChuang-NOAA — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my tests on Hera are at /home/Wen.Meng/stmp2:
> 
> ```
> Wen.Meng@hfe02 stmp2$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp    75 Apr 25 17:35 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp 13064 Apr 25 17:37 fv3r_2023062800/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 13064 Apr 25 17:37 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 25456 Apr 25 17:37 rtma_2023040400_pe_test/NATLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 25456 Apr 25 17:37 rtma_2023040400/NATLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 25172 Apr 25 17:39 fv3r_2023062800/NATLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 25172 Apr 25 17:39 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14470 Apr 25 17:39 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14470 Apr 25 17:39 rtma_2023040400/PRSLEV00.tm00.diff
> ```
> 
> You should change the control file 'postxconfig-NT-fv3rlam_rrfs.txt' into 'postxconfig-NT-rrfs.txt' in job cards run_fv3r_ and run_3drtma_.

Orion and Hercules are still running likely due to the ongoing maintenance. On Hera, I'm seeing NATLEV matching while PRSLEV are differing a bit from your results in both fv3r and 3drtma, if you could verify comparison at `/scratch2/NAGAPE/epic/Fernando.Andrade-maldonado/regression-tests/upp/938/UPP/ci/rundir/upp-HERA`

**Comment by WenMeng-NOAA** [comment]
> > @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my tests on Hera are at /home/Wen.Meng/stmp2:
> > ```
> > Wen.Meng@hfe02 stmp2$ ls -ltr */*diff
> > -rw-r--r-- 1 Wen.Meng stmp    75 Apr 25 17:35 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> > -rw-r--r-- 1 Wen.Meng stmp 13064 Apr 25 17:37 fv3r_2023062800/PRSLEV10.tm00.diff
> > -rw-r--r-- 1 Wen.Meng stmp 13064 Apr 25 17:37 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
> > -rw-r--r-- 1 Wen.Meng stmp 25456 Apr 25 17:37 rtma_2023040400_pe_test/NATLEV00.tm00.diff
> > -rw-r--r-- 1 Wen.Meng stmp 25456 Apr 25 17:37 rtma_2023040400/NATLEV00.tm00.diff
> > -rw-r--r-- 1 Wen.Meng stmp 25172 Apr 25 17:39 fv3r_2023062800/NATLEV10.tm00.diff
> > -rw-r--r-- 1 Wen.Meng stmp 25172 Apr 25 17:39 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
> > -rw-r--r-- 1 Wen.Meng stmp 14470 Apr 25 17:39 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
> > -rw-r--r-- 1 Wen.Meng stmp 14470 Apr 25 17:39 rtma_2023040400/PRSLEV00.tm00.diff
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You should change the control file 'postxconfig-NT-fv3rlam_rrfs.txt' into 'postxconfig-NT-rrfs.txt' in job cards run_fv3r_ and run_3drtma_.
> 
> Orion and Hercules are still running likely due to the ongoing maintenance. On Hera, I'm seeing NATLEV matching while PRSLEV are differing a bit from your results in both fv3r and 3drtma, if you could verify comparison at `/scratch2/NAGAPE/epic/Fernando.Andrade-maldonado/regression-tests/upp/938/UPP/ci/rundir/upp-HERA`

@FernandoAndrade-NOAA I have examined the results in both your run directories and mine, and they are consistent. I forgot to recreate the baselines from last PR in my RTs, which seems to be the root cause. Your RTs on Hera are good to me.

**Comment by FernandoAndrade-NOAA** [comment]
> > > @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my tests on Hera are at /home/Wen.Meng/stmp2:
> > > ```
> > > Wen.Meng@hfe02 stmp2$ ls -ltr */*diff
> > > -rw-r--r-- 1 Wen.Meng stmp    75 Apr 25 17:35 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> > > -rw-r--r-- 1 Wen.Meng stmp 13064 Apr 25 17:37 fv3r_2023062800/PRSLEV10.tm00.diff
> > > -rw-r--r-- 1 Wen.Meng stmp 13064 Apr 25 17:37 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
> > > -rw-r--r-- 1 Wen.Meng stmp 25456 Apr 25 17:37 rtma_2023040400_pe_test/NATLEV00.tm00.diff
> > > -rw-r--r-- 1 Wen.Meng stmp 25456 Apr 25 17:37 rtma_2023040400/NATLEV00.tm00.diff
> > > -rw-r--r-- 1 Wen.Meng stmp 25172 Apr 25 17:39 fv3r_2023062800/NATLEV10.tm00.diff
> > > -rw-r--r-- 1 Wen.Meng stmp 25172 Apr 25 17:39 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
> > > -rw-r--r-- 1 Wen.Meng stmp 14470 Apr 25 17:39 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
> > > -rw-r--r-- 1 Wen.Meng stmp 14470 Apr 25 17:39 rtma_2023040400/PRSLEV00.tm00.diff
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You should change the control file 'postxconfig-NT-fv3rlam_rrfs.txt' into 'postxconfig-NT-rrfs.txt' in job cards run_fv3r_ and run_3drtma_.
> > 
> > 
> > Orion and Hercules are still running likely due to the ongoing maintenance. On Hera, I'm seeing NATLEV matching while PRSLEV are differing a bit from your results in both fv3r and 3drtma, if you could verify comparison at `/scratch2/NAGAPE/epic/Fernando.Andrade-maldonado/regression-tests/upp/938/UPP/ci/rundir/upp-HERA`
> 
> @FernandoAndrade-NOAA I have examined the results in both your run directories and mine, and they are consistent. I forgot to recreate the baselines from last PR in my RTs, which seems to be the root cause. Your RTs on Hera are good to me.

Orion will be unavailable for testing at the moment as they prepare for a shutdown for maintenance. Hercules showed similar results to Hera RTs with differences due to the inability to update baselines in the previous PR caused by instability. Only the expected test cases are showing differences this run so Hercules should be good to go. I'll keep an eye out for when Orion is available again to proceed with the merge process.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you sync your branch one more time?

**Comment by FernandoAndrade-NOAA** [comment]
Orion RTs match with the Hera run, this PR should be ready to go following a final re-sync.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
