### PR TITLE
Read bucket either as an integer or float

### LINKED ISSUE #982: Read diagnostic accumulation bucket in float
The ufs-weather-model has updated the 'diagnostic accumulation bucket' (fhzero) attribute from integer into float. The changes should be implemented in the interface of offline post to read 'fhzero' either in integer or float.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main changes are:

- Capability of  reading bucket (fhzero) from model either as an integer or float.
- Prevent undefined PBLHGUST involved in calculation

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]
The code changes look good to me. I assume you have tested the code updates with the latest model output with real number fhzero.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. There should be no baseline update.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 without changed results.

**Review by FernandoAndrade-NOAA — APPROVED** [review]
RTs on Hera, Hercules and Orion are complete. No changes in results.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
