### PR TITLE
update gtg code revision to v4.16

### LINKED ISSUE #851: Too many printouts in the current revision number of GTG
As mentioned in PR #839, there are too many printouts in the current revision number of GTG.

As a follow up, a few suggestions were made to NCAR turbulence group:
1. At the first point,  can gtg_algo exit courteously if the required config/input files don't exist?
2. read_NamelistFileName(): assign ierr=ios if 'error opening input_file_name file'
3. Too many printouts! Can printflag be read from a configuration file instead of hard coded? Also, can the N printout files be created only when printflag>0?

In the next revision number of GTG, the printouts will be in a reasonable amount.

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
Update gtg code version to v4.16 with less printouts

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
Hi @YaliMao-NOAA, progress should hopefully resume tomorrow. Please go ahead and link / create an issue for this PR to have it ready to go for regression testing and merging. Thanks!

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 without changed results.

**Comment by WenMeng-NOAA** [comment]
The test for gtg product generation was completed on WCOSS2. The printouts from gtg code at runtime were reduced a lot.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion.

Orion is still in queue waiting on 5 tests, I will notify here once it completes. Hera and Hercules completed successfully with no changes.

**Comment by FernandoAndrade-NOAA** [comment]
All but the hrrr test cases passed without changes on Orion. The hrrr test failed due to a timeout, I'm increasing the job card's time limit from 20 to 30 and rerunning @WenMeng-NOAA FYI. The hrrr_pe_test seems to have passed without issue, just hrrr timed out.

**Comment by FernandoAndrade-NOAA** [comment]
HRRR rerun on Orion completed without issues and without changes to results. The timeout seems to have been a system issue, hrrr's rerun was 08:15 this time.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
