### PR TITLE
Bug fix for blowing snow effect on visibility

### LINKED ISSUE #927: Bug fix for BLSN visibility impact
NOAA AWC noted excessive impact of blowing snow in forested areas.  This bug fix removes any BLSN effect on visibility if roughness length is greater than 0.7.  We also need to correct a bug in the original formulation of the code, introducing a factor of ustar_t in calculation of Q_s.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
NOAA AWC noted a pronounced low bias in visibility in RRFS-A during the beta evaluation.  We confirmed it is due to the blowing snow effect.  

This PR restricts the blowing snow effect on visibility to roughness length (z0) < 0.7 (non-forested areas).  With this new code, there will be no blowing snow effect in forested areas.  

The bug fix also corrects the BLSN formulation (there was a missing factor of ustar_t in the equation for Q_s).

The code was tested for a number of blowing snow cases in RRFS_NA_3km and RRFS_CONUS_3km.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Do you have an UPP issue to link this PR?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Do you have an UPP issue to link this PR?

@WenMeng-NOAA I had one but it got closed with my recent PR.  I can open a new one if you like.

**Comment by WenMeng-NOAA** [comment]
> > @EricJames-NOAA Do you have an UPP issue to link this PR?
> 
> @WenMeng-NOAA I had one but it got closed with my recent PR. I can open a new one if you like.

@EricJames-NOAA Please open a new issue for the inventory of UPP updates. Thanks!

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you sync your branch with the latest UPP develop?

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Is your PR ready for reviewing and testing? If yes, please sync your branch with the latest UPP develop.

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA yes, this PR is ready for review!  Thanks.  I have just synced with the latest UPP develop branch.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. Please refer to my tests on Hera at /home/Wen.Meng/stmp2:
```
Wen.Meng@hfe09 stmp2$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp   132 Apr 11 18:45 rap_2020072316/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp   132 Apr 11 18:45 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp    61 Apr 11 18:45 rap_2020072316/WRFNAT.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp    60 Apr 11 18:45 post_nmmb_meso_2014120818_Grib2/BGDAWP03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp    61 Apr 11 18:45 rap_2020072316_pe_test/WRFNAT.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp    60 Apr 11 18:45 post_nmmb_meso_2014120818_Grib2_pe_test/BGDAWP03.tm00.Grib2.diff
-rw-r--r-- 1 Wen.Meng stmp    56 Apr 11 18:45 hrrr_2020060118_pe_test/WRFTWO.GrbF04.diff
-rw-r--r-- 1 Wen.Meng stmp    56 Apr 11 18:46 hrrr_2020060118/WRFTWO.GrbF04.diff
-rw-r--r-- 1 Wen.Meng stmp   370 Apr 11 18:46 fv3r_2023062800/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp   370 Apr 11 18:46 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14010 Apr 11 18:47 rtma_2023040400_pe_test/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14010 Apr 11 18:47 rtma_2023040400/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 13798 Apr 11 18:49 fv3r_2023062800/NATLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 13798 Apr 11 18:49 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  1063 Apr 11 18:49 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  1063 Apr 11 18:49 rtma_2023040400/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  3444 Apr 11 18:53 gfs.20190830/gfs.t00z.master.grb2f006.diff
-rw-r--r-- 1 Wen.Meng stmp  3444 Apr 11 18:53 gfs.20190830_pe_test/gfs.t00z.master.grb2f006.diff
```
The actual values changes should be  in variable "VIS".

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2 with baseline changes in gfs, rap, hrrr, fv3r, nmmb, 3drtma tests.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. Please refer to my tests on Hera at /home/Wen.Meng/stmp2:
> 
> ```
> Wen.Meng@hfe09 stmp2$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp   132 Apr 11 18:45 rap_2020072316/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp   132 Apr 11 18:45 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp    61 Apr 11 18:45 rap_2020072316/WRFNAT.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp    60 Apr 11 18:45 post_nmmb_meso_2014120818_Grib2/BGDAWP03.tm00.Grib2.diff
> -rw-r--r-- 1 Wen.Meng stmp    61 Apr 11 18:45 rap_2020072316_pe_test/WRFNAT.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp    60 Apr 11 18:45 post_nmmb_meso_2014120818_Grib2_pe_test/BGDAWP03.tm00.Grib2.diff
> -rw-r--r-- 1 Wen.Meng stmp    56 Apr 11 18:45 hrrr_2020060118_pe_test/WRFTWO.GrbF04.diff
> -rw-r--r-- 1 Wen.Meng stmp    56 Apr 11 18:46 hrrr_2020060118/WRFTWO.GrbF04.diff
> -rw-r--r-- 1 Wen.Meng stmp   370 Apr 11 18:46 fv3r_2023062800/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp   370 Apr 11 18:46 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14010 Apr 11 18:47 rtma_2023040400_pe_test/NATLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14010 Apr 11 18:47 rtma_2023040400/NATLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 13798 Apr 11 18:49 fv3r_2023062800/NATLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 13798 Apr 11 18:49 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  1063 Apr 11 18:49 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  1063 Apr 11 18:49 rtma_2023040400/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  3444 Apr 11 18:53 gfs.20190830/gfs.t00z.master.grb2f006.diff
> -rw-r--r-- 1 Wen.Meng stmp  3444 Apr 11 18:53 gfs.20190830_pe_test/gfs.t00z.master.grb2f006.diff
> ```
> 
> The actual values changes should be in variable "VIS".

Hera and Hercules match your results, Orion however is running into segmentation faults within the hrrr_pe test
`/work2/noaa/epic/nandoam/regression-testing/upp/orion/915/UPP/ci/work-upp-ORION/out.post.hrrr_pe_test`

```
+ srun /work2/noaa/epic/nandoam/regression-testing/upp/orion/915/UPP/ci/..//exec/upp.x
[Orion-25-40:392413:0:392413] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x2b6dc7214004)
[Orion-25-40:392415:0:392415] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x2ad77ee55004)
[Orion-25-40:392417:0:392417] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x2b380ca03004)
```
```
==== backtrace (tid: 392413) ====
 0 0x0000000000033135 ucp_tag_offload_start_rndv()  ???:0
 1 0x0000000000033cd1 ucp_address_unpack()  ???:0
 2 0x0000000000015474 ucp_ep_create()  ???:0
 3 0x00000000000078db mlx_av_insert()  mlx_av.c:0
 4 0x00000000006c2b75 MPIDI_OFI_mpi_init_hook()  /build/impi/_buildspace/release/../../src/mpid/ch4/netmod/ofi/ofi_init.c:1970
 5 0x00000000002109dd MPID_Init()  /build/impi/_buildspace/release/../../src/mpid/ch4/src/ch4_init.c:1307
 6 0x000000000052a1a3 MPIR_Init_thread()  /build/impi/_buildspace/release/../../src/mpi/init/initthread.c:142
 7 0x000000000052971b PMPI_Init()  /build/impi/_buildspace/release/../../src/mpi/init/init.c:140
 8 0x00000000000ec85b pmpi_init_()  /build/impi/_buildspace/release/../../src/binding/fortran/mpif_h/initf.c:275
 9 0x00000000005ec8f0 setup_servers_()  /work2/noaa/epic/nandoam/regression-testing/upp/orion/915/UPP/sorc/ncep_post.fd/SETUP_SERVERS.f:46
10 0x00000000004bc28a MAIN__()  /work2/noaa/epic/nandoam/regression-testing/upp/orion/915/UPP/sorc/ncep_post.fd/WRFPOST.F:177
11 0x0000000000413ed2 main()  ???:0
12 0x0000000000022495 __libc_start_main()  ???:0
13 0x0000000000413de9 _start()  ???:0
```

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA My tests have been successfully completed on Orion at /home/wmeng/stmp2. I am not sure if there was a system issue during your testing. Or you can look into my test configurations /home/wmeng/ovp/ncep_post/post_regression_test_new/jobs and compare with your configurations.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Since my UPP RTs on Orion are consistent with these on Hera and WCOSS2, we could merge this PR first, and you may debug the test failing later. Please let me know if this approach works for you.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA Since my UPP RTs on Orion are consistent with these on Hera and WCOSS2, we could merge this PR first, and you may debug the test failing later. Please let me know if this approach works for you.

Sure thing, I'll compare our output and run scripts for the hrrr pe test case, I'll create an issue if the failure persists. Please expand read permissions for `/home/wmeng/ovp/ncep_post/post_regression_test_new/jobs`

**Review by FernandoAndrade-NOAA — APPROVED** [review]
Temporarily skipping the hrrr_pe_test case, segmentation faults occurred only on Orion. The base hrrr test case did not run into these issues on Orion. Other test case changes are as expected.

**Comment by WenMeng-NOAA** [comment]
> Temporarily skipping the hrrr_pe_test case, segmentation faults occurred only on Orion. The base hrrr test case did not run into these issues on Orion. Other test case changes are as expected.

@FernandoAndrade-NOAA modified permission of  /home/wmeng/ovp/ncep_post/post_regression_test_new. Please try again.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging. There will be baseline updates in gfs, nmmb, rap, hrrr, fv3r and 3drtma with this PR.

**Pull request merged**
