### PR TITLE
Bug fix for QPFARI and QPFFFG encoding in RRFS

### LINKED ISSUE #960: Update UPP wcoss2 model to use recently implemented operational G2tmpl lib v1.12.0
Following Wen's directions, updated UPP wcoss2 module to remove use of her temporarily installed g2tmpl lib now that
this lib is installed on wcoss2 by NCO

### LINKED ISSUE #962: Bug in prob values denoted in QPFARI and QPFFFG fields in RRFS
The prob values showing up for QPFARI and QPFFFG fields in RRFS are not reproducible.  Subsequent runs lead to different values as shown here:

< 772:4824832913:vt=2024022023:surface:11-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat
=1 parm=197:prob >1:prob fcst 72/110
---
> 772:4824832913:vt=2024022023:surface:11-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat
=1 parm=197:prob >1:prob fcst 96/110
6177c6177
< 773:4824833141:vt=2024022023:surface:0-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat=
1 parm=197:prob >1:prob fcst 72/110
---
> 773:4824833141:vt=2024022023:surface:0-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat=
1 parm=197:prob >1:prob fcst 96/110

### LINKED ISSUE #969: Bug in calculation of vertically summed smoke emissions
Current UPP is not correct for computation of vertically summed smoke emissions.  We need to do a simple sum of vertical levels rather than a vertical integration as is done, for example, for PWAT and vertically integrated smoke.

### LINKED ISSUE #970: Bug in labeling of run total accumulated fields in sub-hourly output.
Currently sub-hourly run-total accumulated precipitation fields have wrong time labels.

### LINKED ISSUE #971: 1-h avg MASSDEN fields in RRFS need to be PM2.5 and PM10
We need 1-h average PM2.5 and PM10 from RRFS to facilitate comparison with surface observations.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
The main changes are:

- Bug fix in prob values denoted in QPFARI and QPFFG
- Bug fix in labeling of run total accumulated fields in sub-hourly 
- Bug fix in calculation of vertically summed smoke emissions
- Change the path of g2tmpl/1.12.0 on WCOSS2 to the prod side
- Change 1-h averaged MASSDEN to PM2.5 and PM10

prob_num and tot_num_prob were not set in grib2_module.f, resulting in seemingly random values showing up for the new GRIB2 records QPFARI and QPFFFG, as noted by Hui-Ya Chuang:

< 772:4824832913:vt=2024022023:surface:11-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat
=1 parm=197:prob >1:prob fcst 72/110
772:4824832913:vt=2024022023:surface:11-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat
=1 parm=197:prob >1:prob fcst 96/110
6177c6177
< 773:4824833141:vt=2024022023:surface:0-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat=
1 parm=197:prob >1:prob fcst 72/110

773:4824833141:vt=2024022023:surface:0-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat=
1 parm=197:prob >1:prob fcst 96/110

This small change fixes the issue, and should lead to bitwise identical results.

The change was tested for the RRFS_NA_3km system on Hera.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you sync your branch with the latest commit of the branch 'release/rrfs_v1'?

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA welcome back!  I hope your family are well.  

Just to clarify, yes, these changes are needed for RRFSv1.  

Smoke/dust folks have requested one more small change which I hope to include in this PR if that's OK.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA welcome back! I hope your family are well.
> 
> Just to clarify, yes, these changes are needed for RRFSv1.
> 
> Smoke/dust folks have requested one more small change which I hope to include in this PR if that's OK.

@EricJames-NOAA The modification in smoke/dust product calculation is fine with me unless @MatthewPyle-NOAA has concerns.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you take a look at my test results for the sub-hourly case at /home/Wen.Meng/stmp2/rrfs_2024050203 and let me know if there are any inconsistencies with your testing?

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA With the fix in  grib2 meta data,  the QPFARI and QPFFFG in rrfs PRSLEV dataset are encoded as:
```
772:714248470:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=197:surface:9-10 hour acc fcst:prob >1:prob fcst 0/1
773:714248695:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=197:surface:10-10 hour acc fcst:prob >1:prob fcst 0/1
774:714248920:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:9-10 hour acc fcst:prob >2:prob fcst 0/1
775:714249145:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:10-10 hour acc fcst:prob >2:prob fcst 0/1
776:714249370:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:9-10 hour acc fcst:prob >5:prob fcst 0/1
777:714249595:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:10-10 hour acc fcst:prob >5:prob fcst 0/1
778:714249820:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:9-10 hour acc fcst:prob >10:prob fcst 0/1
779:714250045:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:10-10 hour acc fcst:prob >10:prob fcst 0/1
780:714250270:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:9-10 hour acc fcst:prob >100:prob fcst 0/1
781:714250495:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:10-10 hour acc fcst:prob >100:prob fcst 0/1

```
Please confirm the above changes.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you also combine another change in your PR? 
Update g2tmpl/1.12.0 location on WCOSS2 which was officially installed at the prod side:
in UPP/modulefiles/wcoss2.lua, remove line 48, and 49:
```
prepend_path("MODULEPATH"," /u/wen.meng/noscrub/ncep_post/g2tmpl/libs/modulefiles/compiler/intel/19.1.3.304")
load(pathJoin("g2tmpl", g2tmpl_ver))
```

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Can you take a look at my test results for the sub-hourly case at /home/Wen.Meng/stmp2/rrfs_2024050203 and let me know if there are any inconsistencies with your testing?

@WenMeng-NOAA my tests were on Jet on /lfs4 which is not accessible at the moment.  I am recreating my tests on Hera.

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA With the fix in grib2 meta data, the QPFARI and QPFFFG in rrfs PRSLEV dataset are encoded as:
> 
> ```
> 772:714248470:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=197:surface:9-10 hour acc fcst:prob >1:prob fcst 0/1
> 773:714248695:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=197:surface:10-10 hour acc fcst:prob >1:prob fcst 0/1
> 774:714248920:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:9-10 hour acc fcst:prob >2:prob fcst 0/1
> 775:714249145:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:10-10 hour acc fcst:prob >2:prob fcst 0/1
> 776:714249370:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:9-10 hour acc fcst:prob >5:prob fcst 0/1
> 777:714249595:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:10-10 hour acc fcst:prob >5:prob fcst 0/1
> 778:714249820:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:9-10 hour acc fcst:prob >10:prob fcst 0/1
> 779:714250045:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:10-10 hour acc fcst:prob >10:prob fcst 0/1
> 780:714250270:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:9-10 hour acc fcst:prob >100:prob fcst 0/1
> 781:714250495:d=2023062800:var discipline=1 center=7 local_table=1 parmcat=1 parm=196:surface:10-10 hour acc fcst:prob >100:prob fcst 0/1
> ```
> 
> Please confirm the above changes.

@WenMeng-NOAA those changes look correct and consistent with my results.

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA your results are consistent with mine.  I added the smoke change requested by NCEP, so this PR is ready from my perspective.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA The 1-h averaged PM2.5 and PM10 in PRSLEV dataset are labeled as:
 ```
751:704042206:d=2023062800:MASSDEN:8 m above ground:10-11 hour ave fcst:aerosol=Missing:aerosol_size <2.5e-06
752:704280574:d=2023062800:MASSDEN:8 m above ground:10-11 hour ave fcst:aerosol=Missing:aerosol_size <1e-05

```
Please confirm.

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA The 1-h averaged PM2.5 and PM10 in PRSLEV dataset are labeled as:
> 
> ```
> 751:704042206:d=2023062800:MASSDEN:8 m above ground:10-11 hour ave fcst:aerosol=Missing:aerosol_size <2.5e-06
> 752:704280574:d=2023062800:MASSDEN:8 m above ground:10-11 hour ave fcst:aerosol=Missing:aerosol_size <1e-05
> ```
> 
> Please confirm.

@WenMeng-NOAA yes, that is correct.  We have changed these fields to be PM2.5 and PM10 (including both smoke and dust), so I changed the aerosol type to "Missing".  The size categorization is correct.

**Comment by WenMeng-NOAA** [comment]
> > @EricJames-NOAA The 1-h averaged PM2.5 and PM10 in PRSLEV dataset are labeled as:
> > ```
> > 751:704042206:d=2023062800:MASSDEN:8 m above ground:10-11 hour ave fcst:aerosol=Missing:aerosol_size <2.5e-06
> > 752:704280574:d=2023062800:MASSDEN:8 m above ground:10-11 hour ave fcst:aerosol=Missing:aerosol_size <1e-05
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please confirm.
> 
> @WenMeng-NOAA yes, that is correct. We have changed these fields to be PM2.5 and PM10 (including both smoke and dust), so I changed the aerosol type to "Missing". The size categorization is correct.

@EricJames-NOAA Thanks for clarifying.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
