### PR TITLE
release/public-v2: Updated documentation for SRW release

### PR DESCRIPTION
**Pull request by mkavulich**
- Fixed some broken links in AddNewVariable.rst
- Updated the example output for adding a new variable for the latest version of the code
- Minor spelling, wording, and formatting changes

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
This is a documentation update only and ok with me as long as the documentation gurus are happy with the changes.

**Comment by WenMeng-NOAA** [comment]
@mkavulich Eventually DTC will bring these updated documents from release/public-v2 back to  develop branch, right?

**Comment by mkavulich** [comment]
@WenMeng-NOAA Yes, we should bring the release branch changes back to develop eventually. I have to do this for release branch changes in a few different repositories so I will work on it in the next week or two.

**Comment by WenMeng-NOAA** [comment]
@mkavulich Thanks!

**Pull request merged**
