### PR TITLE
Updates to support UPP use with MPAS

### LINKED ISSUE #1008: New UPP branch for MPAS-related development?
GSL staff are beginning to modify UPP codes to support MPAS runs.  For now, the "INITPOST.F" interface is being used, since the netCDF array names (from MPASSIT) are largely identical to those in HRRR (WRF-ARW).

The first UPP PRs for MPAS work will likely be ready in the days ahead.  @HuiyaChuang-NOAA suggested that a new UPP branch may be helpful for this code development.

### PR DESCRIPTION
**Pull request by jaymes-kenyon**
This PR contains the initial modifications to support UPP functionality with MPAS (specifically, MPASSIT-generated netCDF history files).  A new`INITPOST_MPAS.F` interface is proposed, copied from `INITPOST.F`.  Several static control files are also included; these control files are currently in use by GSL in its real-time HFIP and RRFS-MPAS runs.

This PR addresses issue #1008.  Thanks to @SamuelTrahanNOAA for the help in making changes to `getVariable.f` and `getIVariableN.f`.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon Do you have the sample MPAS model outputs for my UPP standalone test?

**Comment by jaymes-kenyon** [comment]
@WenMeng-NOAA — Here's a sample netCDF file on Hera; it's a 12-h forecast from the RRFS-MPAS prototype configuration (3-km CONUS):
`/scratch2/BMC/wrfruc/kenyon/sample/rrfs_mpas/2024082100/MPAS-A_out.2024-08-21_12.00.00.nc`

Here's an example "itag" file for testing (note the MODELNAME, SUBMODELNAME, and fileNameFlat):
```
&model_inputs
fileName='/mnt/lfs4/BMC/wrfruc/kenyon/mpas_upp/rrfs/2024082100/MPAS-A_out.2024-08-21_12.00.00.nc'
fileNameFlux='/mnt/lfs4/BMC/wrfruc/kenyon/mpas_upp/rrfs/2024082100/MPAS-A_out.2024-08-21_12.00.00.nc'
IOFORM='netcdfpara'
grib='grib2'
DateStr='2024-08-21_12:00:00'
MODELNAME='RAPR'
SUBMODELNAME='MPAS'
fileNameFlat='postxconfig-NT-rrfs_mpas.txt'
/
```
Thanks for the testing!

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon Thanks for sharing with me your itag. My test results are at /home/Wen.Meng/stmp2/mpas_2024082112 on Hera. Please validate and let me if you see issues.
PS. I would suggest to remove the line "fileNameFlat=..." in tag. The 'fileNameFlat' input is not needed for ingesting WRFIO model output, like rap/hrrr/mpas.

**Comment by jaymes-kenyon** [comment]
@WenMeng-NOAA — Thanks!  Your test results look good.

Thanks also for the clarification regarding the use of "fileNameFlat" within the itag file (for WRFIO applications).  I see now that WRFPOST.F specifies a default name (fileNameFlat='postxconfig-NT.txt').  So, the chosen flat file just needs to be linked within the run directory as this default name.

Another MPAS-related PR will likely be ready soon, but I wanted to get this PR done first.  Thanks again!

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon Thanks for verifying. In my test, I didn't add the entry "fileNameFlat" in itag. Instead, I copied file 'postxconfig-NT-rrfs_mpas.txt" into the run directory and rename as 'postxconfig-NT.txt'.
BTW we will proceed your PR to the merging process.

**Comment by WenMeng-NOAA** [comment]
The github workflow failed at [GCC Linux build](https://github.com/NOAA-EMC/UPP/actions/runs/10507939202/job/29110782178?pr=1018#step:4:1566). Do you know the root cause? @SamuelTrahanNOAA @AlexanderRichert-NOAA @jaymes-kenyon

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on R&D machines. There should be no baseline updates with this PR.

**Comment by jaymes-kenyon** [comment]
@WenMeng-NOAA — It seems to be failing in `getVariable.f` and `getIVariableN.f` (both changed in this PR) due to "undefined reference to **ext_ncd_get_var_ti_real_** ".  

Specifically, `getVariable.f` and `getIVariableN.f` now use calls to **ext_ncd_get_var_ti_real**, which is a subroutine within NCEPlibs-wrf_io (https://github.com/NOAA-EMC/NCEPLIBS-wrf_io).  Is this library available in the automatic testing setup?

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon I would think so. Let's wait for comments from @AlexanderRichert-NOAA and @SamuelTrahanNOAA

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been successfully completed on WCOSS2 without baseline changes.

**Comment by FernandoAndrade-NOAA** [comment]
Please ignore the Jenkins failures, I will run manually.

**Comment by FernandoAndrade-NOAA** [comment]
RTs showed no changes across Hera, Hercules, and Orion. @WenMeng-NOAA I'm assuming we will be waiting for additional comments on the CI failures before the merge.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA I successfully built an UPP executable with GNU compiler on Hera (See /home/Wen.Meng/stmp2/jaymes/UPP/tests/compile_upp_guc.log). I would think the CI workflow should be updated with this PR. Since we have completed the UPP RTs on WCOSS2 and R&D machines, we could skip this CI issue and address it later. Please let me know your thoughts.

**Comment by AlexanderRichert-NOAA** [comment]
This appears to be a problem with the CMake configuration, and I would strongly recommend against merging as is. Specifically, the modifications to getIVariableN.f & getVariable.f use subroutines from wrf_io, but wrf_io isn't being found because BUILD_WITH_WRFIO is not enabled. Note that in [CMakeLists.txt, lines 156-157](https://github.com/jaymes-kenyon/UPP/blob/2b7fd82f2e8c6dc723b511b6d8d994b0d0e468c9/sorc/ncep_post.fd/CMakeLists.txt#L156-L157), the inclusion of getIVariableN.f and getVariable.f is unconditional (specifically, it doesn't depend on BUILD_WITH_WRFIO being enabled). So I imagine you'll want to either make it conditional, or always use wrf_io.

**Comment by SamuelTrahanNOAA** [comment]
What happens if the CMakeLists change is reverted?

We could explicitly enable the build with wrfio when using MPAS.

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA @SamuelTrahanNOAA Thanks for comments on narrowing down the checklist.  In the [CMakelist.txt](https://github.com/NOAA-EMC/UPP/blob/develop/CMakeLists.txt#L18), the default setting is "build without WRF-IO lib. @jaymes-kenyon Could you change "OFF" to "ON" in that line in your branch to see if it resolve the CI issue?

**Comment by SamuelTrahanNOAA** [comment]
I found the problem: `io_int_stubs.f` lacks `ext_ncd_get_var_ti_real`

The correct fix is to add the missing stub.

EDIT: I mistyped the subroutine name. It ends with _real, not _integer.

**Comment by SamuelTrahanNOAA** [comment]
@jaymes-kenyon - Please merge this pull request to your branch:

* https://github.com/jaymes-kenyon/UPP/pull/1

It'll add the missing stub so your branch can compile without the wrf-io library.

**Comment by SamuelTrahanNOAA** [comment]
All three github tests passed. It seems the fixed worked. Do you want to retest other platforms? Or are the github tests sufficient for a fix of adding one stub?

**Comment by WenMeng-NOAA** [comment]
> All three github tests passed. It seems the fixed worked. Do you want to retest other platforms? Or are the github tests sufficient for a fix of adding one stub?

@SamuelTrahanNOAA Thanks for the fix. The UPP RTs are conducted with WRF_IO enabled. I will rerun the RTs on WCOSS2 to confirm.

**Comment by WenMeng-NOAA** [comment]
Re-ran the UPP RTs on WCOSS2. No baseline update is needed.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Please approval this PR for merging process.

**Review by WenMeng-NOAA — APPROVED** [review]

**Review by SamuelTrahanNOAA — APPROVED** [review]
These code changes have the Official Sam Seal of Approval: 🦭👍

Keep up the good job, everyone!

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
