### PR TITLE
UPP refactor phase 2 from Bo Cui

### LINKED ISSUE #235: Updates with the UPP refactor phase 2 merge from Bo Cui
Update the branch develop with the UPP refactor phase 2 merge from Bo Cui.
The changes are included:
1.  Add "implicit none" statements
2.  Modernize inequality statements, change the relational operators from Fortran 77 to 90, e.g. "GT" into ">"
The Pull request #233 was submitted.

### PR DESCRIPTION
**Pull request by BoCui-NOAA**
UPP Refactor phase 2 merge:

1. add "implicit none" statements

2. Modernize inequality statements, change the relational operators from Fortran 77 to 90.

### CODE REVIEW

**Review by mkavulich — APPROVED** [review]
Looks straightforward to me :+1:

I was originally going to suggest skipping the changes in the already-commented lines but I think it's better to do a future commit removing unnecessarily commented code blocks.

**Review by JesseMeng-NOAA — APPROVED** [review]

**Comment by BoCui-NOAA** [comment]
@WenMeng-NOAA Wen, should I resolve the conflicts in file sorc/ncep_post.fd/CALRAD_WCLOUD_newcrtm.f on Github directly? or I made modifications on local machine and then commit it?  

Bo

**Comment by WenMeng-NOAA** [comment]
@BoCui-NOAA Did you sync your branch with the latest changes from upstream/develop?

**Comment by BoCui-NOAA** [comment]
@WenMeng-NOAA Wen, I already sync my branch from upstream/develop, new changes for file CALRAD_WCLOUD_newcrtm.f was committed.

Bo

**Comment by WenMeng-NOAA** [comment]
@BoCui-NOAA The conflicting is still here. It looks to me you add the last upstream/develop changes as your development.

**Comment by WenMeng-NOAA** [comment]
@BoCui-NOAA I don't see the PR #230 in the commit log of your feature branch.

**Comment by WenMeng-NOAA** [comment]
@BoCui-NOAA Now your branch looks good to me.

**Review by JesseMeng-NOAA — APPROVED** [review]

**Review by JesseMeng-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The regression tests were conducted on WCOSS Dell, Cray and NOAA R&D machine Hera. No changed results were found. This PR is ready for merging.

**Pull request merged**
