### PR TITLE
UPP control file changes for HAFS V1

### LINKED ISSUE #612: UPP control file changes for HAFS
- remove hafs.xml and hafs.txt, add hafs_sat.xml and hafs_sat.txt

- add AVE_CPRAT, MAXUVV, MAXDVV, GUST, MXUPHL(0-3km,2-5km) in hafs_nosat.xml and hafs_nosat.txt

- replace INST_PRATE to AVE_PRATE in hafs_nosat.xml and hafs_nosat.txt

### PR DESCRIPTION
**Pull request by LinZhu-NOAA**
- remove hafs.xml and hafs.txt, add hafs_sat.xml and hafs_sat.txt

- add AVE_CPRAT, MAXUVV, MAXDVV, GUST, MXUPHL(0-3km,2-5km) in hafs_nosat.xml and hafs_nosat.txt

- replace INST_PRATE to AVE_PRATE in hafs_nosat.xml and hafs_nosat.txt

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@LinZhu-NOAA Somehow, the control files postcntrl_hafs_nosat.xml and postxconfig-NT-hafs_nosat.txt are not consistent in your branch.  The fields MAXUVV and MAXDVV are missing in your postxconfig-NT-hafs_nosat.txt. Please refer the postxconfig-NT-hafs_nosat.txt from my test at /u/wen.meng/ptmp/zhu/UPP/parm on Cactus.

**Comment by LinZhu-NOAA** [comment]
@WenMeng-NOAA The MAXUVV and MAXDVV are added in postxconfig-NT-hafs_nosat.txt. Thanks.

**Comment by WenMeng-NOAA** [comment]
@LinZhu-NOAA My test for hafs is at /u/wen.meng/ptmp/fv3hafs_2022092800 on Cactus. Please let me know if you see any differences with your test.

**Comment by LinZhu-NOAA** [comment]
@WenMeng-NOAA The grib2 file looks okay to me. Thanks.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on WCOSS2, Hera and Orion. The baseline of hafs will be recreated with this PR.

**Pull request merged**
