### PR TITLE
Reduce the printouts for GEFS processing.

### LINKED ISSUE #1074: Reduce "GEFS" prints to log
In GEFS regression test, lines like these
```
 820:  GEFS env var            0           0           0
 820:  Processing for GEFS and default setting is tmpl4_1 and tmpl4_11
 820:  After g2sec1 call we need to set listsec1(2) =            2
 820:  After g2sec1 call we need to set listsec1(13) =            1
```
are printed over tasks and times and double the size of the log file.

It looks like the number of these lines could be reduced towards keeping the log more readable.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
This PR addresses issue #1074.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@NickSzapiro-NOAA Please take a look at the runtime log 'outpost_2023080309' at /home/Wen.Meng/stmp2/post_gefs_2023080300 on Hera.

**Review by NickSzapiro-NOAA — APPROVED** [review]

**Comment by NickSzapiro-NOAA** [comment]
Thank you!! @WenMeng-NOAA

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA You may start the UPP RTs on R&D machines. There should be baseline changes with this PR.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2 with no baseline changes.

**Review by gspetro-NOAA — APPROVED** [review]
RTs completed on Hera, Orion, and Hercules with no baseline changes.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
