### PR TITLE
Updates to the GSL exp1 ceiling diagnostic

### LINKED ISSUE #944: RRFS:  Update the exp1 ceiling diagnostic
Based on verification results from RRFS retrospective tests, the RRFS "exp1" (experimental-1) ceiling diagnostic should be updated in UPP.  These updates should produce improved ceiling fields with this diagnostic, particularly at LIFR thresholds (< 500 ft AGL).  This issue can be assigned to @jaymes-kenyon

### PR DESCRIPTION
**Pull request by jaymes-kenyon**
[Addresses issue #944]

This updates the GSL "exp1" (experimental) ceiling diagnostic for possible use in RRFSv1.  Recent RRFS retrospective tests with this code have produced improved verification statistics relative to the existing "exp1" code.  In particular, this update accomplishes the following:

1) Reduces the threshold cloud fraction used to detect a ceiling, from 0.50 (current) to 0.41 (new).

2) Revises the code to detect shallow fog, and makes this code more readable / understandable.  Any shallow fog that is detected will **_not_** yield a very low ceiling.

Testing of this code has been successful on Hera in a RRFS case (CONUS domain).

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon My UPP RTs indicate the impact only in 'CEIL' PRSLEV dataset of RRFS test as
827:761040843:CEIL:cloud ceiling:rpn_corr=0.975146:rpn_rms=1017.83
I would think that is expected change. Please validate my test at /home/Wen.Meng/stmp2/fv3r_2023062800 on Hera.

**Comment by jaymes-kenyon** [comment]
@WenMeng-NOAA:  Thanks for the test!  This is the expected change—looks good!

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA: Thanks for the test! This is the expected change—looks good!

@jaymes-kenyon Thanks !

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. Please refer to my testing at  /home/Wen.Meng/stmp2 on Hera:
```
Wen.Meng@hfe07 stmp2$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp   75 May  2 12:50 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp  541 May  2 12:52 fv3r_2023062800/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 1009 May  2 12:52 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  541 May  2 12:52 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 1009 May  2 12:52 rtma_2023040400/PRSLEV00.tm00.diff
```

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have completed on WCOSS2. The baselines for fv3r and 3drtma will be recreated with this PR.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. Please refer to my testing at /home/Wen.Meng/stmp2 on Hera:
> 
> ```
> Wen.Meng@hfe07 stmp2$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp   75 May  2 12:50 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp  541 May  2 12:52 fv3r_2023062800/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 1009 May  2 12:52 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  541 May  2 12:52 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 1009 May  2 12:52 rtma_2023040400/PRSLEV00.tm00.diff
> ```

Logs pushed up. RTs across Hera, Hercules, and Orion match with your results.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
