### PR TITLE
Update parm/makefile and UPP WAFS control files in plain text

### LINKED ISSUE #1024: WAFS control files in plain text need to be re-generated
WAFS control files in plain text failed to work at run time. It turned out they need to be re-generated and updated.

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
Update UPP WAFS control files in plain text
Add a list of WAFS control files to parm/makefile

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA Could you recreate gefs-wafs control flat file under par/gefs?

**Comment by YaliMao-NOAA** [comment]
@WenMeng-NOAA Just updated the GEFS wafs control file

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on R&D machines. There should be no baseline update with this PR.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2 without baseline change.

**Review by FernandoAndrade-NOAA — APPROVED** [review]
No changes in RT results across machines.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
