### PR TITLE
Update documentation for variables in CALGUST.f and CALHEL.f

### PR DESCRIPTION
**Pull request by gspetro-NOAA**
This PR provides a definition for the LPBL and ZPBL variables in CALGUST.f
It also corrects a typo in CALHEL.f that generated a warning (DPTH --> should be DEPTH). 

This partially addresses Issue #392 .

### CODE REVIEW

**Review by fossell — APPROVED** [review]
Changes look good to me. Documentation updates only, no change to code.

**Comment by fossell** [comment]
@gspetro-NOAA - Looks good to me. Please wait for @WenMeng-NOAA to review and approve and give the ago ahead for merging.

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA Your PR will be the next one being processed. Can you make it up to date with develop branch? The syncing procedures can be found at
https://github.com/NOAA-EMC/UPP/wiki/UPP-Code-Development#update-your-branch-at-your-fork-with-branch-develop-at-authoritative-repository

**Comment by gspetro-NOAA** [comment]
Done! :) Let me know if you need anything else.
I believe I will need to issue a PR to the gh-pages branch with the updated
html files once this is merged, so keep an eye out for that.

Best,
Gillian

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on WCOSS2. No baseline change is needed with this PR. This PR is ready for merging.

**Pull request merged**
