### PR TITLE
Bug fixes in UPP

### LINKED ISSUE #769: Correct mismatched GRIB IDs in SURFCE.f
There are some mismatched IDs in encoding grib2 in SURFCE.f (line 4361 - 4498). An example at
https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/SURFCE.f#L4361
 IF (IGET(526)>0.) THEN  --    fld_info(cfld)%ifld=IAVBLFLD(IGET(518))

There are following mismatched IDs:
526 -- 518
527 -- 519
528 -- 520
529 -- 521
530 -- 522

### LINKED ISSUE #796: Update for using 3D radar reflectivity from model output for GFS V17
The GFS V17 model with Thompson MP will output 3d radar. The change  is needed in UPP for assigning 3D radar from model output instead of calculation in UPP.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main changes are:

- Fix the mis-matched UPP IDs in writing data blocks
- Assigning 3D radar reflectivity read from model instead of calculation in UPP for GFS V17

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you review the changes in SURFCE.f?

**Comment by WenMeng-NOAA** [comment]
@JongilHan66 Can you review the changes in MDLFLD.f for GFS V17 radar reflectivity?

**Review by JongilHan66 — APPROVED** [review]
The changes in MDLFLD.f for 3D radar reflectivity from model when GFS use Thmopson MP look good.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. There should be no baseline changes with this PR.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 without changed results. No changes from the GFS testing due to 3D radar reflectivity not included in the baseline of gfs model output files.

**Comment by FernandoAndrade-NOAA** [comment]
Hera, Orion, and Hercules UPP RTs have completed without changes to results.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
