### PR TITLE
Add hourly averaged smoke PM2.5 and dust PM10

### LINKED ISSUE #907: Enable output of time-averaged smoke and dust in RRFS
We need to produce output of time-averaged smoke and dust in RRFS to facilitate comparison with other models and air quality observations.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
Air quality users have requested hourly averaged smoke PM2.5 and dust PM10 (fine dust + coarse dust) for comparison with air quality observations.  This PR enables these fields to be output in RRFS.

The code update requires the addition of PDS template 4.46 in NCEPLIBS-g2tmpl, for which I have opened a PR:

https://github.com/NOAA-EMC/NCEPLIBS-g2tmpl/pull/115

The code has been tested for the real-time RRFS_NA_3km system on Jet.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Do you have RRFS model data files in netcdf  which include new output variables on Hera?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Do you have RRFS model data files in netcdf which include new output variables on Hera?

Yes, I have some history files here on Hera:

/scratch1/BMC/wrfruc/ejames/wen_pm_avg/

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you sync your branch with the latest UPP develop?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Can you sync your branch with the latest UPP develop?

I synced it!  Thanks for working on these PRs.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Could you also update s4.lua with g2tmpl/1.12.0?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Could you also update s4.lua with g2tmpl/1.12.0?

I don't have access to S4.  Could you share the path?

**Comment by WenMeng-NOAA** [comment]
> > @EricJames-NOAA Could you also update s4.lua with g2tmpl/1.12.0?
> 
> I don't have access to S4. Could you share the path?

You might update s4.lua as:
```
From 
prepend_path("MODULEPATH", "/data/prod/jedi/spack-stack/spack-stack-1.6.0/envs/unified-env/install/modulefiles/Core")
into
prepend_path("MODULEPATH", "/data/prod/jedi/spack-stack/spack-stack-1.6.0/envs/upp-addon-env/install/modulefiles/Core")
```

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Please sync your branch.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Could you add the following changes in modulefiles/wcoss2.lua for g2tmpl/1.12.0:
```
wen.meng@clogin01 modulefiles$ git diff  wcoss2.lua
diff --git a/modulefiles/wcoss2.lua b/modulefiles/wcoss2.lua
index eccb1d6d..539d8581 100644
--- a/modulefiles/wcoss2.lua
+++ b/modulefiles/wcoss2.lua
@@ -24,7 +24,7 @@ load(pathJoin("libpng", libpng_ver))
 load(pathJoin("zlib", zlib_ver))
 
 g2_ver=os.getenv("g2_ver") or "3.4.5"
-g2tmpl_ver=os.getenv("g2tmpl_ver") or "1.10.2"
+g2tmpl_ver=os.getenv("g2tmpl_ver") or "1.12.0"
 bacio_ver=os.getenv("bacio_ver") or "2.4.1"
 ip_ver=os.getenv("ip_ver") or "3.3.3"
 sp_ver=os.getenv("sp_ver") or "2.3.3"
@@ -45,6 +45,9 @@ load(pathJoin("nemsio", nemsio_ver))
 load(pathJoin("sigio", sigio_ver))
 load(pathJoin("wrf_io", wrf_io_ver))
 
+prepend_path("MODULEPATH"," /u/wen.meng/noscrub/ncep_post/g2tmpl/libs/modulefiles/compiler/intel/19.1.3.304")
+load(pathJoin("g2tmpl", g2tmpl_ver))
+
 setenv("CC","cc")
 setenv("CXX","CC")
 setenv("FC","ftn")
```

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA I updated it...let me know if you see any mistakes!

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA I updated it...let me know if you see any mistakes!

@EricJames-NOAA I tested the UPP building on WCOSS2. It works well. Thanks!

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. For your reference, my RT results are at /home/Wen.Meng/stmp2 on Hera:
```
Wen.Meng@hfe07 stmp2$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp    75 May  8 21:54 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp 16626 May  8 21:56 fv3r_2023062800/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 16626 May  8 21:56 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 17670 May  8 21:56 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 17670 May  8 21:56 rtma_2023040400/PRSLEV00.tm00.diff
```

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2. Baseline updates for fv3r and 3drtma are needed.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Could you bump g2tmpl from 1.10.2 to 1.12.0 at
https://github.com/EricJames-NOAA/UPP/blob/pm_avg/ci/spack.yaml#L14
It might solve the CI failure on github.

**Comment by WenMeng-NOAA** [comment]
The g2tmpl upgrade might make CI failure on github. This issue can be solved later,

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
