### PR TITLE
Unify CONST1 and VISRH in GSD visibility calculation.

### LINKED ISSUE #302: value of CONST1 used for visibility
I would like to suggest trying to migrate to using a value of 3.00 ( -ln(.05) ) more uniformly in the UPP code. This would make visibility calculations more compatible with the METAR definition of visibility. It is my understanding that the instrumentation presently used by METARs utilizes a 5% contrast threshold instead of 2%.

A reference mentioning this is here:

https://www.metoffice.gov.uk/weather/guides/observations/how-we-measure-visibility

Another one is Attachment D in this document (search for Koschmeider):

https://www.icao.int/airnavigation/IMP/Documents/Annex%203%20-%2075.pdf

This references also mentions the 0.05 threshold:

https://www.biral.com/wp-content/uploads/2015/02/Introduction_to_visibility-v2-2.pdf

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Unify CONST1 and VISRH in CALVIS_GSD.f.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were conducted on WCOSS-Dell, WCOSS-Cray and Hera. With the changes applied, the baselines of nmmb, fv3lam will be re-created.

**Review by HuiyaChuang-NOAA — APPROVED** [review]
Looks good.

**Comment by HuiyaChuang-NOAA** [comment]
I will soon email Jacob, Eric, and Fangling to inform them we're ready for visibility unification

**Review by Steve-Albers — COMMENTED** [review]
These changes look good. Please note that CONST1 with the old values can be found in other places, as seen in this search:

https://github.com/NOAA-EMC/EMC_post/search?q=const1

**Pull request merged**
