### PR TITLE
Change grib2 number of ULWRF from NCEP local definition to WMO definition  in fv3lam_rrfs.xml

### LINKED ISSUE #869: Change grib2 name of ULWRF in RRFS products
Per WMO header requirement in FAA grib2 data, ULWRF in RRFS products should use WMO definition number '4' instead of the NCEP definition number '193'.

### PR DESCRIPTION
**Pull request by AndrewBenjamin-NOAA**
In order to use the WMO ID for ULWRF, I have removed <table_info>NCEP</table_info> from fv3lam_rrfs.xml.
This is needed for WMO headers for special FAA grib2 files.

A standalone test was performed on WCOSS2 and can be found here: /lfs/h2/emc/ptmp/andrew.benjamin/post_rrfs_2023062800.65061

Comparing the text files degrib2.ulwrf.test.out with degrib2.ulwrf.rrfsa.out show that removing the table info has the desired effect of using the WMO ID rather than the duplicate ID.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@AndrewBenjamin-NOAA Do you have an UPP issue linking to this PR?

**Comment by WenMeng-NOAA** [comment]
@AndrewBenjamin-NOAA Please sync your branch with the latest UPP develop.

**Comment by AndrewBenjamin-NOAA** [comment]
> @AndrewBenjamin-NOAA Do you have an UPP issue linking to this PR?

@WenMeng-NOAA I do not have a UPP issue with this PR. This is part of a larger effort to no longer use duplicate NCEP local use IDs when official WMO id's have been added to the grib tables. This commit should be the last for products that go out over the SBN. I will do a similar check on all RRFS products currently running in the parallel. Would you like me to open a UPP issues?



> @AndrewBenjamin-NOAA Please sync your branch with the latest UPP develop.

My branch has been synced with the latest UPP develop.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA I do not have a UPP issue with this PR. This is part of a larger effort to no longer use duplicate NCEP local use IDs when official WMO id's have been added to the grib tables. This commit should be the last for products that go out over the SBN. I will do a similar check on all RRFS products currently running in the parallel. Would you like me to open a UPP issues?

@AndrewBenjamin-NOAA Please open a new UPP issue for this PR.

**Comment by AndrewBenjamin-NOAA** [comment]
@WenMeng-NOAA is it possible to reopen issue #826? These changes are directly related to this issue.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2, Hera and Orion. There will be baseline re-creation for fv3r and 3drtma with this PR. This PR is ready for merging.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
