### PR TITLE
icnt value increase with NCO's feedback

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Increase icnt value from 1000 to 1080 in  exglobal_atmos_pmgr.sh with NCO's feedback.

### CODE REVIEW

**Review by KateFriedman-NOAA — APPROVED** [review]
The update to `icnt` looks good and is as discussed between @WenMeng-NOAA and @WeiWei-NCO. Thanks!

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA I plan to cut the new UPP tag as upp_v8.1.2. Please let me know if it works for the global-workflow. Thanks!

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA I plan to cut the new UPP tag as upp_v8.1.2. Please let me know if it works for the global-workflow. Thanks!

That works for global-workflow, thanks! I'll proceed with updating the UPP tag name in global-workflow `feature/ops-wcoss2` and include it in the new tag for NCO. Please confirm once the new UPP `upp_v8.1.2` tag is cut. Thanks!

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA The new tag upp_v8.1.2 was created. Please let me know if you see issues. Thanks!

**Comment by KateFriedman-NOAA** [comment]
> The new tag upp_v8.1.2 was created. Please let me know if you see issues. Thanks!

@WenMeng-NOAA I tested checkout and build of the new tag...no issues. Looks good, thanks for cutting the new tag!

**Pull request merged**
