### PR TITLE
Add options in build script

### LINKED ISSUE #431: Add an option of compiling gtg code in UPP build script
Add an option of compiling gtg code in UPP build script.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main changes are:

- Add command line options in compile_upp.sh for building with gtg code, building with stub wrfio code, turning on cmake verbose, specifying building location.
- Remove legacy GNU make build capability.

### CODE REVIEW

**Review by YaliMao-NOAA — APPROVED** [review]
All look good.
For the future version on WCOSS2, 'module purge' may need to be changed to 'module reset' in tests/compile_upp.sh

**Comment by WenMeng-NOAA** [comment]
> All look good. For the future version on WCOSS2, 'module purge' may need to be changed to 'module reset' in tests/compile_upp.sh

I will do that in my porting UPP develop on WCOSS2. Can you verify that this script is working for you with gtg code included.
Thanks!

**Comment by YaliMao-NOAA** [comment]
> I will do that in my porting UPP develop on WCOSS2. Can you verify that this script is working for you with gtg code included. Thanks!

Yes, I was able to checkout GTG code, and compile UPP GTG successfully with './compile_upp.sh -g'

**Comment by fossell** [comment]
@WenMeng-NOAA - This look ok in general. Right now for public versions we do not use this script anyway, and we do not support WRF or GTG to community so mods here shouldn't be a problem.  We might explore some options to leverage this script for community, but we'll need more time to decide how to support various builds on different platforms to the community, that does not need to hold up this PR though.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA Great, Thanks!

**Review by fossell — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA - This look ok in general. Right now for public versions we do not use this script anyway, and we do not support WRF or GTG to community so mods here shouldn't be a problem. We might explore some options to leverage this script for community, but we'll need more time to decide how to support various builds on different platforms to the community, that does not need to hold up this PR though.

@fossell Thanks for the comments. You are welcome for enhancing the build script to support more platforms and build options.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA Would you consider to add gtg.config.gfs from gtg repository under UPP parm/? It might save a step during gtg product generation.

**Comment by YaliMao-NOAA** [comment]
> 

Since gtg.config.gfs is part of private code, I don't think it's appropriate to copy the one from gtg repository to the one under UPP parm/. I am thinking to make these modifications:
1. Remove parm/gtg.config.gfs
2. In scripts/exgfs_atmos_nceppost.sh, change the line from:
        cp $PARMpost/gtg.config.gfs gtg.config
    to:
        cp $HOMEgfs/sorc/ncep_post.fd/post_gtg.fd/gtg.config.gfs gtg.config

**Comment by WenMeng-NOAA** [comment]
> > 
> 
> Since gtg.config.gfs is part of private code, I don't think it's appropriate to copy the one from gtg repository to the one under UPP parm/. I am thinking to make these modifications:
> 
> 1. Remove parm/gtg.config.gfs
> 2. In scripts/exgfs_atmos_nceppost.sh, change the line from:
>    cp $PARMpost/gtg.config.gfs gtg.config
>    to:
>    cp $HOMEgfs/sorc/ncep_post.fd/post_gtg.fd/gtg.config.gfs gtg.config

@YaliMao-NOAA Your proposal sounds good to me. You may submit in a different PR. Thanks!

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were conducted on WCOSS-Cray, WCOSS-Dell and Hera. No changed results were found. This PR is ready for merging.

**Pull request merged**
