### PR TITLE
update gtg code revision to v.4.16.3

### LINKED ISSUE #952: Solve the RRFS GTG difference between NCAR and EMC run
There are differences of RRFS GTG between NCAR and EMC.
It turned out the vertical orientations of RRFS in UPP and  in NCAR's algorithm are different.

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
To solve the RRFS GTG difference between NCAR and EMC run, for issue #952

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA From my UPP gtg testing, the impact from your PR is in RRFS dataset 'AVIATI'. My test is at /u/wen.meng/ptmp/post_rrfs_2023060614-new on Cactus. Please validate.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Orion and Hera. No baseline update is expected in this PR.

**Comment by YaliMao-NOAA** [comment]
> @YaliMao-NOAA From my UPP gtg testing, the impact from your PR is in RRFS dataset 'AVIATI'. My test is at /u/wen.meng/ptmp/post_rrfs_2023060614-new on Cactus. Please validate.

The RRFS test result looks good to me. Thank you!

**Comment by FernandoAndrade-NOAA** [comment]
Hera is back up after today's maintenance, running RTs now.

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA RTs completed and logs committed for all machines, no changes in results.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
