### PR TITLE
Bug fix of reading sea salt scavenging and sync changes from inline post interface

### LINKED ISSUE #726: Sea Salt Scavenging Flux Input
In lines 3501-3511 of INITPOST_NETCDF.f, seas1wtc is getting assigned to VarName in each line. In other similar code blocks, seas1wtc would be assigned when K == 1, seas2wtc where K == 2, and so on. Currently, the code reads:

```
! retrieve seasalt scavenging fluxes
      do K = 1, nbin_ss
       if ( K == 1) VarName='seas1wtc'
       if ( K == 2) VarName='seas1wtc'
       if ( K == 3) VarName='seas1wtc'
       if ( K == 4) VarName='seas1wtc'
       if ( K == 5) VarName='seas1wtc'
      call read_netcdf_2d_para(ncid2d,ista,ista_2l,iend,iend_2u,jsta,jsta_2l,jend,jend_2u,&
      spval,VarName,chem_2d)
      sssv(1:im,jsta_2l:jend_2u,K)=chem_2d(1:im,jsta_2l:jend_2u)
       enddo
```

It seems like it should be:
```
! retrieve seasalt scavenging fluxes
      do K = 1, nbin_ss
       if ( K == 1) VarName='seas1wtc'
       if ( K == 2) VarName='seas2wtc'
       if ( K == 3) VarName='seas3wtc'
       if ( K == 4) VarName='seas4wtc'
       if ( K == 5) VarName='seas5wtc'
      call read_netcdf_2d_para(ncid2d,ista,ista_2l,iend,iend_2u,jsta,jsta_2l,jend,jend_2u,&
      spval,VarName,chem_2d)
      sssv(1:im,jsta_2l:jend_2u,K)=chem_2d(1:im,jsta_2l:jend_2u)
       enddo
```

Thanks to @hertneky for noticing this! :)

### LINKED ISSUE #727: Modification of sndepac calculation
Sync the updates of sndepac calculation from inline post interface to the offline post interface.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main updates in offline post interface:

- Bug fix of reading seaswtc 
- Sync the changes of sndepac calculation from inline post interface

### CODE REVIEW

**Review by zhanglikate — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Can you conduct the UPP RT tests on Hera and Orion. You might expect changed results from 3DRTMA testing.

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests are completed on WCOSS2. There are changed results of ASNOW from 3DRTMA as:
```
722:656007324:ASNOW:surface:rpn_corr=0.661982:rpn_rms=4.55196e-05
```

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA UPP RTs finished on Hera and Orion with changes in 3drtma in the following including the expected change:
```
39:38622976:REFZR:entire atmosphere (considered as a single layer):rpn_corr=-nan:rpn_rms=undefined
40:38861307:REFZI:entire atmosphere (considered as a single layer):rpn_corr=-nan:rpn_rms=undefined
49:49740509:PBLREG:surface:rpn_corr=-nan:rpn_rms=undefined
703:635158661:REFZR:4000 m above ground:rpn_corr=-nan:rpn_rms=undefined
704:635396992:REFZI:4000 m above ground:rpn_corr=-nan:rpn_rms=undefined
706:636307658:REFZR:1000 m above ground:rpn_corr=-nan:rpn_rms=undefined
707:636545989:REFZI:1000 m above ground:rpn_corr=-nan:rpn_rms=undefined
722:656007087:ASNOW:surface:rpn_corr=0.661982:rpn_rms=4.55196e-05
763:706949147:POT:10 m above ground:rpn_corr=-nan:rpn_rms=undefined
764:707187478:SPFH:10 m above ground:rpn_corr=-nan:rpn_rms=undefined
771:708930629:NCPCP:surface:rpn_corr=-nan:rpn_rms=undefined
772:709168984:NCPCP:surface:rpn_corr=-nan:rpn_rms=undefined
773:709407339:LSPA:surface:rpn_corr=-nan:rpn_rms=undefined
774:709645694:FROZR:surface:rpn_corr=-nan:rpn_rms=undefined
775:709884049:FRZR:surface:rpn_corr=-nan:rpn_rms=undefined
776:710122404:TSNOWP:surface:rpn_corr=-nan:rpn_rms=undefined
777:710360759:SNOM:surface:rpn_corr=-nan:rpn_rms=undefined
779:710888776:BGRUN:surface:rpn_corr=-nan:rpn_rms=undefined
780:711127131:WATR:surface:rpn_corr=-nan:rpn_rms=undefined
781:711365486:FROZR:surface:rpn_corr=-nan:rpn_rms=undefined
782:711603841:FRZR:surface:rpn_corr=-nan:rpn_rms=undefined
783:711842196:TSNOWP:surface:rpn_corr=-nan:rpn_rms=undefined
803:720031351:EVP:surface:rpn_corr=-nan:rpn_rms=undefined
808:724242661:UFLX:surface:rpn_corr=-nan:rpn_rms=undefined
809:724480992:VFLX:surface:rpn_corr=-nan:rpn_rms=undefined
822:736871974:AOTK:entire atmosphere (considered as a single layer):rpn_corr=-nan:rpn_rms=undefined
834:743355407:SWHR:entire atmosphere (considered as a single layer):rpn_corr=-nan:rpn_rms=undefined
835:743593738:LWHR:entire atmosphere (considered as a single layer):rpn_corr=-nan:rpn_rms=undefined
843:749939867:CDLYR:entire atmosphere (considered as a single layer):rpn_corr=-nan:rpn_rms=undefined
861:774862543:ULWRF:top of atmosphere:rpn_corr=-nan:rpn_rms=undefined
866:781558620:AEMFLX:surface:rpn_corr=-nan:rpn_rms=undefined
867:781796975:FWINX:surface:rpn_corr=-nan:rpn_rms=undefined
868:782035306:CSDSF:surface:rpn_corr=-nan:rpn_rms=undefined
1023:990025361:ALBDO:surface:rpn_corr=-nan:rpn_rms=undefined
1024:990263692:SNFALB:surface:rpn_corr=-nan:rpn_rms=undefined
```

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You testing is consistent with mine. We can ignore these fields with undefined rms since they have undefined values for all grids.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA and @EdwardColon-NOAA Please be aware that the computation of snow fall (ASNOW) will be updated with this PR for RRFS and 3DRTMA.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Please go ahead to approve this PR.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA I thought the ASNOW change was only for 3DRTMA, not RRFS?

**Comment by WenMeng-NOAA** [comment]
The PR is ready for merging. The baseline of 3DRTM will be recreated.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA I thought the ASNOW change was only for 3DRTMA, not RRFS?

@EricJames-NOAA From UPP RT testing perspective, change is only for 3DRTMA since we still use a legacy version of model history files and control file (fv3lam.xml) for RRFS testing. The 3DRTMA uses control file fv3lam_rrfs.xml.

**Pull request merged**
