### PR TITLE
Support GFSV16.2.0 on Hera/Orion

### LINKED ISSUE #442: Update GFSV16 branch with hpc-stack on Hera and Orion
Update the UPP for GFSV16 branch release/gfs_v16 on Hera/Orion:

- Use hpc-stack 
- Use LUA format for modulefile

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The changes for support GFS V16.2.0 on Hera/Orion:

- Use NCEPLIBs built from hpc/1.2.0.
- Use modulefiles in lua format

### CODE REVIEW

**Review by KateFriedman-NOAA — APPROVED** [review]
Updates to support Hera/Orion for GFSv16.2.0 look good. I tested building the post_gfsv16_hpc branch on both Hera and Orion, please see the following logs to confirm they built as expected with the g-w versions files in play:
Hera: /scratch1/NCEPDEV/global/Kate.Friedman/git/dev_v16/sorc/logs/build_ncep_post.log_post_gfsv16_hpc
Orion: /work/noaa/global/kfriedma/git/dev_v16/sorc/logs/build_ncep_post.log_post_gfsv16_hpc

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA Both build logs look good to me. When you may set "machine=ORION" for orion and "machine=HERA" for hera in g-w runtime configuration. When this PR merged, I will create a new tag upp_v8.1.1 for supporting GFS V16.2.0 on hera and orion. Please let me know if you have comments on tag name.

**Comment by KateFriedman-NOAA** [comment]
> Both build logs look good to me

Excellent, thanks for confirming!

> When you may set "machine=ORION" for orion and "machine=HERA" for hera in g-w runtime configuration.

Not sure I understand what you're saying here, can you elaborate? Thanks!

> new tag upp_v8.1.1 for supporting GFS V16.2.0 on hera and orion

Tag name works for me! I'll be testing this tag (and the other updated components for GFSv16.2.0 R&D support) on WCOSS2 to confirm the R&D updates do not break/impact WCOSS2. Is there any concern regarding WCOSS2? Thanks!

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA 

> When you may set "machine=ORION" for orion and "machine=HERA" for hera in g-w runtime configuration.
> 
> Not sure I understand what you're saying here, can you elaborate? Thanks!

It's just a reminder. The undefining or setting incorrectly  variable "machine" from upstream configuration might cause MPMD process unlaunched. That would take a longer time to generate PGRB datasets.

**Comment by KateFriedman-NOAA** [comment]
> > When you may set "machine=ORION" for orion and "machine=HERA" for hera in g-w runtime configuration.
> > Not sure I understand what you're saying here, can you elaborate? Thanks!
> 
> It's just a reminder. The undefining or setting incorrectly variable "machine" from upstream configuration might cause MPMD process unlaunched. That would take a longer time to generate PGRB datasets.

Oh ok, I see. So the global-workflow setup scripts define `machine` at runtime (in config.base and the rocoto xml) as one of the following: `WCOSS2`, `HERA`, `ORION`, or `WCOSS_DELL_P3`. We'll have `JET` and possibly others down the road too. Those settings line up with what you state is used by the UPP so I think we're good. At build-time the global-workflow machine-setup.sh script sets a `target` variable that is the lowercase equivalent of `machine` but the characters are the same. Is there any issue with the lowercase `target` variable at buildtime for the UPP?

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA Thanks for confirming from g-w end. The UPP build script [sorc/](https://github.com/NOAA-EMC/UPP/blob/release/gfs_v16/sorc/build_ncep_post.sh) uses lowercase for "machine" setting in build time. There should no issue for build time in UPP standalone and global-work perspective so far.

**Comment by KateFriedman-NOAA** [comment]
> The UPP build script [sorc/](https://github.com/NOAA-EMC/UPP/blob/release/gfs_v16/sorc/build_ncep_post.sh) uses lowercase for "machine" setting in build time. There should no issue for build time in UPP standalone and global-work perspective so far.

Good, thanks for confirming the `machine` variable usage on the UPP side for build time. Sounds like we're good for both run and build.

**Pull request merged**
