### PR TITLE
Additional RT log information

### LINKED ISSUE #942: Improvements to UPP RT logs
Improve the UPP RT logs by adding more potentially useful information in reference to the UFS Weather Model's log structure. Additions would include hashes, testing date, total test times, test directories, etc.

### PR DESCRIPTION
**Pull request by FernandoAndrade-NOAA**
This PR provides more RT log information similar to UFS Weather Model including:

1. Test date
2. Total test time
3. Run directory
4. Baseline directory
5. UPP Hash
6. Submodule hashes

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2 without changed results.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA I conducted the UPP RTs with the CI driver script. The new RT log look good to me. You may start RTs on Hera and Orion.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA I conducted the UPP RTs with the CI driver script. The new RT log look good to me. You may start RTs on Hera and Orion.

Sounds good, thanks! I'll start up the Hera RTs, Orion and Hercules are currently having issues today so there will be a delay with testing on those systems.

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA RT logs pushed up, no changes across machines, thanks!

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
