### PR TITLE
To make 'cmake' go through for GTG:

### LINKED ISSUE #272: Update cmake build with GTG code
The current EMC_post develop branch does not build with GTG code. 

Tried to build develop (33eb60e) on WCOSS-Dell with GTG code copied in; build failed:

/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/logs/build_ncep_post_33eb60e.log

```
...
[ 19%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/TABLE.f.o
[ 19%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/TABLEQ.f.o
[ 19%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/UPP_MATH.f.o
[ 19%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/xml_perl_data.f.o
[ 20%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/gtg_ctlblk.f90.o
[ 21%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/native_endianness.f.o
[ 21%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/AllGETHERV_GSD.f.o
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90(13): warning #5117: Bad # preprocessor line
#ifndef NCAR
-^
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90(15): warning #5117: Bad # preprocessor line
#endif
-^
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90(19): warning #5117: Bad # preprocessor line
#ifdef NCAR
-^
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90(23): warning #5117: Bad # preprocessor line
#endif
-^
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90(22): error #6401: The attributes of this name conflict with those made accessible by a USE statement.   [SPVAL]
  real,parameter :: SPVAL=9.9E10
--------------------^
compilation aborted for /gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90 (code 1)
make[2]: *** [sorc/ncep_post.fd/CMakeFiles/upp.dir/gtg_ctlblk.f90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [sorc/ncep_post.fd/CMakeFiles/upp.dir/all] Error 2
make: *** [all] Error 2
+ make install
[  1%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/physcons.f.o
[  2%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/GFIP3.f.o
[  3%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/UPP_PHYSICS.f.o
[  4%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/grib2_module.f.o
[  5%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/gtg_ctlblk.f90.o
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90(13): warning #5117: Bad # preprocessor line
#ifndef NCAR
-^
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90(15): warning #5117: Bad # preprocessor line
#endif
-^
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90(19): warning #5117: Bad # preprocessor line
#ifdef NCAR
-^
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90(23): warning #5117: Bad # preprocessor line
#endif
-^
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90(22): error #6401: The attributes of this name conflict with those made accessible by a USE statement.   [SPVAL]
  real,parameter :: SPVAL=9.9E10
--------------------^
compilation aborted for /gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/sorc/ncep_post.fd/gtg_ctlblk.f90 (code 1)
make[2]: *** [sorc/ncep_post.fd/CMakeFiles/upp.dir/gtg_ctlblk.f90.o] Error 1
make[1]: *** [sorc/ncep_post.fd/CMakeFiles/upp.dir/all] Error 2
make: *** [all] Error 2
+ rm -rf /gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/exec
+ mkdir /gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/exec
+ cp /gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/tests/install/bin/upp.x /gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/exec/.
cp: cannot stat ‘/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/feature-hpc-stack/sorc/gfs_post.fd/tests/install/bin/upp.x’: No such file or directory

### PR DESCRIPTION
**Pull request by YaliMao-NOAA**
(To fix issue #272)
1. GTG source code file extensions are changed from f90 to F90
2. Add ip::ip_4 back to sorc/ncep_post.fd/CMakeLists.txt

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA Will you update Externals.cfg with checking out master branch from gtg repository?

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA My gfs test failed at wafs data generation as:
 iSF_SURFACE_PHYSICS=           0
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
upp.x              00000000015E4EED  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B4D36905630  Unknown               Unknown  Unknown
upp.x              00000000016C3DF0  Unknown               Unknown  Unknown
upp.x              0000000000A4043A  gtg_algo_                 179  gtg_algo.F90
upp.x              0000000000949C4B  mdlfld_                  3745  MDLFLD.f
upp.x              00000000006BF02D  process_                   82  PROCESS.f
upp.x              0000000000656A02  MAIN__                    932  WRFPOST.f
upp.x              00000000004076DE  Unknown               Unknown  Unknown
libc-2.17.so       00002B4D371EF545  __libc_start_main     Unknown  Unknown
upp.x              00000000004075E9  Unknown               Unknown  Unknown

Can you take a look at it?

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA Can you sync your branch with upstream/develop? Your PR would be the next one for merging. Also please test wafs dataset generation.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA With the update from your branch, my test still failed at wafs dataset generation as:
upp.x              0000000000A7EC9A  gtg_algo_                 179  gtg_algo.F90
upp.x              0000000000988383  mdlfld_                  3745  MDLFLD.f
upp.x              00000000006FE65D  process_                   82  PROCESS.f
upp.x              000000000065A7AD  MAIN__                    931  WRFPOST.f

Can you take a look at it? My UPP clone is at /scratch1/NCEPDEV/stmp2/Wen.Meng/yali/EMC_post on Hera.

**Comment by YaliMao-NOAA** [comment]
@WenMeng-NOAA I am able to duplicate the error messages on Hera and going to take a look. No errors popped up on Dell with the same input, so I guess Hera may have different compiling options.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA I got the same errors on Dell. Are you saying you can run though wafs dataset generation on Dell?
You may see the log file of my test in  /u/Wen.Meng/ptmp/nceppost/outputs/test_post_gfs_2020020400.o55702406.

**Comment by YaliMao-NOAA** [comment]
Yes, I ran through two cases on Dell. One is your canned data, 20200204 00z f006, /gpfs/dell3/ptmp/Yali.Mao/post_gtg.o55683870 and the other is 20210414 00z f012, /gpfs/dell3/ptmp/Yali.Mao/post_gtg.o55658109

I am debugging on Hera, which is really slow picking up a job. Right now, I can conclude the cmake version of UPP on Hera doesn't handle optional arguments well. I am not sure who I can get help from.

On Dell, I compared my UPP (/gpfs/dell2/emc/modeling/noscrub/Yali.Mao/git/EMC_post_wafs) and your UPP (/u/Wen.Meng/noscrubd6/ncep_post/yali/EMC_post), I found two significant differences.
1. parm/gtg.config.gfs (EMC_post develop github inventory doesn't have the most recent version. My UPP ran through with both versions)
2. All other differences are cmake related, which I don't understand well.
My driver is almost the same as yours /gpfs/dell2/emc/modeling/noscrub/Yali.Mao/git/EMC_post_fork/driver/run_gtg_post.sh.dell.cmake

**Comment by YaliMao-NOAA** [comment]
On Hera, I removed the optional arguments, recompiled and re-ran, and it went through. It's not a good fix since the code is supposed to work with the optional arguments. But before further investigation, would you please help me to identify whether what I guess is right?
On Hera, please copy /scratch2/NCEPDEV/ovp/Yali.Mao/git/UPP_GTG_fork/gtg_algo.F90 to your UPP, recompile and have a test run. If it goes through, I will ask the help from cmake group.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA I looked into your UPP working version at /gpfs/dell2/emc/modeling/noscrub/Yali.Mao/git/EMC_post_wafs/sorc/ncep_post.fd on Venus. It looks all gtg routines are stub code. How did you build UPP executable with gtg code checked out from gtg private repository? Do you have UPP combined with gtg code building procedure changes?

**Comment by WenMeng-NOAA** [comment]
> parm/gtg.config.gfs (EMC_post develop github inventory doesn't have the most recent version. My UPP ran through with both versions)
I copied gtg.config.gfs from gtg code checkout directory sorc/post_gtg.fd to parm/.

**Comment by YaliMao-NOAA** [comment]
About gtg.config.gfs, I mean there are differences between this two versions:
1. https://github.com/NOAA-EMC/EMC_post/blob/develop/parm/gtg.config.gfs
2. /u/Wen.Meng/noscrubd6/ncep_post/yali/EMC_post/parm/gtg.config.gfs, which is the same as /gpfs/dell1/nco/ops/nwprod/gfs.v16.0.9/parm/post/gtg.config.gfs

This is the reason why I said "EMC_post develop github inventory doesn't have the most recent version"

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA That difference is intended. You don't want to keep the up to dated version of gtg.config.gfs under public UPP repository. You set up the procedure of overwriting gtg.config.gfs after gtg code is checked out starting at GFS V15 implementation.

**Comment by YaliMao-NOAA** [comment]
Thank you for pointing out the old version of gtg.config.gfs is intended. Now I understand.

**Comment by YaliMao-NOAA** [comment]
To avoid uploading the real GTG code to github by accident, I set up my own compiling procedure. Before compiling, real GTG code is copied to UPP; after compiling, the stubs are copied back. So in my UPP version, you can only see the stubs. 

I am sure the executable file is built with the real GTG code, otherwise there won't be a successful GTG run generating gfs.t00z.wafs.grb2f006 under
/scratch2/NCEPDEV/stmp3/Yali.Mao/com_post/gfs.20200204/00/

Since I was not able to duplicate the error messages on Dell, I debugged on Hera. On Hera, please copy /scratch2/NCEPDEV/ovp/Yali.Mao/git/UPP_GTG_fork/gtg_algo.F90 to your UPP, recompile and have a test run. Other GTG code is the same and you don't need to copy them.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA I copied your new gtg_algo.F90, compiled and tested. Now the wafs dataset is generated at 
/scratch1/NCEPDEV/stmp2/Wen.Meng/com2/gfs/test/gfs.20200204/00
Please verify it.

**Comment by YaliMao-NOAA** [comment]
Thank you for the testing. Our results are bit-wise identical.
/scratch1/NCEPDEV/stmp2/Wen.Meng/com2/gfs/test/gfs.20200204/00/gfs.t00z.wafs.grb2f006 
/scratch2/NCEPDEV/stmp3/Yali.Mao/com_post/gfs.20200204/00/gfs.t00z.wafs.grb2f006

But this version of gtg_algo.F90 is not a fix, it is just to verify what I guess is right. The original version should be right, the issue must come from cmake compiling. Any suggestion that I should report the bug under cmake or post group? Thank you.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA I would look for the help from EIB. You may add the question from the issue #272 and @ a couple CMAKE experts.

**Comment by YaliMao-NOAA** [comment]
@WenMeng-NOAA Thank you for the suggestion. I reported the issue under #272 and @ Kyle

**Comment by YaliMao-NOAA** [comment]
I communicated with NCAR GTG group and the code was modified and worked on both side.
I pulled the most recent develop branch, and did a test which went through.

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were conducted on WCOSS-Dell, WCOSS_Cray and Hera. No changed results were found. The GFS wafs dataset was successfully created in the test. This PR is read for merging.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
