### PR TITLE
RRFS IFI crash fix + debug mode change

### LINKED ISSUE #850: Getting some failures with RRFS configuration
Over the last couple of weeks, we've had several failures with the UPP within the RRFS real-time parallel.  Based on the limited amount of traceback information in the log, it seems to be failing at the mpi_barrier call near the end of the WRFPOST.f code.

```
            CALL PROCESS(kth,kpv,th(1:kth),pv(1:kpv),iostatusD3D)
            IF(ME == 0) WRITE(6,*)'WRFPOST:  PREPARE TO PROCESS NEXT GRID'
!
!           write(*,*)'enter gribit2 before mpi_barrier'
            call mpi_barrier(mpi_comm_comp,ierr)
```
For one of the cases, I captured the model dyn*.nc and phy*.nc files for the failing case, in addition to the logfile.  These are in /lfs/h2/emc/lam/noscrub/emc.lam/post_fail_log/2023122706_case/ on cactus.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
This fixes the RRFS IFI crash, which was caused by incorrect error handling for extreme values of potential temperature. 

Also, it enables libIFI's own debug mode (-DIFI_DEBUG=ON) when UPP is built with inline IFI (-I) and debug (-d). That debug mode enables bounds checking and other safeguards. It also causes uncaught C++ exceptions to pass through to Fortran. That usually results in a stack trace or core dump to the point in the C++ library that raised the exception. (Without debug mode, C++ returns an integer error code to Fortran.)

- waiting on https://github.com/NCAR/UPP_IFI/pull/5
- fixes #850

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA Can you sync your branch with the latest UPP develop?

**Review by MatthewPyle-NOAA — APPROVED** [review]
Great to see this problem being fixed so quickly.  Can't comment on the IFI changes, but like the compile modification to utilize debug options for IFI when appropriate.

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA @MatthewPyle-NOAA 
I did two tests:
test 1: 
  UPP version: current UPP develop
  RRFS data file:  RRFS parallel failure case  '2023122706_case'
  run directory: /u/wen.meng/ptmp/post_rrfs_2023122706-fail
  ** This test failed at IFI* file generation.

test 2:
  UPP version: Sam's PR #852 
  RRFS data file:  RRFS parallel failure case  '2023122706_case'
  run directory: /u/wen.meng/ptmp/post_rrfs_2023122706-sam-fix
  ** This test was successfully completed.

It appears to me that Sam's fix is working. Please let me know if you see issues in my tests.

**Comment by SamuelTrahanNOAA** [comment]
My tests finished:

- Matt Pyle's case: passed on WCOSS
- Shun Liu's case: passed on WCOSS and Hera

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA Is your PR available for final testing? If yes, please sync with the UPP develop.

**Comment by SamuelTrahanNOAA** [comment]
@WenMeng-NOAA - It is ready for testing. The libIFI PR was merged and the branch is up to date.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2, Hera and Orion without changed results. This PR is ready for merging.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
