### PR TITLE
Modify ROTDIR setting

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Modify RODIR setting in JGLOBAL_ATMOS_NCEPPOST.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA In JGLOBAL_ATMOS_NCEPPOST, both COMIN/COMOUT point to ROTDIR as root path,
`export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}`
`export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}`

There is no need for modifying them, right?

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA In JGLOBAL_ATMOS_NCEPPOST, both COMIN/COMOUT point to ROTDIR as root path, `export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}` `export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}`
> 
> There is no need for modifying them, right?

Correct, you don't need to modify those COM* lines now that ROTDIR is being set with compath.py at the configuration level.

**Review by KateFriedman-NOAA — APPROVED** [review]
This change to remove the RUN_ENVIR=nco ROTDIR block looks good, thanks @WenMeng-NOAA!

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA  In JGLOBAL_ATMOS_NCEPPOST:
```
if [ $RUN_ENVIR = "nco" ]; then
    export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
    export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
else
    export COMIN="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
fi
```
Do you think they could be unified as the following for both NCO and EMC parallel run:
```
export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
```

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA In JGLOBAL_ATMOS_NCEPPOST:
> 
> ```
> if [ $RUN_ENVIR = "nco" ]; then
>     export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
>     export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
> else
>     export COMIN="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
>     export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
> fi
> ```
> 
> Do you think they could be unified as the following for both NCO and EMC parallel run:
> 
> ```
> export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
> export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
> ```

Yes, actually I think that would be fine. Please made that consolidation and I can double check it's fine in my current test. Thanks!

**Comment by KateFriedman-NOAA** [comment]
@WenMeng-NOAA I made that change locally in my clone and am rerunning some gdaspost jobs. It looks like it's working fine:

```
Kate.Friedman@dlogin03> grep COMIN= logs/2021122700/gdaspost001.log                                      
0.183 + COMIN=/lfs/h2/emc/ptmp/Kate.Friedman/comrot/testcyc768l/com/gfs/v16.2/gdas.20211227/00/atmos
COMIN=/lfs/h2/emc/ptmp/Kate.Friedman/comrot/testcyc768l/com/gfs/v16.2/gdas.20211227/00/atmos
Kate.Friedman@dlogin03> grep COMOUT= logs/2021122700/gdaspost001.log                                       
0.183 + COMOUT=/lfs/h2/emc/ptmp/Kate.Friedman/comrot/testcyc768l/com/gfs/v16.2/gdas.20211227/00/atmos
COMOUT=/lfs/h2/emc/ptmp/Kate.Friedman/comrot/testcyc768l/com/gfs/v16.2/gdas.20211227/00/atmos
```

Here is my git diff:
```
Kate.Friedman@dlogin03:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2/sorc/gfs_post.fd> git diff jobs/JGLOBAL_ATMOS_NCEPPOST
diff --git a/jobs/JGLOBAL_ATMOS_NCEPPOST b/jobs/JGLOBAL_ATMOS_NCEPPOST
index 66c8135..d134ec0 100755
--- a/jobs/JGLOBAL_ATMOS_NCEPPOST
+++ b/jobs/JGLOBAL_ATMOS_NCEPPOST
@@ -65,9 +65,6 @@ export g2tmpl_ver=${g2tmpl_ver:-v1.5.0}
 export CDATE=${CDATE:-${PDY}${cyc}}
 export CDUMP=${CDUMP:-${RUN:-"gfs"}}
 export COMPONENT=${COMPONENT:-atmos}
-if [ $RUN_ENVIR = "nco" ]; then
-    export ROTDIR=${COMROOT:?}/$NET/$envir
-fi
 
 
 ##############################################
@@ -81,13 +78,8 @@ export FIXCRTM=${CRTM_FIX:-${HOMECRTM}/fix}
 export PARMpost=${PARMpost:-$HOMEgfs/parm/post}
 export INLINE_POST=${WRITE_DOPOST:-".false."}
 
-if [ $RUN_ENVIR = "nco" ]; then
-    export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
-else
-    export COMIN="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
-    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
-fi
+export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
+export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
 [[ ! -d $COMOUT ]] && mkdir -m 775 -p $COMOUT
 
 if [ $RUN = gfs ];then
```

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA Great! Please review my new commit and let me know if you have more comments. Thanks!

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good, thanks @WenMeng-NOAA !

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA The tag upp_v8.1.0 was recreated.

**Comment by KateFriedman-NOAA** [comment]
Awesome, thanks @WenMeng-NOAA !

**Pull request merged**
