### PR TITLE
Enable template 4-49 to obtain aerosol ensemble information

### LINKED ISSUE #1009: Added functionality to handle aerosol ensemble information in UPP
Aerosol ensemble simulations have been added to GEFS, and appropriate aerosol ensemble information should be identified and correctly passed to the GEFS GRIB 2 output via UPP, just as is done for meteorological variables

### PR DESCRIPTION
**Pull request by lipan-NOAA**
https://github.com/NOAA-EMC/UPP/issues/1009

In order to compile this update correctly, please update the g2tmpl library in the module file

### CODE REVIEW

**Comment by lipan-NOAA** [comment]
@WenMeng-NOAA The code update PR has been submitted, please review it.

**Comment by WenMeng-NOAA** [comment]
@lipan-NOAA The g2/3.5.1 and g2tmpl/1.13.0 are available on WCOSS2 and R&D platforms now. Can you update relevant modulefiles in your branch?

**Comment by WenMeng-NOAA** [comment]
@lipan-NOAA Can you also update the following gefs aerosol/chem control file under parm/gefs for gefs v13 products?
```
postcntrl_gefs_chem.xml and postxconfig-NT-gefs-chem.txt
postcntrl_gefs_aerosol_f00.xml and postxconfig-NT-gefs-f00-aerosol.txt
postcntrl_gefs_aerosol.xml and postxconfig-NT-gefs-aerosol.txt
```

**Comment by lipan-NOAA** [comment]
@WenMeng-NOAA I will update these later if possible as I still need to discuss with the GEFS team about the setup of the aerosol products in GEFS

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA I will update these later if possible as I still need to discuss with the GEFS team about the setup of the aerosol products in GEFS

@lipan-NOAA Your plan sounds good to me.  We will wrap your PR for processing.

**Comment by WenMeng-NOAA** [comment]
@lipan-NOAA I did an UPP standalone test with model output from GEFS v13 EP5r2 and control file "postxconfig-NT-gefs-aerosol.txt". My test results are at /u/wen.meng/ptmp/post_gefs_2018081600 on Cactus. Can you take a look at my test? Thanks!

**Comment by lipan-NOAA** [comment]
@WenMeng-NOAA it looks fine to me. Thanks.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on R&D machines. There should be no baseline update in this PR.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2. No baseline update is needed in this PR.

**Review by FernandoAndrade-NOAA — APPROVED** [review]
Results showed no changes across Hera, Hercules, and Orion. Failures in GCC CI build will likely continue until packages can be updated to 3.5.1 and 1.13.0

**Comment by SamuelTrahanNOAA** [comment]
The ufs-weather-model needs to support GCC. We'll have to get the GCC builds working before https://github.com/ufs-community/ufs-weather-model/pull/2326 can be merged.

> Failures in GCC CI build will likely continue until packages can be updated to 3.5.1 and 1.13.0

- https://github.com/ufs-community/ufs-weather-model/pull/2326

**Comment by WenMeng-NOAA** [comment]
> Results showed no changes across Hera, Hercules, and Orion. Failures in GCC CI build will likely continue until packages can be updated to 3.5.1 and 1.13.0

@FernandoAndrade-NOAA The GCC failure in GCC CI was on github. I am not sure if any updates are needed for the configuration of CI on github. Can you test the UPP standalone with GCC on Hera or Orion?

**Comment by FernandoAndrade-NOAA** [comment]
I can't confirm in the case of manual testing until the gnu spack-stack has been updated with g2 3.5.1 and g2tmpl 1.13.0

**Comment by SamuelTrahanNOAA** [comment]
If the gnu spack-stack hasn't been updated yet, then that is a confirmation that it doesn't work.

**Comment by FernandoAndrade-NOAA** [comment]
This was on Hera, which may be one of the machines with version conflicts Ratko mentioned, let me try Orion if it's available and as a pretest if there's going to be any issues.

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA @FernandoAndrade-NOAA The UPP build script under tests/compile_upp.sh doesn't include configuration for building executable with GCU compiler.  
@FernandoAndrade-NOAA Can you share with me your build script with GNU compiler on Hera?

**Comment by WenMeng-NOAA** [comment]
I saw g2/3.5.1 and g2tmpl/1.13.0 are available at /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/upp-addon-env/install/modulefiles/gcc/9.2.0 for GNU compiler on Hera. It appears to me the failure of @FernandoAndrade-NOAA 's testing might be finding the latest g2 and g2tmpl at the appropriate spack-stack location.  That issue could be addressed in the UFS PR #2326.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
