### PR TITLE
Adding RRFS products to fv3lam_post_avblflds.xml and fv3lam_rrfs.xml

### PR DESCRIPTION
**Pull request by AndrewBenjamin-NOAA**
Updated fv3lam_rrfs.xml and fv3lam_post_avblflds.xml to include more operational products needed for the RRFS. These products could be added directly (existing products in UPP)

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
@AndrewBenjamin-NOAA could you sync your branch with develop? I'll get started on RTs on Hera and Orion following the sync. Thank you

**Comment by AndrewBenjamin-NOAA** [comment]
@FernandoAndrade-NOAA I just synced with upstream/develop. Thank you

**Comment by FernandoAndrade-NOAA** [comment]
UPP RTs have completed on Hera and Orion. I'm seeing changes in results for rtma in fields 2-1275 in NATLEV00.tm00.diff and 2-976 in PRSLEV00.tm00.diff

Run directory results can be checked in the following locations:
Hera: /scratch1/NCEPDEV/stmp2/Fernando.Andrade-maldonado/rtma_2023040400
Orion: /work/noaa/epic-ps/nandoam/upp-testing/emc-tests/rt-699/rundir/rtma_2023040400

Please let me know if you see any unexpected changes.

@HuiyaChuang-NOAA Could you run RTs on WCOSS2 and verify results? Thank you

**Comment by HuiyaChuang-NOAA** [comment]
> UPP RTs have completed on Hera and Orion. I'm seeing changes in results for rtma in fields 2-1275 in NATLEV00.tm00.diff and 2-976 in PRSLEV00.tm00.diff
> 
> Run directory results can be checked in the following locations: Hera: /scratch1/NCEPDEV/stmp2/Fernando.Andrade-maldonado/rtma_2023040400 Orion: /work/noaa/epic-ps/nandoam/upp-testing/emc-tests/rt-699/rundir/rtma_2023040400
> 
> Please let me know if you see any unexpected changes.
> 
> @HuiyaChuang-NOAA Could you run RTs on WCOSS2 and verify results? Thank you

@AndrewBenjamin-NOAA @FernandoAndrade-NOAA 

I have a few questions and concerns about this PR:
1) I believe fv3lam_rrfs.xml is no longer used as Wen unified all post avaiable xml file and "post_avblflds.xml" is now 
used as the unified one;
2) I was going to ask if @AndrewBenjamin-NOAA  ran a UPP RT test to see what variables were changed but it looks 
Fernando's RT tests are showing Andrew's PR changed RT output.

**Comment by HuiyaChuang-NOAA** [comment]
Huiya emailed @EricJames-NOAA who confirm GSL used the unified post available xml file "post_avblflds.xml".

Huiya asked that @AndrewBenjamin-NOAA withdraw this PR for now and work on a different PR using the unified post available xml file above.  Also run UPP RT on wcoss2 first to verify the output.

**Comment by AndrewBenjamin-NOAA** [comment]
Closing and will resubmit under new PR.

**Pull request closed without merging**
