### PR TITLE
Sync EE2 updates from AQM v7 implementation

### LINKED ISSUE #881: Update UPP with crtm/2.4.0.1 on WCOSS2 and WCOSS2_Acorn
Update UPP with crtm/2.4.0.1 on WCOSS2 and Acorn.

### LINKED ISSUE #882: Sync changes of AQM v7 to UPP develop
The changes of EE2 requirements from AQM v7 implementation need to be synced to UPP develop.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
The main updates are:

- Sync EE2 updates from AQM v7 implementation
- Upgrade crtm to 2.4.0.1 on WCOSS2
- Update modulefiles on WCOSS2 Acorn

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA This PR is ready for testing on Hera and Orion. Thanks!

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2 without changed results.

**Review by FernandoAndrade-NOAA — APPROVED** [review]
UPP RTs on Hera, Hercules, and Orion have completed successfully with no changes to results.

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
