### PR TITLE
Adds more precision for ASNOW and PRATE for RRFS

### LINKED ISSUE #807: Precision for ASNOW and PRATE in RRFS needs to be increased
It was noticed when taking differences from ASNOW fields to generate shorter accumulation periods that it doesn't appear to be written with enough precision to account for the product being defined in units of meters rather than the more typical kg/m^2 (or mm) for precipitation fields.  Creating this issue to reference in a PR.

### PR DESCRIPTION
**Pull request by MatthewPyle-NOAA**
As mentioned in the associated [issue ](https://github.com/NOAA-EMC/UPP/issues/807), we've noticed that the GSD snow field (ASNOW) and the instantaneous and maximum precipitation rate (PRATE) fields need more precision for the RRFS.  This PR boosts the scaling values for these fields within parm/fv3lam_rrfs.xml.  It changes answers in the fv3r regression tests.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@MatthewPyle-NOAA You need to update RRFS text control file with modification of RRFS xml file. You may do:
```
cd UPP/parm
make
```
You would expect the changes in postxconfig-NT-fv3lam_rrfs.txt.

**Comment by MatthewPyle-NOAA** [comment]
Thanks @WenMeng-NOAA - I'd forgotten how the .txt file gets generated.  Will do that and update my PR.

**Comment by WenMeng-NOAA** [comment]
@MatthewPyle-NOAA Can you sync your branch for processing?

**Comment by MatthewPyle-NOAA** [comment]
Have resync'd it now...

**Comment by WenMeng-NOAA** [comment]
@MatthewPyle-NOAA From my RRFS testing, there are changes in PRATE and ASNOW fields as:
```
NATLEV file:
before:  wgrib2 NATLEV10.tm00.WCOSS2 -match PRATE -stats -s
1565:1312211998:ndata=1905141:undef=0:mean=2.03196e-05:min=0:max=0.0676:cos_wt_mean=2.00784e-05:d=2023062800:PRATE:surface:10 hour fcst:
after:  wgrib2 NATLEV10.tm00 -match PRATE -stats -s
1565:1312211998:ndata=1905141:undef=0:mean=2.15285e-05:min=0:max=0.067552:cos_wt_mean=2.1315e-05:d=2023062800:PRATE:surface:10 hour fcst:

PRSLEV file:
before:  wgrib2 PRSLEV10.tm00.WCOSS2 -match PRATE -stats -s                                   
817:804077193:ndata=1905141:undef=0:mean=2.03196e-05:min=0:max=0.0676:cos_wt_mean=2.00784e-05:d=2023062800:PRATE:surface:10 hour fcst:
818:804133787:ndata=1905141:undef=0:mean=0.00010704:min=0:max=0.1179:cos_wt_mean=0.000106981:d=2023062800:PRATE:surface:9-10 hour max fcst:                       

after: wgrib2 PRSLEV10.tm00 -match PRATE -stats -s                                
817:804077204:ndata=1905141:undef=0:mean=2.15285e-05:min=0:max=0.067552:cos_wt_mean=2.1315e-05:d=2023062800:PRATE:surface:10 hour fcst:
818:804406995:ndata=1905141:undef=0:mean=0.000108895:min=0:max=0.117904:cos_wt_mean=0.000108873:d=2023062800:PRATE:surface:9-10 hour max fcst:

before: wgrib2 PRSLEV10.tm00.WCOSS2 -match ASNOW -stats -s                                   
761:734934407:ndata=1905141:undef=0:mean=1.6096e-06:min=0:max=0.046224:cos_wt_mean=1.46234e-06:d=2023062800:ASNOW:surface:0-10 hour acc fcst:

after:  wgrib2 PRSLEV10.tm00 -match ASNOW -stats -s                                
761:734934407:ndata=1905141:undef=0:mean=1.6096e-06:min=0:max=0.0462242:cos_wt_mean=1.46234e-06:d=2023062800:ASNOW:surface:0-10 hour acc fcst:

```

You may access my test case at /u/wen.meng/ptmp/fv3r_2023062800 on Dogwood. Please let me know if you see issues.

**Comment by MatthewPyle-NOAA** [comment]
@WenMeng-NOAA Looks good from my perspective - thanks!

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2. There will be baseline changes for fv3r and 3drtma in this PR.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion and refer to my test results on Hera at /scratch1/NCEPDEV/stmp2/Wen.Meng as:
```
[Wen.Meng@hfe01 ~/stmp2]$ ls -ltr */*diff
-rw-r--r-- 1 Wen.Meng stmp    75 Oct 30 13:47 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp  1962 Oct 30 13:48 fv3r_2023062800/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  1962 Oct 30 13:49 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14665 Oct 30 13:49 rtma_2023040400_pe_test/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14665 Oct 30 13:49 rtma_2023040400/NATLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  2484 Oct 30 13:51 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14528 Oct 30 13:51 fv3r_2023062800/NATLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp  2484 Oct 30 13:51 rtma_2023040400/PRSLEV00.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14528 Oct 30 13:52 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
```

**Comment by FernandoAndrade-NOAA** [comment]
There seems to be an issue with Jenkins, I'm running manually in the meantime on Hera and Orion.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion and refer to my test results on Hera at /scratch1/NCEPDEV/stmp2/Wen.Meng as:
> 
> ```
> [Wen.Meng@hfe01 ~/stmp2]$ ls -ltr */*diff
> -rw-r--r-- 1 Wen.Meng stmp    75 Oct 30 13:47 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
> -rw-r--r-- 1 Wen.Meng stmp  1962 Oct 30 13:48 fv3r_2023062800/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  1962 Oct 30 13:49 fv3r_2023062800_pe_test/PRSLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14665 Oct 30 13:49 rtma_2023040400_pe_test/NATLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14665 Oct 30 13:49 rtma_2023040400/NATLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  2484 Oct 30 13:51 rtma_2023040400_pe_test/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14528 Oct 30 13:51 fv3r_2023062800/NATLEV10.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp  2484 Oct 30 13:51 rtma_2023040400/PRSLEV00.tm00.diff
> -rw-r--r-- 1 Wen.Meng stmp 14528 Oct 30 13:52 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
> ```

My UPP RT results match your changes on Hera and Orion.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
