### PR TITLE
Documentation changes

### PR DESCRIPTION
**Pull request by hertneky**
Documentation changes for develop

### CODE REVIEW

**Comment by fossell** [comment]
@WenMeng-NOAA - These were just a couple extra mods we needed to put into the release branch, one was an important fix to make sure that new unified variable table was rendered properly on the UG website. Sorry we didn't get them in before the merge of the branch.

**Comment by WenMeng-NOAA** [comment]
@fossell Got it. Thanks for updating.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@fossell The PR looks good to me. Please let me know if you have comments. Thanks!

**Review by fossell — APPROVED** [review]
Looks good to me.

**Comment by fossell** [comment]
@WenMeng-NOAA - You can merge without @camshe approval.

**Pull request merged**
