### PR TITLE
Update FV3-LAM flat files and ncep_post executable names

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
In reference to discussion in Issue #145, the post executable in the develop branch has been renamed ncep_post and the FV3-LAM-relevant flat files were renamed to include the FV3-LAM acronym instead of FV3-SAR.  These changes bring the develop branch in line with the release/public-v2 branch.

@WenMeng-NOAA @mkavulich

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@JeffBeck-NOAA Do you have corresponding xml files for fv3lam and fv3lam_goes flat files? It would be better for keeping a pair of xml
and flat files under the parm directory.

**Comment by Empyrean2** [comment]
> @JeffBeck-NOAA Do you have corresponding xml files for fv3lam and fv3lam_goes flat files? It would be better for keeping a pair of xml
> and flat files under the parm directory.

@WenMeng-NOAA, I can also rename the related XML files. I'll go ahead and push a commit to do that.

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA Do you have corresponding xml files for fv3lam and fv3lam_goes flat files? It would be better for keeping a pair of xml
> and flat files under the parm directory.

@WenMeng-NOAA, I can also rename the related XML files. I'll go ahead and push a commit to do that.

**Comment by WenMeng-NOAA** [comment]
@JeffBeck-NOAA Would you also change sar to lam in parm/makefile?

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA Would you also change sar to lam in parm/makefile?

@WenMeng-NOAA, done!

**Comment by WenMeng-NOAA** [comment]
@JeffBeck-NOAA Now it is in a good shape. I will proceed code reviewing testing. Thanks!

**Comment by WenMeng-NOAA** [comment]
@EricRogers-NOAA and @BenjaminBlake-NOAA Please review this PR for renaming UPP control files for FV3 LAM/LAMX. Thanks!

**Comment by BenjaminBlake-NOAA** [comment]
@WenMeng-NOAA  This PR looks good to me so I'll go ahead and approve it

**Review by BenjaminBlake-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
The regression tests were conducted on Dell, Cray and Hera. No changed results were found. This PR is ready for merging.

**Pull request merged**
