### PR TITLE
Update release/gfs_v16 with the feedback from NCO

### LINKED ISSUE #432: Update branch release/gfs_v16 on WCOSS2 with NCO's feedback
Update branch release/gfs_v16 on WCOSS2 with NCO's feedback.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Update branch release/gfs_v16 with the feedback from NCO.

### CODE REVIEW

**Review by KateFriedman-NOAA — APPROVED** [review]
Updates to modulefiles based on feedback from SPA Wei looks good, thanks @WenMeng-NOAA !

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA Thanks for review PR. Do you want me to create a new UPP tag for global-workflow right now, or we might for further feedback from NCO's runtime testing?

**Comment by KateFriedman-NOAA** [comment]
@WenMeng-NOAA If you plan to reuse the same tag name then feel free to recut the tag now. If you plan to make a new tag (newer version #) then let's wait and see if there are any other updates from NCO. I'm reviewing a possible script update related to ROTDIR right now, I will let you and others know tomorrow if edits are needed for that. Thanks!

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA Reusing the current tag name would be a good idea. I will wait for your further feedback and recreate the tag tomorrow. Thanks!

**Comment by KateFriedman-NOAA** [comment]
@WenMeng-NOAA Sounds good! Please check UPP scripts to make sure they set ROTDIR/COM* paths correctly (see email from me late yesterday). Once checked (and updated if needed) we can have you retag. Thanks!

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA I didn't pay attention on ROTDIR setting in gfs post j-job script. Can you give me an example from global-workflow scripts? Thanks!

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA The  UPP J-job script set ROTDIR/COMIN/COMOUT as:
```
if [ $RUN_ENVIR = "nco" ]; then
    export ROTDIR=${COMROOT:?}/$NET/$envir
fi
if [ $RUN_ENVIR = "nco" ]; then
    export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
    export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
else
    export COMIN="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
fi
...
```

I assume that the changes would be
```
if [ $RUN_ENVIR = "nco" ]; then
    export ROTDIR=$(compath.py ${envir}/${NET}/${gfs_ver})
fi
 
```

**Comment by KateFriedman-NOAA** [comment]
@WenMeng-NOAA Yes, that is one change that Wei and I just discussed. I am also now testing the removal of that RUN_ENVIR=nco block completely, with an adjustment for ROTDIR at the config level. Will let you and the other CMs know the outcome of that test and the needed changes today.

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA Thanks for confirming.

**Pull request merged**
