### PR TITLE
RRFS-MPAS applications: add several fields to output; remove "imp_physics" logic from INITPOST_MPAS

### LINKED ISSUE #1087: MPAS applications: fix / add several aviation fields, remove "if imp_physics..." logic from INITPOST_MPAS
A forthcoming PR will do the following for MPAS-related applications:

- For VIL, discontinue use of the local GRIB2 table
- Add GSL's experimental ceiling fields to the GRIB2 output
- Within "INITPOST_MPAS", remove instances of "if imp_physics...".  These portions of the code initialize various arrays based upon the microphysics scheme.  However, many of these "imp_physics" identifiers correspond to schemes in WRF-ARW.  If they are again needed for MPAS, these codes can be re-introduced.

This issue can be assigned to @jaymes-kenyon

### PR DESCRIPTION
**Pull request by jaymes-kenyon**
This PR addresses issue #1087 for MPAS applications.  Namely:

- For VIL, discontinue use of the local GRIB2 table
- Add GSL's experimental ceiling fields to the GRIB2 output

Additionally, within "INITPOST_MPAS", many instances "if imp_physics..." are removed.  These portions of the code (originally inherited from "INITPOST") initialize various hydrometeor arrays based upon the microphysics scheme.  However, many of these "imp_physics" identifiers correspond to schemes in WRF-ARW and may not have relevance for MPAS.  If future MPAS development requires this logic, then similar code structures can be re-introduced.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon I ran an UPP standalone test with MPAS data files you provided at /home/Wen.Meng/stmp2/mpas_2024082112-after on Hera. Can you take a look at it and let me know if you see issues?
The three new fields you are proposing have been generated in WRFTWO dataset as:
```
3:1190255:ndata=1905141:undef=0:mean=0.143845:min=0:max=76.18:cos_wt_mean=0.144931:d=2024082100:VIL:entire atmosphere:12 hour fcst:
113:70778438:ndata=1905141:undef=827150:mean=4332.37:min=23.9683:max=14617.5:cos_wt_mean=4394.42:d=2024082100:CEIL:cloud ceiling:12 hour fcst:
114:73009041:ndata=1905141:undef=0:mean=11423.9:min=23.9683:max=20000:cos_wt_mean=11497.2:d=2024082100:CEIL:cloud base:12 hour fcst:
```

**Comment by jaymes-kenyon** [comment]
@WenMeng-NOAA — Thanks!  Your test results look good; these are are new fields that are expected from this PR.  Thanks for sharing!

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA This PR is ready for the UPP RTs. There should be no baseline changes.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs have been completed on WCOSS2 with no baseline changes.

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by gspetro-NOAA** [comment]
RTs pass on Hera, Orion, and Hercules without baseline changes.

**Review by gspetro-NOAA — APPROVED** [review]
This PR is ready for merging.

**Pull request merged**
