### PR TITLE
Bug fix for invalid land categories in CRTM

### LINKED ISSUE #806: issue with land surface type
Recently, while using UPP (the latest version from the developer's branch) to simulate RRFS GOES-16 brightness temperatures, we noticed that there were scattered NaN values in the BT field (mostly along the land/sea interface). Looking a bit closer at the UPP output revealed numerous errors of the type:

 CRTM_LandSurface_IsValid(INFORMATION) : Invalid Land Surface type
 CRTM_Forward(FAILURE) : Input data check failed for profile #1

Investigating further, we noticed that in the CALRAD_WCLOUD subroutine, land surface types 15 and 17 (URBAN_CONCRETE and BROADLEAF_BRUSH) are reassigned to the INVALID_LAND category. This occurs at approximately line 250 of the subroutine where the variable model_to_crtm is populated when ivegsrc=1. I ran a test restoring the original land surface types and this eliminates the CRTM error messages as well as the NaNs.

We aren't sure why this reassignment is being done, but it does degrade the simulation of brightness temperatures and we presume it is impacting others' work as well.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
Collaborators at Wisconsin noted that two land surface types were being assigned as INVALID_LAND for CRTM.  This PR restores the appropriate land surface type, getting rid of NaNs in the simulated brightness temperature output.  

The code was tested for the RRFS_CONUS_3km system on Jet, and leads to minor expected differences in the simulated brightness temperatures (fewer undefined values).

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you sync your branch?

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were completed on WCOSS2. There will be baseline updates for fv3r, rap and hrrr with this PR.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RTs on Hera and Orion. This PR is a bug fix. There will be no field value change in grib2 files. I would think the baseline changes from rap/hrrr/fv3r are from grib2 metadata.  But you will notice the following error message have disappeared in runtime logs.  
```
 CRTM_LandSurface_IsValid(INFORMATION) : Invalid Land Surface type
 CRTM_Forward(FAILURE) : Input data check failed for profile #1
 CRTM_Forward(FAILURE) : 1 profiles failed
 ***ERROR*** during crtm_forward call       3
```
My UPP RTs on Hera are at /scratch1/NCEPDEV/stmp2/Wen.Meng:
```
-rw-r--r-- 1 Wen.Meng stmp    75 Oct 27 17:34 rap_2020072316/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp     0 Oct 27 17:34 hrrr_2020060118_pe_test/WRFTWO.GrbF04.diff
-rw-r--r-- 1 Wen.Meng stmp    75 Oct 27 17:34 rap_2020072316_pe_test/WRFPRS.GrbF16.diff
-rw-r--r-- 1 Wen.Meng stmp     0 Oct 27 17:35 hrrr_2020060118/WRFTWO.GrbF04.diff
-rw-r--r-- 1 Wen.Meng stmp 14460 Oct 27 17:37 fv3r_2023062800_pe_test/NATLEV10.tm00.diff
-rw-r--r-- 1 Wen.Meng stmp 14460 Oct 27 17:37 fv3r_2023062800/NATLEV10.tm00.diff
```

**Comment by FernandoAndrade-NOAA** [comment]
Apologies for the delay in test results, Jenkins CI had a GitHub credentials issue, but it seems to be resolved and is properly building for RTs now. I'll post results when available.

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA Hera and Orion UPP RT results are consistent with yours.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
