### PR TITLE
Output lat/lon on four corner points of rotated lat-lon grids in text file

### LINKED ISSUE #530: Output text file with lat/lon corner points needed for RRFS fire weather run
In INITNEMS.f, there is this logic for the NMMB:

          IF (MAPTYPE==205)THEN  !A STAGGERED B-GRID
            open(112,file='latlons_corners.txt',form='formatted' &
             ,status='unknown')
            if(grib=="grib2") then
              write(112,1001)LATSTART/1000,(LONSTART/1000)-360000, &
                  LATSE/1000, &
                  LONSE/1000,LATNW/1000,LONNW/1000,LATLAST/1000, &
                  (LONLAST/1000)-360000
            endif
1001        format(4(I6,x,I7,x))
          close(112)
          ENDIF

The above logic writes out the earth lat/lon of the 4 corner points of the NAM b-grid into the "latlons_corners.txt" file. For the NAM fire weather nest (which can be placed anywhere in the CONUS or Alaska) post-processing, this file is used by the code that creates the WGRIB2 grid specs for the fire weather output grid (lambert conformal over CONUS or polar stereographic over Alaska).

I am working on a 1.5 km RRFS fire weather domain which will replace the NAM fire weather nest. I need the same code fragment placed in current UPP for the regional FV3, presumably in INITPOST_NETCDF.f. The RRFS fire weather run will output (via the inline post) a rotated lat/lon grid, and by having the lat/lons of the 4 corner points of the rotated lat/lon grid, I can calculate the grid specs for the output grid as is now done for the NAM's fire weather nest.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
Output lat/lon on four corner points of rotated lat-lon grid in text file.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricEngle-NOAA I added forecast hour in file name convention. Please test and let me know if you have suggestions. Thanks!

**Comment by EricEngle-NOAA** [comment]
> @EricEngle-NOAA I added forecast hour in file name convention. Please test and let me know if you have suggestions. Thanks!

I think you meant @EricRogers-NOAA?

**Comment by WenMeng-NOAA** [comment]
> > @EricEngle-NOAA I added forecast hour in file name convention. Please test and let me know if you have suggestions. Thanks!
> 
> I think you meant @EricRogers-NOAA?

Yes. Sorry for confusing.

**Comment by WenMeng-NOAA** [comment]
@EricRogers-NOAA  I added forecast hour in file name convention. Please test and let me know if you have suggestions. Thanks!

**Comment by EricRogers-NOAA** [comment]
@EricEngle-NOAA good deduction ;-) Yes, she meant me. @WenMeng-NOAA I'll run a test today.

**Comment by EricEngle-NOAA** [comment]
All good 😄

**Review by HuiyaChuang-NOAA — APPROVED** [review]

**Review by EricRogers-NOAA — APPROVED** [review]
I ran this UPP code last night in a RRFSFW test run and it ran fine.

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on Hera and Orion. No baseline changes in this PR.

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on WCOSS2.

**Pull request merged**
