### PR TITLE
GSL precip type fix

### LINKED ISSUE #729: Correction in GSL precip type diagnosis
The GSL precip type diagnosis inadvertently uses run total accumulated precip instead of 1-h precip from RRFS.  This is an easy fix in SURFCE.f

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
Correcting GSL precip type diagnosis to use 1-h precip instead of run total precip for RRFS.  

The code was tested for RRFS_3km_CONUS system on Jet.

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Can you sync your branch with the latest UPP develop?

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA Would you like me to go ahead and start UPP RTs on Hera and Orion for this PR?

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA Would you like me to go ahead and start UPP RTs on Hera and Orion for this PR?
@FernandoAndrade-NOAA I have been reviewing and testing for RRFS. Please hold off your testing.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA In you PR #695, P-type in PRSLEV were switched to GSL scheme. Another group of P-type generated with non-GSL scheme is kept in NATLEV dataset. I would like to know if this kind of configuration is intentional.

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA In you PR #695, P-type in PRSLEV were switched to GSL scheme. Another group of P-type generated with non-GSL scheme is kept in NATLEV dataset. I would like to know if this kind of configuration is intentional.

@WenMeng-NOAA no that it is not intentional!  I meant to switch all p-types to the GSL scheme.  I can add that change into this PR.  Thank you for pointing it out!

**Comment by AlexanderRichert-NOAA** [comment]
I think I ran into a similar issue recently in the CI. @EricJames-NOAA can you try changing `cache_key: intel2` -> `cache_key: intel**3**` (one place) and `actions/cache@v2`->`actions/cache@v**3**` (two places) in .github/workflows/intel.yml? If that doesn't work then I can dig further.

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were conducted on WCOSS2. There are some changed results from 3DRTMA as:
```
NATLEV:
1371:1211459369:CSNOW:surface:rpn_corr=0.0384651:rpn_rms=0.46011
1373:1211505551:CFRZR:surface:rpn_corr=-0.000302196:rpn_rms=0.276241
1374:1211567817:CRAIN:surface:rpn_corr=0.014156:rpn_rms=0.893746

PRSLEV:
797:715173114:CFRZR:surface:rpn_corr=0.0822664:rpn_rms=0.275226
798:715235380:CRAIN:surface:rpn_corr=0.96125:rpn_rms=0.113849
```

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may start the UPP RT tests on Hera and Orion and check if your testing is consistent with mine on WCOSS2. The fields with undefined values can be ignored, such as: 1023:990098358:ALBDO:surface:rpn_corr=-nan:rpn_rms=undefined

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA, I'm trying to resolve an account issue with the help desk for Orion/Hercules that's caused me being unable to run RTs there. Hera I should be able to run RTs for this PR

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA, I'm trying to resolve an account issue with the help desk for Orion/Hercules that's caused me being unable to run RTs there. Hera I should be able to run RTs for this PR

@FernandoAndrade-NOAA I can run the RT tests on Orion.

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on Hera. The results are consistent with ones from WCOSS2. There will be a baseline update for 3drtma with this PR.

**Comment by WenMeng-NOAA** [comment]
> I think I ran into a similar issue recently in the CI. @EricJames-NOAA can you try changing `cache_key: intel2` -> `cache_key: intel**3**` (one place) and `actions/cache@v2`->`actions/cache@v**3**` (two places) in .github/workflows/intel.yml? If that doesn't work then I can dig further.

@EricJames-NOAA Could you add the fix based on @AlexanderRichert-NOAA 's suggestions in your branch to test this CI failure on  github?

**Comment by EricJames-NOAA** [comment]
> > I think I ran into a similar issue recently in the CI. @EricJames-NOAA can you try changing `cache_key: intel2` -> `cache_key: intel**3**` (one place) and `actions/cache@v2`->`actions/cache@v**3**` (two places) in .github/workflows/intel.yml? If that doesn't work then I can dig further.
> 
> @EricJames-NOAA Could you add the fix based on @AlexanderRichert-NOAA 's suggestions in your branch to test this CI failure on github?

Sorry!  I just committed those changes.  Let's see if the tests succeed now.

**Comment by AlexanderRichert-NOAA** [comment]
@EricJames-NOAA there's one more instance of `actions/cache@v2` to change to v3. Fingers crossed...

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA RTs finished on Hera with the expected changes in 3drtma PRSLEV and NATLEV, apologies for the delay

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA Now the CI is successful. Thanks for the quick fix.

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were completed on Orion. The results are consistent with the ones on WCOSS2.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA RTs finished on Hera with the expected changes in 3drtma PRSLEV and NATLEV, apologies for the delay

@FernandoAndrade-NOAA Please approve this PR.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
