### PR TITLE
[develop]: Add testing chapter to UG

### PR DESCRIPTION
**Pull request by gspetro-NOAA**
This PR: 
- adds a testing chapter to the UPP
- renames `docs` to `doc` for NCO compliance
- adds the UFS logo
- adds a linkcheck functionality for the docs
- automates requirements generation with a `requirements.in` file and pip-tools

Resolves Issue #883

### CODE REVIEW

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA Please sync your branch with the latest UPP develop.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA You may run the  UPP RTs either on Hera and Orion. There should be baseline changes with this PR.

**Comment by FernandoAndrade-NOAA** [comment]
Just leaving an update here that the Hera RT run is unfortunately still sitting in queue. I will update again once tests have concluded.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA You may run the UPP RTs either on Hera and Orion. There should be baseline changes with this PR.

UPP RTs have completed successfully with no changes in results. I believe the fair share values for the epic accounts are currently relatively low, I would expect RTs from my side to take significantly longer until that's resolved.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by WenMeng-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Pull request merged**
